/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'welcome': RouteRecordInfo<
      'welcome',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'about': RouteRecordInfo<
      'about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account': RouteRecordInfo<
      'account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'coverage': RouteRecordInfo<
      'coverage',
      '/coverage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'explore': RouteRecordInfo<
      'explore',
      '/explore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'journeys': RouteRecordInfo<
      'journeys',
      '/journeys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'journey-detail': RouteRecordInfo<
      'journey-detail',
      '/journeys/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'map': RouteRecordInfo<
      'map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'public-route': RouteRecordInfo<
      'public-route',
      '/r/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    'random-rides': RouteRecordInfo<
      'random-rides',
      '/random',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard': RouteRecordInfo<
      'dashboard',
      '/routes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'route-detail': RouteRecordInfo<
      'route-detail',
      '/routes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/system': RouteRecordInfo<
      '/system',
      '/system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/welcome.vue': {
      routes:
        | 'welcome'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | 'about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | 'account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/coverage.vue': {
      routes:
        | 'coverage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/explore.vue': {
      routes:
        | 'explore'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/journeys/index.vue': {
      routes:
        | 'journeys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/journeys/[id].vue': {
      routes:
        | 'journey-detail'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/map.vue': {
      routes:
        | 'map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/r/[slug].vue': {
      routes:
        | 'public-route'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'src/pages/random/index.vue': {
      routes:
        | 'random-rides'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | 'dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/routes/[id].vue': {
      routes:
        | 'route-detail'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/system.vue': {
      routes:
        | '/system'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
