services:
  graphhopper:
    extends:
      service: graphhopper
      file: docker-compose.base.yml
    ports:
      - "8989:8989"

  photon:
    extends:
      service: photon
      file: docker-compose.base.yml
    command: -cors-any
    ports:
      - "2322:2322" # Photon runs on port 2322

  db:
    extends:
      service: db
      file: docker-compose.base.yml
    ports:
      - "5432:5432"
  redis:
    extends:
      service: redis
      file: docker-compose.base.yml
    ports:
      - "6379:6379"