"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import corsheaders.defaults

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-=4hnu)cr(c0xln2e#q-prnw+4z%ey#i=qw!+7b345ogd=uldah",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

AUTH_USER_MODEL = "core.User"

ALLOWED_HOSTS = []

# Axes must come first: it refuses a locked-out client before any password is checked.
AUTHENTICATION_BACKENDS = ["axes.backends.AxesStandaloneBackend", "core.auth.backend.IdentityBackend"]

# The admin is reachable from the internet, so it lives at a path set per deployment
# (production requires one) instead of the /admin/ every bot tries.
ADMIN_PATH = os.environ.get("DJANGO_ADMIN_PATH", "admin").strip("/")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS: list[str] = []
CSRF_TRUSTED_ORIGINS: list[str] = []
CORS_ALLOW_HEADERS = (
    *corsheaders.defaults.default_headers,
    "baggage",  # for sentry
    "sentry-trace",  # for sentry
    "Access-Control-Allow-Origin",
    "X-NoRain-Prefetch",  # dashboard prefetch; see route_forecast
)

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"

# Password-reset links remain valid only briefly and are invalidated after use.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

DEFAULT_FROM_EMAIL = "norain@localhost"
FRONTEND_URL = os.environ.get("FRONTEND_URL", f"http://localhost:{os.environ.get('FRONTEND_PORT') or '3000'}")

# Stripe. Empty in development: the billing endpoints then report 503 rather than
# failing obscurely, and every entitlement can still be set by hand in the admin.
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_ID_PRO = os.environ.get("STRIPE_PRICE_ID_PRO", "")

# Application definition

INSTALLED_APPS = [
    # Above daphne: the first app wins a management command name, and core's runserver
    # extends daphne's with a default port from BACKEND_PORT.
    "core",
    "daphne",
    "ninja",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "channels",
    "django_tasks_db",
    "axes",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
]

# Queue split. `db_worker` has no concurrency flag -- it runs one task at a time -- so
# throughput comes from running several worker processes, and the split keeps a burst of
# provider fetches from starving the work a user is actually waiting on:
#   cells      the provider fan-out, one task per grid cell (many, slow, I/O bound)
#   compute    weather computation from warm cells
#   forecasts  job planning and assembly (few, latency-sensitive: someone is watching)
#   default    geometry, thumbnails, pre-warm scans, maintenance
TASKS = {
    "default": {
        "BACKEND": "django_tasks_db.DatabaseBackend",
        "QUEUES": ["default", "cells", "compute", "forecasts"],
        "OPTIONS": {"id_function": "uuid.uuid7"},
    }
}

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

# Not a page cache. This is the in-flight claim for grid-cell fetches: `cache.add()` is
# atomic, so exactly one caller wins the right to enqueue a fetch for a given cell and the
# rest skip it. A claim cannot live on the cell row itself -- ForecastCell.fetched_at is
# auto_now, so writing a claim there would bump it and make a stale cell look fresh.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
    }
}

# Workers run in their own containers, so progress events reach the daphne process (and
# from there the browser's WebSocket) through the channel layer.
#
# channels_redis waits for messages with a blocking Redis read of 5 s (`brpop_timeout`).
# redis-py 8 also gives every socket a default 5 s read timeout, so an idle wait timed out
# at the same moment and killed the WebSocket with "Timeout reading from ...". The read
# timeout must stay longer than the blocking read; it is still finite, so a dead
# connection is noticed.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [{"address": f"{REDIS_URL}/2", "socket_timeout": 15}]},
    }
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Last, so it can swap the response of a locked-out login for the lockout response.
    "axes.middleware.AxesMiddleware",
]
# None of this runs for websockets: backend/asgi.py hands those to the consumers directly.
# That is fine -- ws/forecast/<id>/ is an ordinary user feature, not the admin -- so do not
# add these middlewares to the Channels stack.

# Failed sign-ins (the SPA login and the admin login) are counted per client IP. Per IP
# rather than per account+IP: a pair lockout never trips when one address tries a
# different account each time, which is what a bot does. The cost is that people behind
# one shared address can be locked out by someone else's failures for the cool-off.
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_RESET_ON_SUCCESS = True
AXES_CLIENT_IP_CALLABLE = "core.auth.lockout.client_ip"
AXES_USERNAME_CALLABLE = "core.auth.lockout.attempted_identity"
AXES_LOCKOUT_CALLABLE = "core.auth.lockout.lockout_response"

# 2FA for the admin: OTPAdminSite (backend/urls.py) asks for a code from an authenticator
# app. The first device is created with `manage.py add_totp_device`.
OTP_TOTP_ISSUER = "NoRain"

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "backend.asgi.application"
WSGI_APPLICATION = "backend.wsgi.application"


# Every environment uses PostGIS so development and tests exercise production's
# constraints and spatial field types rather than silently falling back to SQLite.
def required_db_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"{name} must be set for the PostgreSQL connection.")
    return value


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": required_db_env("DB_NAME"),
        "USER": required_db_env("DB_USER"),
        "PASSWORD": required_db_env("DB_PASSWORD"),
        "HOST": required_db_env("DB_HOST"),
        "PORT": int(required_db_env("DB_PORT")),
        "CONN_MAX_AGE": 60,
    }
}


def homebrew_library(filename: str) -> str | None:
    """Django's find_library never searches Homebrew's lib dirs on macOS; look there ourselves."""
    if sys.platform != "darwin":
        return None
    for prefix in ("/opt/homebrew/lib", "/usr/local/lib"):
        if (candidate := Path(prefix) / filename).exists():
            return str(candidate)
    return None


gdal_library_path = os.environ.get("GDAL_LIBRARY_PATH") or homebrew_library("libgdal.dylib")
if gdal_library_path:
    GDAL_LIBRARY_PATH = gdal_library_path

geos_library_path = os.environ.get("GEOS_LIBRARY_PATH") or homebrew_library("libgeos_c.dylib")
if geos_library_path:
    GEOS_LIBRARY_PATH = geos_library_path


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
