// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CommentOut
 */
export interface CommentOut {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    author: string;
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    editedAt?: Date | null;
    /**
     * 
     */
    canEdit?: boolean;
    /**
     * 
     */
    canDelete?: boolean;
}

/**
 * Check if a given object implements the CommentOut interface.
 */
export function instanceOfCommentOut(value: object): value is CommentOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function CommentOutFromJSON(json: any): CommentOut {
    return CommentOutFromJSONTyped(json, false);
}

export function CommentOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': json['author'],
        'body': json['body'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'editedAt': json['edited_at'] === undefined ? undefined : json['edited_at'] === null ? null : (parseDateTime(json['edited_at'])),
        'canEdit': json['can_edit'] == null ? undefined : json['can_edit'],
        'canDelete': json['can_delete'] == null ? undefined : json['can_delete'],
    };
}

export function CommentOutToJSON(json: any): CommentOut {
    return CommentOutToJSONTyped(json, false);
}

export function CommentOutToJSONTyped(value?: CommentOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'author': value['author'],
        'body': value['body'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'edited_at': value['editedAt'] == null ? value['editedAt'] : serializeDateTime(value['editedAt']),
        'can_edit': value['canEdit'],
        'can_delete': value['canDelete'],
    };
}

