// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentIn
 */
export interface CommentIn {
    /**
     * 
     */
    body: string;
}

/**
 * Check if a given object implements the CommentIn interface.
 */
export function instanceOfCommentIn(value: object): value is CommentIn {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CommentInFromJSON(json: any): CommentIn {
    return CommentInFromJSONTyped(json, false);
}

export function CommentInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentIn {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function CommentInToJSON(json: any): CommentIn {
    return CommentInToJSONTyped(json, false);
}

export function CommentInToJSONTyped(value?: CommentIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

