// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmOut
 */
export interface ConfirmOut {
    /**
     * 
     */
    code: string;
}

/**
 * Check if a given object implements the ConfirmOut interface.
 */
export function instanceOfConfirmOut(value: object): value is ConfirmOut {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ConfirmOutFromJSON(json: any): ConfirmOut {
    return ConfirmOutFromJSONTyped(json, false);
}

export function ConfirmOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmOut {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ConfirmOutToJSON(json: any): ConfirmOut {
    return ConfirmOutToJSONTyped(json, false);
}

export function ConfirmOutToJSONTyped(value?: ConfirmOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

