// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopyIn
 */
export interface CopyIn {
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    scheduleCron?: string;
    /**
     * 
     */
    scheduleDescription?: string;
}

/**
 * Check if a given object implements the CopyIn interface.
 */
export function instanceOfCopyIn(value: object): value is CopyIn {
    return true;
}

export function CopyInFromJSON(json: any): CopyIn {
    return CopyInFromJSONTyped(json, false);
}

export function CopyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'scheduleCron': json['scheduleCron'] == null ? undefined : json['scheduleCron'],
        'scheduleDescription': json['scheduleDescription'] == null ? undefined : json['scheduleDescription'],
    };
}

export function CopyInToJSON(json: any): CopyIn {
    return CopyInToJSONTyped(json, false);
}

export function CopyInToJSONTyped(value?: CopyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'scheduleCron': value['scheduleCron'],
        'scheduleDescription': value['scheduleDescription'],
    };
}

