// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverageAreaOut } from './CoverageAreaOut';
import {
    CoverageAreaOutFromJSON,
    CoverageAreaOutFromJSONTyped,
    CoverageAreaOutToJSON,
    CoverageAreaOutToJSONTyped,
} from './CoverageAreaOut';

/**
 * 
 * @export
 * @interface CoverageOut
 */
export interface CoverageOut {
    /**
     * 
     */
    areas: Array<CoverageAreaOut>;
    /**
     * 
     */
    countries: Array<string>;
}

/**
 * Check if a given object implements the CoverageOut interface.
 */
export function instanceOfCoverageOut(value: object): value is CoverageOut {
    if (!('areas' in value) || value['areas'] === undefined) return false;
    if (!('countries' in value) || value['countries'] === undefined) return false;
    return true;
}

export function CoverageOutFromJSON(json: any): CoverageOut {
    return CoverageOutFromJSONTyped(json, false);
}

export function CoverageOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageOut {
    if (json == null) {
        return json;
    }
    return {
        
        'areas': ((json['areas'] as Array<any>).map(CoverageAreaOutFromJSON)),
        'countries': json['countries'],
    };
}

export function CoverageOutToJSON(json: any): CoverageOut {
    return CoverageOutToJSONTyped(json, false);
}

export function CoverageOutToJSONTyped(value?: CoverageOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areas': ((value['areas'] as Array<any>).map(CoverageAreaOutToJSON)),
        'countries': value['countries'],
    };
}

