// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CoverageAreaOut
 */
export interface CoverageAreaOut {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    nameEn?: string | null;
    /**
     * 
     */
    status?: CoverageAreaOutStatusEnum | null;
    /**
     * 
     */
    note?: string | null;
    /**
     * 
     */
    noteEn?: string | null;
    /**
     * 
     */
    coveredSince?: Date | null;
    /**
     * 
     */
    votes?: number;
    /**
     * 
     */
    voted?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum CoverageAreaOutStatusEnum {
    Covered = 'covered',
    Planned = 'planned',
    Candidate = 'candidate'
}


/**
 * Check if a given object implements the CoverageAreaOut interface.
 */
export function instanceOfCoverageAreaOut(value: object): value is CoverageAreaOut {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function CoverageAreaOutFromJSON(json: any): CoverageAreaOut {
    return CoverageAreaOutFromJSONTyped(json, false);
}

export function CoverageAreaOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageAreaOut {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'nameEn': json['name_en'] === undefined ? undefined : json['name_en'] === null ? null : json['name_en'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'noteEn': json['note_en'] === undefined ? undefined : json['note_en'] === null ? null : json['note_en'],
        'coveredSince': json['covered_since'] === undefined ? undefined : json['covered_since'] === null ? null : (parseDate(json['covered_since'])),
        'votes': json['votes'] == null ? undefined : json['votes'],
        'voted': json['voted'] == null ? undefined : json['voted'],
    };
}

export function CoverageAreaOutToJSON(json: any): CoverageAreaOut {
    return CoverageAreaOutToJSONTyped(json, false);
}

export function CoverageAreaOutToJSONTyped(value?: CoverageAreaOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'name_en': value['nameEn'],
        'status': value['status'],
        'note': value['note'],
        'note_en': value['noteEn'],
        'covered_since': value['coveredSince'] == null ? value['coveredSince'] : serializeDate(value['coveredSince']),
        'votes': value['votes'],
        'voted': value['voted'],
    };
}

