// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartureCandidate } from './DepartureCandidate';
import {
    DepartureCandidateFromJSON,
    DepartureCandidateFromJSONTyped,
    DepartureCandidateToJSON,
    DepartureCandidateToJSONTyped,
} from './DepartureCandidate';

/**
 * 
 * @export
 * @interface DepartureComparison
 */
export interface DepartureComparison {
    /**
     * 
     */
    requestedTime: string;
    /**
     * 
     */
    windowStart: string;
    /**
     * 
     */
    windowEnd: string;
    /**
     * 
     */
    candidates: Array<DepartureCandidate>;
    /**
     * 
     */
    recommendedTime?: string | null;
    /**
     * 
     */
    explanation: string;
}

/**
 * Check if a given object implements the DepartureComparison interface.
 */
export function instanceOfDepartureComparison(value: object): value is DepartureComparison {
    if ((!('requestedTime' in (value as Record<string, any>)) && !('requested_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestedTime'] === undefined && (value as Record<string, any>)['requested_time'] === undefined)) return false;
    if ((!('windowStart' in (value as Record<string, any>)) && !('window_start' in (value as Record<string, any>))) || ((value as Record<string, any>)['windowStart'] === undefined && (value as Record<string, any>)['window_start'] === undefined)) return false;
    if ((!('windowEnd' in (value as Record<string, any>)) && !('window_end' in (value as Record<string, any>))) || ((value as Record<string, any>)['windowEnd'] === undefined && (value as Record<string, any>)['window_end'] === undefined)) return false;
    if (!('candidates' in value) || value['candidates'] === undefined) return false;
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    return true;
}

export function DepartureComparisonFromJSON(json: any): DepartureComparison {
    return DepartureComparisonFromJSONTyped(json, false);
}

export function DepartureComparisonFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartureComparison {
    if (json == null) {
        return json;
    }
    return {
        
        'requestedTime': json['requested_time'],
        'windowStart': json['window_start'],
        'windowEnd': json['window_end'],
        'candidates': ((json['candidates'] as Array<any>).map(DepartureCandidateFromJSON)),
        'recommendedTime': json['recommended_time'] === undefined ? undefined : json['recommended_time'] === null ? null : json['recommended_time'],
        'explanation': json['explanation'],
    };
}

export function DepartureComparisonToJSON(json: any): DepartureComparison {
    return DepartureComparisonToJSONTyped(json, false);
}

export function DepartureComparisonToJSONTyped(value?: DepartureComparison | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requested_time': value['requestedTime'],
        'window_start': value['windowStart'],
        'window_end': value['windowEnd'],
        'candidates': ((value['candidates'] as Array<any>).map(DepartureCandidateToJSON)),
        'recommended_time': value['recommendedTime'],
        'explanation': value['explanation'],
    };
}

