// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartureCandidate
 */
export interface DepartureCandidate {
    /**
     * 
     */
    departureTime: string;
    /**
     * 
     */
    arrivalTime: string;
    /**
     * 
     */
    available: boolean;
    /**
     * 
     */
    rideScore?: number | null;
    /**
     * 
     */
    rideLabel: string;
}

/**
 * Check if a given object implements the DepartureCandidate interface.
 */
export function instanceOfDepartureCandidate(value: object): value is DepartureCandidate {
    if ((!('departureTime' in (value as Record<string, any>)) && !('departure_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['departureTime'] === undefined && (value as Record<string, any>)['departure_time'] === undefined)) return false;
    if ((!('arrivalTime' in (value as Record<string, any>)) && !('arrival_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['arrivalTime'] === undefined && (value as Record<string, any>)['arrival_time'] === undefined)) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if ((!('rideLabel' in (value as Record<string, any>)) && !('ride_label' in (value as Record<string, any>))) || ((value as Record<string, any>)['rideLabel'] === undefined && (value as Record<string, any>)['ride_label'] === undefined)) return false;
    return true;
}

export function DepartureCandidateFromJSON(json: any): DepartureCandidate {
    return DepartureCandidateFromJSONTyped(json, false);
}

export function DepartureCandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartureCandidate {
    if (json == null) {
        return json;
    }
    return {
        
        'departureTime': json['departure_time'],
        'arrivalTime': json['arrival_time'],
        'available': json['available'],
        'rideScore': json['ride_score'] === undefined ? undefined : json['ride_score'] === null ? null : json['ride_score'],
        'rideLabel': json['ride_label'],
    };
}

export function DepartureCandidateToJSON(json: any): DepartureCandidate {
    return DepartureCandidateToJSONTyped(json, false);
}

export function DepartureCandidateToJSONTyped(value?: DepartureCandidate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departure_time': value['departureTime'],
        'arrival_time': value['arrivalTime'],
        'available': value['available'],
        'ride_score': value['rideScore'],
        'ride_label': value['rideLabel'],
    };
}

