// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EchoIn
 */
export interface EchoIn {
    /**
     * 
     */
    challenge: string;
    /**
     * 
     */
    step: number;
    /**
     * 
     */
    token?: string;
}

/**
 * Check if a given object implements the EchoIn interface.
 */
export function instanceOfEchoIn(value: object): value is EchoIn {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function EchoInFromJSON(json: any): EchoIn {
    return EchoInFromJSONTyped(json, false);
}

export function EchoInFromJSONTyped(json: any, ignoreDiscriminator: boolean): EchoIn {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'step': json['step'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function EchoInToJSON(json: any): EchoIn {
    return EchoInToJSONTyped(json, false);
}

export function EchoInToJSONTyped(value?: EchoIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'step': value['step'],
        'token': value['token'],
    };
}

