// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EchoOut
 */
export interface EchoOut {
    /**
     * 
     */
    token: string;
}

/**
 * Check if a given object implements the EchoOut interface.
 */
export function instanceOfEchoOut(value: object): value is EchoOut {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function EchoOutFromJSON(json: any): EchoOut {
    return EchoOutFromJSONTyped(json, false);
}

export function EchoOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EchoOut {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function EchoOutToJSON(json: any): EchoOut {
    return EchoOutToJSONTyped(json, false);
}

export function EchoOutToJSONTyped(value?: EchoOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

