// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElevationPoint
 */
export interface ElevationPoint {
    /**
     * 
     */
    distanceM: number;
    /**
     * 
     */
    elapsedS: number;
    /**
     * 
     */
    elevationM: number | null;
}

/**
 * Check if a given object implements the ElevationPoint interface.
 */
export function instanceOfElevationPoint(value: object): value is ElevationPoint {
    if ((!('distanceM' in (value as Record<string, any>)) && !('distance_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['distanceM'] === undefined && (value as Record<string, any>)['distance_m'] === undefined)) return false;
    if ((!('elapsedS' in (value as Record<string, any>)) && !('elapsed_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['elapsedS'] === undefined && (value as Record<string, any>)['elapsed_s'] === undefined)) return false;
    if ((!('elevationM' in (value as Record<string, any>)) && !('elevation_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['elevationM'] === undefined && (value as Record<string, any>)['elevation_m'] === undefined)) return false;
    return true;
}

export function ElevationPointFromJSON(json: any): ElevationPoint {
    return ElevationPointFromJSONTyped(json, false);
}

export function ElevationPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevationPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'distanceM': json['distance_m'],
        'elapsedS': json['elapsed_s'],
        'elevationM': json['elevation_m'],
    };
}

export function ElevationPointToJSON(json: any): ElevationPoint {
    return ElevationPointToJSONTyped(json, false);
}

export function ElevationPointToJSONTyped(value?: ElevationPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distance_m': value['distanceM'],
        'elapsed_s': value['elapsedS'],
        'elevation_m': value['elevationM'],
    };
}

