// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElevationIn
 */
export interface ElevationIn {
    /**
     * 
     */
    coordinates: Array<Array<number>>;
    /**
     * 
     */
    totalSeconds: number;
    /**
     * 
     */
    vertexTimes?: Array<number> | null;
}

/**
 * Check if a given object implements the ElevationIn interface.
 */
export function instanceOfElevationIn(value: object): value is ElevationIn {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if (!('totalSeconds' in value) || value['totalSeconds'] === undefined) return false;
    return true;
}

export function ElevationInFromJSON(json: any): ElevationIn {
    return ElevationInFromJSONTyped(json, false);
}

export function ElevationInFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElevationIn {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'],
        'totalSeconds': json['totalSeconds'],
        'vertexTimes': json['vertexTimes'] === undefined ? undefined : json['vertexTimes'] === null ? null : json['vertexTimes'],
    };
}

export function ElevationInToJSON(json: any): ElevationIn {
    return ElevationInToJSONTyped(json, false);
}

export function ElevationInToJSONTyped(value?: ElevationIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
        'totalSeconds': value['totalSeconds'],
        'vertexTimes': value['vertexTimes'],
    };
}

