// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnsembleRange } from './EnsembleRange';
import {
    EnsembleRangeFromJSON,
    EnsembleRangeFromJSONTyped,
    EnsembleRangeToJSON,
    EnsembleRangeToJSONTyped,
} from './EnsembleRange';

/**
 * 
 * @export
 * @interface EnsembleModelStatistics
 */
export interface EnsembleModelStatistics {
    /**
     * 
     */
    metrics: { [key: string]: EnsembleRange; };
    /**
     * 
     */
    pop?: number | null;
    /**
     * 
     */
    rainIfWet?: number | null;
    /**
     * 
     */
    model: string;
}

/**
 * Check if a given object implements the EnsembleModelStatistics interface.
 */
export function instanceOfEnsembleModelStatistics(value: object): value is EnsembleModelStatistics {
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function EnsembleModelStatisticsFromJSON(json: any): EnsembleModelStatistics {
    return EnsembleModelStatisticsFromJSONTyped(json, false);
}

export function EnsembleModelStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnsembleModelStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'metrics': (mapValues(json['metrics'], EnsembleRangeFromJSON)),
        'pop': json['pop'] === undefined ? undefined : json['pop'] === null ? null : json['pop'],
        'rainIfWet': json['rain_if_wet'] === undefined ? undefined : json['rain_if_wet'] === null ? null : json['rain_if_wet'],
        'model': json['model'],
    };
}

export function EnsembleModelStatisticsToJSON(json: any): EnsembleModelStatistics {
    return EnsembleModelStatisticsToJSONTyped(json, false);
}

export function EnsembleModelStatisticsToJSONTyped(value?: EnsembleModelStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metrics': (mapValues(value['metrics'], EnsembleRangeToJSON)),
        'pop': value['pop'],
        'rain_if_wet': value['rainIfWet'],
        'model': value['model'],
    };
}

