// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnsembleRange
 */
export interface EnsembleRange {
    /**
     * 
     */
    median?: number | null;
    /**
     * 
     */
    memberCount: number;
    /**
     * 
     */
    p10?: number | null;
    /**
     * 
     */
    p90?: number | null;
}

/**
 * Check if a given object implements the EnsembleRange interface.
 */
export function instanceOfEnsembleRange(value: object): value is EnsembleRange {
    if ((!('memberCount' in (value as Record<string, any>)) && !('member_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['memberCount'] === undefined && (value as Record<string, any>)['member_count'] === undefined)) return false;
    return true;
}

export function EnsembleRangeFromJSON(json: any): EnsembleRange {
    return EnsembleRangeFromJSONTyped(json, false);
}

export function EnsembleRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnsembleRange {
    if (json == null) {
        return json;
    }
    return {
        
        'median': json['median'] === undefined ? undefined : json['median'] === null ? null : json['median'],
        'memberCount': json['member_count'],
        'p10': json['p10'] === undefined ? undefined : json['p10'] === null ? null : json['p10'],
        'p90': json['p90'] === undefined ? undefined : json['p90'] === null ? null : json['p90'],
    };
}

export function EnsembleRangeToJSON(json: any): EnsembleRange {
    return EnsembleRangeToJSONTyped(json, false);
}

export function EnsembleRangeToJSONTyped(value?: EnsembleRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'median': value['median'],
        'member_count': value['memberCount'],
        'p10': value['p10'],
        'p90': value['p90'],
    };
}

