// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnsembleModelStatistics } from './EnsembleModelStatistics';
import {
    EnsembleModelStatisticsFromJSON,
    EnsembleModelStatisticsFromJSONTyped,
    EnsembleModelStatisticsToJSON,
    EnsembleModelStatisticsToJSONTyped,
} from './EnsembleModelStatistics';
import type { EnsembleRange } from './EnsembleRange';
import {
    EnsembleRangeFromJSON,
    EnsembleRangeFromJSONTyped,
    EnsembleRangeToJSON,
    EnsembleRangeToJSONTyped,
} from './EnsembleRange';

/**
 * 
 * @export
 * @interface ForecastUncertainty
 */
export interface ForecastUncertainty {
    /**
     * 
     */
    fetchedAt: string;
    /**
     * 
     */
    forecastTime: string;
    /**
     * 
     */
    metrics: { [key: string]: EnsembleRange; };
    /**
     * 
     */
    models: Array<EnsembleModelStatistics>;
    /**
     * 
     */
    pop?: number | null;
    /**
     * 
     */
    precipitationIntervalS?: number;
    /**
     * 
     */
    rainIfWet?: number | null;
    /**
     * 
     */
    requestedModels: Array<string>;
    /**
     * 
     */
    source?: string;
}

/**
 * Check if a given object implements the ForecastUncertainty interface.
 */
export function instanceOfForecastUncertainty(value: object): value is ForecastUncertainty {
    if ((!('fetchedAt' in (value as Record<string, any>)) && !('fetched_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['fetchedAt'] === undefined && (value as Record<string, any>)['fetched_at'] === undefined)) return false;
    if ((!('forecastTime' in (value as Record<string, any>)) && !('forecast_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['forecastTime'] === undefined && (value as Record<string, any>)['forecast_time'] === undefined)) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    if ((!('requestedModels' in (value as Record<string, any>)) && !('requested_models' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestedModels'] === undefined && (value as Record<string, any>)['requested_models'] === undefined)) return false;
    return true;
}

export function ForecastUncertaintyFromJSON(json: any): ForecastUncertainty {
    return ForecastUncertaintyFromJSONTyped(json, false);
}

export function ForecastUncertaintyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastUncertainty {
    if (json == null) {
        return json;
    }
    return {
        
        'fetchedAt': json['fetched_at'],
        'forecastTime': json['forecast_time'],
        'metrics': (mapValues(json['metrics'], EnsembleRangeFromJSON)),
        'models': ((json['models'] as Array<any>).map(EnsembleModelStatisticsFromJSON)),
        'pop': json['pop'] === undefined ? undefined : json['pop'] === null ? null : json['pop'],
        'precipitationIntervalS': json['precipitation_interval_s'] == null ? undefined : json['precipitation_interval_s'],
        'rainIfWet': json['rain_if_wet'] === undefined ? undefined : json['rain_if_wet'] === null ? null : json['rain_if_wet'],
        'requestedModels': json['requested_models'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function ForecastUncertaintyToJSON(json: any): ForecastUncertainty {
    return ForecastUncertaintyToJSONTyped(json, false);
}

export function ForecastUncertaintyToJSONTyped(value?: ForecastUncertainty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fetched_at': value['fetchedAt'],
        'forecast_time': value['forecastTime'],
        'metrics': (mapValues(value['metrics'], EnsembleRangeToJSON)),
        'models': ((value['models'] as Array<any>).map(EnsembleModelStatisticsToJSON)),
        'pop': value['pop'],
        'precipitation_interval_s': value['precipitationIntervalS'],
        'rain_if_wet': value['rainIfWet'],
        'requested_models': value['requestedModels'],
        'source': value['source'],
    };
}

