// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnsembleRange } from './EnsembleRange';
import {
    EnsembleRangeFromJSON,
    EnsembleRangeFromJSONTyped,
    EnsembleRangeToJSON,
    EnsembleRangeToJSONTyped,
} from './EnsembleRange';

/**
 * A sample's ensemble spread without the per-model breakdown.
 * 
 * The breakdown is most of the bytes and only the details panel shows it, for one point
 * at a time, so it comes from ``/forecast_jobs/{id}/samples/{index}/uncertainty``.
 * @export
 * @interface ForecastUncertaintySummary
 */
export interface ForecastUncertaintySummary {
    /**
     * 
     */
    fetchedAt: string;
    /**
     * 
     */
    forecastTime: string;
    /**
     * 
     */
    metrics: { [key: string]: EnsembleRange; };
    /**
     * 
     */
    pop?: number | null;
    /**
     * 
     */
    precipitationIntervalS?: number;
    /**
     * 
     */
    rainIfWet?: number | null;
    /**
     * 
     */
    source?: string;
}

/**
 * Check if a given object implements the ForecastUncertaintySummary interface.
 */
export function instanceOfForecastUncertaintySummary(value: object): value is ForecastUncertaintySummary {
    if ((!('fetchedAt' in (value as Record<string, any>)) && !('fetched_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['fetchedAt'] === undefined && (value as Record<string, any>)['fetched_at'] === undefined)) return false;
    if ((!('forecastTime' in (value as Record<string, any>)) && !('forecast_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['forecastTime'] === undefined && (value as Record<string, any>)['forecast_time'] === undefined)) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    return true;
}

export function ForecastUncertaintySummaryFromJSON(json: any): ForecastUncertaintySummary {
    return ForecastUncertaintySummaryFromJSONTyped(json, false);
}

export function ForecastUncertaintySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastUncertaintySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'fetchedAt': json['fetched_at'],
        'forecastTime': json['forecast_time'],
        'metrics': (mapValues(json['metrics'], EnsembleRangeFromJSON)),
        'pop': json['pop'] === undefined ? undefined : json['pop'] === null ? null : json['pop'],
        'precipitationIntervalS': json['precipitation_interval_s'] == null ? undefined : json['precipitation_interval_s'],
        'rainIfWet': json['rain_if_wet'] === undefined ? undefined : json['rain_if_wet'] === null ? null : json['rain_if_wet'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function ForecastUncertaintySummaryToJSON(json: any): ForecastUncertaintySummary {
    return ForecastUncertaintySummaryToJSONTyped(json, false);
}

export function ForecastUncertaintySummaryToJSONTyped(value?: ForecastUncertaintySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fetched_at': value['fetchedAt'],
        'forecast_time': value['forecastTime'],
        'metrics': (mapValues(value['metrics'], EnsembleRangeToJSON)),
        'pop': value['pop'],
        'precipitation_interval_s': value['precipitationIntervalS'],
        'rain_if_wet': value['rainIfWet'],
        'source': value['source'],
    };
}

