// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForecastUncertaintySummary } from './ForecastUncertaintySummary';
import {
    ForecastUncertaintySummaryFromJSON,
    ForecastUncertaintySummaryFromJSONTyped,
    ForecastUncertaintySummaryToJSON,
    ForecastUncertaintySummaryToJSONTyped,
} from './ForecastUncertaintySummary';

/**
 * 
 * @export
 * @interface ForecastSampleOut
 */
export interface ForecastSampleOut {
    /**
     * 
     */
    lat: number;
    /**
     * 
     */
    lon: number;
    /**
     * 
     */
    elapsedS: number;
    /**
     * 
     */
    eta: string;
    /**
     * 
     */
    rainMm: number;
    /**
     * 
     */
    precipitationIntervalS?: number | null;
    /**
     * 
     */
    rainRateMmH?: number | null;
    /**
     * 
     */
    probabilitySource?: string | null;
    /**
     * 
     */
    uncertainty?: ForecastUncertaintySummary | null;
    /**
     * 
     */
    pop?: number | null;
    /**
     * 
     */
    rainIfWet?: number | null;
    /**
     * 
     */
    temp: number;
    /**
     * 
     */
    windSpeed?: number | null;
    /**
     * 
     */
    windGust?: number | null;
    /**
     * 
     */
    windDir?: number | null;
    /**
     * 
     */
    headwind?: number | null;
    /**
     * 
     */
    crosswind?: number | null;
    /**
     * 
     */
    windPowerW?: number | null;
    /**
     * 
     */
    sampleIndex?: number | null;
    /**
     * 
     */
    windCoverage?: number | null;
    /**
     * 
     */
    weatherCode?: number | null;
    /**
     * 
     */
    weatherDesc: string;
    /**
     * 
     */
    stationCount?: number | null;
    /**
     * 
     */
    rideScore?: number | null;
    /**
     * 
     */
    rideLabel?: string | null;
    /**
     * 
     */
    windEffortLevel?: string | null;
    /**
     * 
     */
    frostLevel?: string | null;
}

/**
 * Check if a given object implements the ForecastSampleOut interface.
 */
export function instanceOfForecastSampleOut(value: object): value is ForecastSampleOut {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if ((!('elapsedS' in (value as Record<string, any>)) && !('elapsed_s' in (value as Record<string, any>))) || ((value as Record<string, any>)['elapsedS'] === undefined && (value as Record<string, any>)['elapsed_s'] === undefined)) return false;
    if (!('eta' in value) || value['eta'] === undefined) return false;
    if ((!('rainMm' in (value as Record<string, any>)) && !('rain_mm' in (value as Record<string, any>))) || ((value as Record<string, any>)['rainMm'] === undefined && (value as Record<string, any>)['rain_mm'] === undefined)) return false;
    if (!('temp' in value) || value['temp'] === undefined) return false;
    if ((!('weatherDesc' in (value as Record<string, any>)) && !('weather_desc' in (value as Record<string, any>))) || ((value as Record<string, any>)['weatherDesc'] === undefined && (value as Record<string, any>)['weather_desc'] === undefined)) return false;
    return true;
}

export function ForecastSampleOutFromJSON(json: any): ForecastSampleOut {
    return ForecastSampleOutFromJSONTyped(json, false);
}

export function ForecastSampleOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastSampleOut {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lon': json['lon'],
        'elapsedS': json['elapsed_s'],
        'eta': json['eta'],
        'rainMm': json['rain_mm'],
        'precipitationIntervalS': json['precipitation_interval_s'] === undefined ? undefined : json['precipitation_interval_s'] === null ? null : json['precipitation_interval_s'],
        'rainRateMmH': json['rain_rate_mm_h'] === undefined ? undefined : json['rain_rate_mm_h'] === null ? null : json['rain_rate_mm_h'],
        'probabilitySource': json['probability_source'] === undefined ? undefined : json['probability_source'] === null ? null : json['probability_source'],
        'uncertainty': json['uncertainty'] === undefined ? undefined : json['uncertainty'] === null ? null : ForecastUncertaintySummaryFromJSON(json['uncertainty']),
        'pop': json['pop'] === undefined ? undefined : json['pop'] === null ? null : json['pop'],
        'rainIfWet': json['rain_if_wet'] === undefined ? undefined : json['rain_if_wet'] === null ? null : json['rain_if_wet'],
        'temp': json['temp'],
        'windSpeed': json['wind_speed'] === undefined ? undefined : json['wind_speed'] === null ? null : json['wind_speed'],
        'windGust': json['wind_gust'] === undefined ? undefined : json['wind_gust'] === null ? null : json['wind_gust'],
        'windDir': json['wind_dir'] === undefined ? undefined : json['wind_dir'] === null ? null : json['wind_dir'],
        'headwind': json['headwind'] === undefined ? undefined : json['headwind'] === null ? null : json['headwind'],
        'crosswind': json['crosswind'] === undefined ? undefined : json['crosswind'] === null ? null : json['crosswind'],
        'windPowerW': json['wind_power_w'] === undefined ? undefined : json['wind_power_w'] === null ? null : json['wind_power_w'],
        'sampleIndex': json['sample_index'] === undefined ? undefined : json['sample_index'] === null ? null : json['sample_index'],
        'windCoverage': json['wind_coverage'] === undefined ? undefined : json['wind_coverage'] === null ? null : json['wind_coverage'],
        'weatherCode': json['weather_code'] === undefined ? undefined : json['weather_code'] === null ? null : json['weather_code'],
        'weatherDesc': json['weather_desc'],
        'stationCount': json['station_count'] === undefined ? undefined : json['station_count'] === null ? null : json['station_count'],
        'rideScore': json['ride_score'] === undefined ? undefined : json['ride_score'] === null ? null : json['ride_score'],
        'rideLabel': json['ride_label'] === undefined ? undefined : json['ride_label'] === null ? null : json['ride_label'],
        'windEffortLevel': json['wind_effort_level'] === undefined ? undefined : json['wind_effort_level'] === null ? null : json['wind_effort_level'],
        'frostLevel': json['frost_level'] === undefined ? undefined : json['frost_level'] === null ? null : json['frost_level'],
    };
}

export function ForecastSampleOutToJSON(json: any): ForecastSampleOut {
    return ForecastSampleOutToJSONTyped(json, false);
}

export function ForecastSampleOutToJSONTyped(value?: ForecastSampleOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lon': value['lon'],
        'elapsed_s': value['elapsedS'],
        'eta': value['eta'],
        'rain_mm': value['rainMm'],
        'precipitation_interval_s': value['precipitationIntervalS'],
        'rain_rate_mm_h': value['rainRateMmH'],
        'probability_source': value['probabilitySource'],
        'uncertainty': ForecastUncertaintySummaryToJSON(value['uncertainty']),
        'pop': value['pop'],
        'rain_if_wet': value['rainIfWet'],
        'temp': value['temp'],
        'wind_speed': value['windSpeed'],
        'wind_gust': value['windGust'],
        'wind_dir': value['windDir'],
        'headwind': value['headwind'],
        'crosswind': value['crosswind'],
        'wind_power_w': value['windPowerW'],
        'sample_index': value['sampleIndex'],
        'wind_coverage': value['windCoverage'],
        'weather_code': value['weatherCode'],
        'weather_desc': value['weatherDesc'],
        'station_count': value['stationCount'],
        'ride_score': value['rideScore'],
        'ride_label': value['rideLabel'],
        'wind_effort_level': value['windEffortLevel'],
        'frost_level': value['frostLevel'],
    };
}

