// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum GeometrySource {
    Graphhopper = 'graphhopper',
    Imported = 'imported'
}


export function instanceOfGeometrySource(value: any): boolean {
    for (const key in GeometrySource) {
        if (Object.prototype.hasOwnProperty.call(GeometrySource, key)) {
            if (GeometrySource[key as keyof typeof GeometrySource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GeometrySourceFromJSON(json: any): GeometrySource {
    return GeometrySourceFromJSONTyped(json, false);
}

export function GeometrySourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometrySource {
    return json as GeometrySource;
}

export function GeometrySourceToJSON(value?: GeometrySource | null): any {
    return value as any;
}

export function GeometrySourceToJSONTyped(value: any, ignoreDiscriminator: boolean): GeometrySource {
    return value as GeometrySource;
}

