// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeometrySchema
 */
export interface GeometrySchema {
    /**
     * 
     */
    coordinates: Array<number>;
    /**
     * 
     */
    type?: string;
}

/**
 * Check if a given object implements the GeometrySchema interface.
 */
export function instanceOfGeometrySchema(value: object): value is GeometrySchema {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function GeometrySchemaFromJSON(json: any): GeometrySchema {
    return GeometrySchemaFromJSONTyped(json, false);
}

export function GeometrySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometrySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function GeometrySchemaToJSON(json: any): GeometrySchema {
    return GeometrySchemaToJSONTyped(json, false);
}

export function GeometrySchemaToJSONTyped(value?: GeometrySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
        'type': value['type'],
    };
}

