// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GpxPathOut
 */
export interface GpxPathOut {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    coordinates: Array<Array<number>>;
    /**
     * 
     */
    distanceM: number;
    /**
     * 
     */
    routingPoints: Array<Array<number>>;
}

/**
 * Check if a given object implements the GpxPathOut interface.
 */
export function instanceOfGpxPathOut(value: object): value is GpxPathOut {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if ((!('distanceM' in (value as Record<string, any>)) && !('distance_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['distanceM'] === undefined && (value as Record<string, any>)['distance_m'] === undefined)) return false;
    if ((!('routingPoints' in (value as Record<string, any>)) && !('routing_points' in (value as Record<string, any>))) || ((value as Record<string, any>)['routingPoints'] === undefined && (value as Record<string, any>)['routing_points'] === undefined)) return false;
    return true;
}

export function GpxPathOutFromJSON(json: any): GpxPathOut {
    return GpxPathOutFromJSONTyped(json, false);
}

export function GpxPathOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpxPathOut {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'coordinates': json['coordinates'],
        'distanceM': json['distance_m'],
        'routingPoints': json['routing_points'],
    };
}

export function GpxPathOutToJSON(json: any): GpxPathOut {
    return GpxPathOutToJSONTyped(json, false);
}

export function GpxPathOutToJSONTyped(value?: GpxPathOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'coordinates': value['coordinates'],
        'distance_m': value['distanceM'],
        'routing_points': value['routingPoints'],
    };
}

