// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { JourneyStageOut } from './JourneyStageOut';
import {
    JourneyStageOutFromJSON,
    JourneyStageOutFromJSONTyped,
    JourneyStageOutToJSON,
    JourneyStageOutToJSONTyped,
} from './JourneyStageOut';
import type { PoiOut } from './PoiOut';
import {
    PoiOutFromJSON,
    PoiOutFromJSONTyped,
    PoiOutToJSON,
    PoiOutToJSONTyped,
} from './PoiOut';

/**
 * 
 * @export
 * @interface JourneyDayOut
 */
export interface JourneyDayOut {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    index: number;
    /**
     * 
     */
    date: Date;
    /**
     * 
     */
    start: Array<number>;
    /**
     * 
     */
    end: Array<number>;
    /**
     * 
     */
    lodging?: PoiOut | null;
    /**
     * 
     */
    lodgingMissing?: boolean;
    /**
     * 
     */
    weatherRouted?: boolean;
    /**
     * 
     */
    forecastAvailable?: boolean;
    /**
     * 
     */
    stages?: Array<JourneyStageOut>;
}

/**
 * Check if a given object implements the JourneyDayOut interface.
 */
export function instanceOfJourneyDayOut(value: object): value is JourneyDayOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function JourneyDayOutFromJSON(json: any): JourneyDayOut {
    return JourneyDayOutFromJSONTyped(json, false);
}

export function JourneyDayOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyDayOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'index': json['index'],
        'date': (json['date'] == null ? json['date'] : parseDate(json['date'])),
        'start': json['start'],
        'end': json['end'],
        'lodging': json['lodging'] === undefined ? undefined : json['lodging'] === null ? null : PoiOutFromJSON(json['lodging']),
        'lodgingMissing': json['lodging_missing'] == null ? undefined : json['lodging_missing'],
        'weatherRouted': json['weather_routed'] == null ? undefined : json['weather_routed'],
        'forecastAvailable': json['forecast_available'] == null ? undefined : json['forecast_available'],
        'stages': json['stages'] == null ? undefined : ((json['stages'] as Array<any>).map(JourneyStageOutFromJSON)),
    };
}

export function JourneyDayOutToJSON(json: any): JourneyDayOut {
    return JourneyDayOutToJSONTyped(json, false);
}

export function JourneyDayOutToJSONTyped(value?: JourneyDayOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'index': value['index'],
        'date': value['date'] == null ? value['date'] : serializeDate(value['date']),
        'start': value['start'],
        'end': value['end'],
        'lodging': PoiOutToJSON(value['lodging']),
        'lodging_missing': value['lodgingMissing'],
        'weather_routed': value['weatherRouted'],
        'forecast_available': value['forecastAvailable'],
        'stages': value['stages'] == null ? undefined : ((value['stages'] as Array<any>).map(JourneyStageOutToJSON)),
    };
}

