// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RoadPrefsIn } from './RoadPrefsIn';
import {
    RoadPrefsInFromJSON,
    RoadPrefsInFromJSONTyped,
    RoadPrefsInToJSON,
    RoadPrefsInToJSONTyped,
} from './RoadPrefsIn';
import type { WeatherPrefsIn } from './WeatherPrefsIn';
import {
    WeatherPrefsInFromJSON,
    WeatherPrefsInFromJSONTyped,
    WeatherPrefsInToJSON,
    WeatherPrefsInToJSONTyped,
} from './WeatherPrefsIn';

/**
 * 
 * @export
 * @interface JourneyIn
 */
export interface JourneyIn {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    startLat: number;
    /**
     * 
     */
    startLon: number;
    /**
     * 
     */
    startName: string;
    /**
     * 
     */
    destLat: number;
    /**
     * 
     */
    destLon: number;
    /**
     * 
     */
    destName: string;
    /**
     * 
     */
    viaPoints?: Array<Array<number>>;
    /**
     * 
     */
    profile?: string;
    /**
     * 
     */
    startDate: Date;
    /**
     * 
     */
    earliestStart?: string;
    /**
     * 
     */
    latestArrival?: string;
    /**
     * 
     */
    maxDaySeconds?: number | null;
    /**
     * 
     */
    maxDayDistanceM?: number | null;
    /**
     * 
     */
    maxLegSeconds?: number | null;
    /**
     * 
     */
    maxLegDistanceM?: number | null;
    /**
     * 
     */
    poiCategories?: Array<string>;
    /**
     * 
     */
    lodgingKinds?: Array<string>;
    /**
     * 
     */
    roadPrefs?: RoadPrefsIn;
    /**
     * 
     */
    weatherPrefs?: WeatherPrefsIn;
}

/**
 * Check if a given object implements the JourneyIn interface.
 */
export function instanceOfJourneyIn(value: object): value is JourneyIn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startLat' in value) || value['startLat'] === undefined) return false;
    if (!('startLon' in value) || value['startLon'] === undefined) return false;
    if (!('startName' in value) || value['startName'] === undefined) return false;
    if (!('destLat' in value) || value['destLat'] === undefined) return false;
    if (!('destLon' in value) || value['destLon'] === undefined) return false;
    if (!('destName' in value) || value['destName'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function JourneyInFromJSON(json: any): JourneyIn {
    return JourneyInFromJSONTyped(json, false);
}

export function JourneyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'startLat': json['startLat'],
        'startLon': json['startLon'],
        'startName': json['startName'],
        'destLat': json['destLat'],
        'destLon': json['destLon'],
        'destName': json['destName'],
        'viaPoints': json['viaPoints'] == null ? undefined : json['viaPoints'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'startDate': (json['startDate'] == null ? json['startDate'] : parseDate(json['startDate'])),
        'earliestStart': json['earliestStart'] == null ? undefined : json['earliestStart'],
        'latestArrival': json['latestArrival'] == null ? undefined : json['latestArrival'],
        'maxDaySeconds': json['maxDaySeconds'] === undefined ? undefined : json['maxDaySeconds'] === null ? null : json['maxDaySeconds'],
        'maxDayDistanceM': json['maxDayDistanceM'] === undefined ? undefined : json['maxDayDistanceM'] === null ? null : json['maxDayDistanceM'],
        'maxLegSeconds': json['maxLegSeconds'] === undefined ? undefined : json['maxLegSeconds'] === null ? null : json['maxLegSeconds'],
        'maxLegDistanceM': json['maxLegDistanceM'] === undefined ? undefined : json['maxLegDistanceM'] === null ? null : json['maxLegDistanceM'],
        'poiCategories': json['poiCategories'] == null ? undefined : json['poiCategories'],
        'lodgingKinds': json['lodgingKinds'] == null ? undefined : json['lodgingKinds'],
        'roadPrefs': json['roadPrefs'] == null ? undefined : RoadPrefsInFromJSON(json['roadPrefs']),
        'weatherPrefs': json['weatherPrefs'] == null ? undefined : WeatherPrefsInFromJSON(json['weatherPrefs']),
    };
}

export function JourneyInToJSON(json: any): JourneyIn {
    return JourneyInToJSONTyped(json, false);
}

export function JourneyInToJSONTyped(value?: JourneyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'startLat': value['startLat'],
        'startLon': value['startLon'],
        'startName': value['startName'],
        'destLat': value['destLat'],
        'destLon': value['destLon'],
        'destName': value['destName'],
        'viaPoints': value['viaPoints'],
        'profile': value['profile'],
        'startDate': value['startDate'] == null ? value['startDate'] : serializeDate(value['startDate']),
        'earliestStart': value['earliestStart'],
        'latestArrival': value['latestArrival'],
        'maxDaySeconds': value['maxDaySeconds'],
        'maxDayDistanceM': value['maxDayDistanceM'],
        'maxLegSeconds': value['maxLegSeconds'],
        'maxLegDistanceM': value['maxLegDistanceM'],
        'poiCategories': value['poiCategories'],
        'lodgingKinds': value['lodgingKinds'],
        'roadPrefs': RoadPrefsInToJSON(value['roadPrefs']),
        'weatherPrefs': WeatherPrefsInToJSON(value['weatherPrefs']),
    };
}

