// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Why a variant ranks where it does, as data the SPA words (``journeys.rank_day``).
 * 
 * ``missing_stop``: no reachable stop for ``category``. ``gap``: ``minutes`` / ``km`` of a leg
 * without ``category``. ``detour``: ``km`` off the line to ``name`` (or ``category``).
 * ``longer``: ``percent`` longer than the fastest variant. ``day_limit`` / ``leg_limit``
 * (with ``leg``): ``minutes`` too long or ``km`` too far.
 * @export
 * @interface JourneyReasonOut
 */
export interface JourneyReasonOut {
    /**
     * 
     */
    kind: JourneyReasonOutKindEnum;
    /**
     * 
     */
    category?: string | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    leg?: number | null;
    /**
     * 
     */
    minutes?: number | null;
    /**
     * 
     */
    km?: number | null;
    /**
     * 
     */
    percent?: number | null;
}

/**
* @export
* @enum {string}
*/
export enum JourneyReasonOutKindEnum {
    MissingStop = 'missing_stop',
    Gap = 'gap',
    Detour = 'detour',
    Longer = 'longer',
    DayLimit = 'day_limit',
    LegLimit = 'leg_limit'
}


/**
 * Check if a given object implements the JourneyReasonOut interface.
 */
export function instanceOfJourneyReasonOut(value: object): value is JourneyReasonOut {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function JourneyReasonOutFromJSON(json: any): JourneyReasonOut {
    return JourneyReasonOutFromJSONTyped(json, false);
}

export function JourneyReasonOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyReasonOut {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'leg': json['leg'] === undefined ? undefined : json['leg'] === null ? null : json['leg'],
        'minutes': json['minutes'] === undefined ? undefined : json['minutes'] === null ? null : json['minutes'],
        'km': json['km'] === undefined ? undefined : json['km'] === null ? null : json['km'],
        'percent': json['percent'] === undefined ? undefined : json['percent'] === null ? null : json['percent'],
    };
}

export function JourneyReasonOutToJSON(json: any): JourneyReasonOut {
    return JourneyReasonOutToJSONTyped(json, false);
}

export function JourneyReasonOutToJSONTyped(value?: JourneyReasonOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'category': value['category'],
        'name': value['name'],
        'leg': value['leg'],
        'minutes': value['minutes'],
        'km': value['km'],
        'percent': value['percent'],
    };
}

