// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeOut
 */
export interface LikeOut {
    /**
     * 
     */
    liked: boolean;
    /**
     * 
     */
    likeCount: number;
}

/**
 * Check if a given object implements the LikeOut interface.
 */
export function instanceOfLikeOut(value: object): value is LikeOut {
    if (!('liked' in value) || value['liked'] === undefined) return false;
    if ((!('likeCount' in (value as Record<string, any>)) && !('like_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['likeCount'] === undefined && (value as Record<string, any>)['like_count'] === undefined)) return false;
    return true;
}

export function LikeOutFromJSON(json: any): LikeOut {
    return LikeOutFromJSONTyped(json, false);
}

export function LikeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeOut {
    if (json == null) {
        return json;
    }
    return {
        
        'liked': json['liked'],
        'likeCount': json['like_count'],
    };
}

export function LikeOutToJSON(json: any): LikeOut {
    return LikeOutToJSONTyped(json, false);
}

export function LikeOutToJSONTyped(value?: LikeOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'liked': value['liked'],
        'like_count': value['likeCount'],
    };
}

