// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OverrunOut } from './OverrunOut';
import {
    OverrunOutFromJSON,
    OverrunOutFromJSONTyped,
    OverrunOutToJSON,
    OverrunOutToJSONTyped,
} from './OverrunOut';
import type { LegOverrunOut } from './LegOverrunOut';
import {
    LegOverrunOutFromJSON,
    LegOverrunOutFromJSONTyped,
    LegOverrunOutToJSON,
    LegOverrunOutToJSONTyped,
} from './LegOverrunOut';

/**
 * 
 * @export
 * @interface LimitOverrunsOut
 */
export interface LimitOverrunsOut {
    /**
     * 
     */
    day?: OverrunOut | null;
    /**
     * 
     */
    legs?: Array<LegOverrunOut>;
}

/**
 * Check if a given object implements the LimitOverrunsOut interface.
 */
export function instanceOfLimitOverrunsOut(value: object): value is LimitOverrunsOut {
    return true;
}

export function LimitOverrunsOutFromJSON(json: any): LimitOverrunsOut {
    return LimitOverrunsOutFromJSONTyped(json, false);
}

export function LimitOverrunsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): LimitOverrunsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] === undefined ? undefined : json['day'] === null ? null : OverrunOutFromJSON(json['day']),
        'legs': json['legs'] == null ? undefined : ((json['legs'] as Array<any>).map(LegOverrunOutFromJSON)),
    };
}

export function LimitOverrunsOutToJSON(json: any): LimitOverrunsOut {
    return LimitOverrunsOutToJSONTyped(json, false);
}

export function LimitOverrunsOutToJSONTyped(value?: LimitOverrunsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': OverrunOutToJSON(value['day']),
        'legs': value['legs'] == null ? undefined : ((value['legs'] as Array<any>).map(LegOverrunOutToJSON)),
    };
}

