// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverrunOut
 */
export interface OverrunOut {
    /**
     * 
     */
    overS?: number;
    /**
     * 
     */
    overM?: number;
}

/**
 * Check if a given object implements the OverrunOut interface.
 */
export function instanceOfOverrunOut(value: object): value is OverrunOut {
    return true;
}

export function OverrunOutFromJSON(json: any): OverrunOut {
    return OverrunOutFromJSONTyped(json, false);
}

export function OverrunOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverrunOut {
    if (json == null) {
        return json;
    }
    return {
        
        'overS': json['over_s'] == null ? undefined : json['over_s'],
        'overM': json['over_m'] == null ? undefined : json['over_m'],
    };
}

export function OverrunOutToJSON(json: any): OverrunOut {
    return OverrunOutToJSONTyped(json, false);
}

export function OverrunOutToJSONTyped(value?: OverrunOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'over_s': value['overS'],
        'over_m': value['overM'],
    };
}

