// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoUpdateIn
 */
export interface PhotoUpdateIn {
    /**
     * 
     */
    caption?: string;
    /**
     * 
     */
    lat?: number | null;
    /**
     * 
     */
    lon?: number | null;
}

/**
 * Check if a given object implements the PhotoUpdateIn interface.
 */
export function instanceOfPhotoUpdateIn(value: object): value is PhotoUpdateIn {
    return true;
}

export function PhotoUpdateInFromJSON(json: any): PhotoUpdateIn {
    return PhotoUpdateInFromJSONTyped(json, false);
}

export function PhotoUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoUpdateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'] == null ? undefined : json['caption'],
        'lat': json['lat'] === undefined ? undefined : json['lat'] === null ? null : json['lat'],
        'lon': json['lon'] === undefined ? undefined : json['lon'] === null ? null : json['lon'],
    };
}

export function PhotoUpdateInToJSON(json: any): PhotoUpdateIn {
    return PhotoUpdateInToJSONTyped(json, false);
}

export function PhotoUpdateInToJSONTyped(value?: PhotoUpdateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
        'lat': value['lat'],
        'lon': value['lon'],
    };
}

