// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeometrySchema } from './GeometrySchema';
import {
    GeometrySchemaFromJSON,
    GeometrySchemaFromJSONTyped,
    GeometrySchemaToJSON,
    GeometrySchemaToJSONTyped,
} from './GeometrySchema';
import type { PropertiesSchema } from './PropertiesSchema';
import {
    PropertiesSchemaFromJSON,
    PropertiesSchemaFromJSONTyped,
    PropertiesSchemaToJSON,
    PropertiesSchemaToJSONTyped,
} from './PropertiesSchema';

/**
 * 
 * @export
 * @interface PlacesSearchResult
 */
export interface PlacesSearchResult {
    /**
     * 
     */
    geometry: GeometrySchema;
    /**
     * 
     */
    properties: PropertiesSchema;
    /**
     * 
     */
    type?: string;
}

/**
 * Check if a given object implements the PlacesSearchResult interface.
 */
export function instanceOfPlacesSearchResult(value: object): value is PlacesSearchResult {
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function PlacesSearchResultFromJSON(json: any): PlacesSearchResult {
    return PlacesSearchResultFromJSONTyped(json, false);
}

export function PlacesSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlacesSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'geometry': GeometrySchemaFromJSON(json['geometry']),
        'properties': PropertiesSchemaFromJSON(json['properties']),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function PlacesSearchResultToJSON(json: any): PlacesSearchResult {
    return PlacesSearchResultToJSONTyped(json, false);
}

export function PlacesSearchResultToJSONTyped(value?: PlacesSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geometry': GeometrySchemaToJSON(value['geometry']),
        'properties': PropertiesSchemaToJSON(value['properties']),
        'type': value['type'],
    };
}

