// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertiesSchema
 */
export interface PropertiesSchema {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    city?: string | null;
    /**
     * 
     */
    state?: string | null;
    /**
     * 
     */
    countrycode?: string | null;
    /**
     * 
     */
    showCanton: boolean;
}

/**
 * Check if a given object implements the PropertiesSchema interface.
 */
export function instanceOfPropertiesSchema(value: object): value is PropertiesSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('showCanton' in (value as Record<string, any>)) && !('show_canton' in (value as Record<string, any>))) || ((value as Record<string, any>)['showCanton'] === undefined && (value as Record<string, any>)['show_canton'] === undefined)) return false;
    return true;
}

export function PropertiesSchemaFromJSON(json: any): PropertiesSchema {
    return PropertiesSchemaFromJSONTyped(json, false);
}

export function PropertiesSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertiesSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'city': json['city'] === undefined ? undefined : json['city'] === null ? null : json['city'],
        'state': json['state'] === undefined ? undefined : json['state'] === null ? null : json['state'],
        'countrycode': json['countrycode'] === undefined ? undefined : json['countrycode'] === null ? null : json['countrycode'],
        'showCanton': json['show_canton'],
    };
}

export function PropertiesSchemaToJSON(json: any): PropertiesSchema {
    return PropertiesSchemaToJSONTyped(json, false);
}

export function PropertiesSchemaToJSONTyped(value?: PropertiesSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'city': value['city'],
        'state': value['state'],
        'countrycode': value['countrycode'],
        'show_canton': value['showCanton'],
    };
}

