// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RandomPrefsOut
 */
export interface RandomPrefsOut {
    /**
     * 
     */
    roundTrip?: boolean;
    /**
     * Preferred direction, degrees from north
     */
    heading?: number | null;
    /**
     * Plus: forecast and rank the candidates (and route around the weather if chosen). Off: variants to pick from and save as routes, no forecast.
     */
    considerWeather?: boolean;
    /**
     * 
     */
    seed?: number;
}

/**
 * Check if a given object implements the RandomPrefsOut interface.
 */
export function instanceOfRandomPrefsOut(value: object): value is RandomPrefsOut {
    return true;
}

export function RandomPrefsOutFromJSON(json: any): RandomPrefsOut {
    return RandomPrefsOutFromJSONTyped(json, false);
}

export function RandomPrefsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RandomPrefsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'roundTrip': json['round_trip'] == null ? undefined : json['round_trip'],
        'heading': json['heading'] === undefined ? undefined : json['heading'] === null ? null : json['heading'],
        'considerWeather': json['consider_weather'] == null ? undefined : json['consider_weather'],
        'seed': json['seed'] == null ? undefined : json['seed'],
    };
}

export function RandomPrefsOutToJSON(json: any): RandomPrefsOut {
    return RandomPrefsOutToJSONTyped(json, false);
}

export function RandomPrefsOutToJSONTyped(value?: RandomPrefsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round_trip': value['roundTrip'],
        'heading': value['heading'],
        'consider_weather': value['considerWeather'],
        'seed': value['seed'],
    };
}

