// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A random ride's shape. The dice (``seed``) are the server's: a re-plan throws them again.
 * @export
 * @interface RandomPrefsIn
 */
export interface RandomPrefsIn {
    /**
     * 
     */
    roundTrip?: boolean;
    /**
     * Preferred direction, degrees from north
     */
    heading?: number | null;
    /**
     * Plus: forecast and rank the candidates (and route around the weather if chosen). Off: variants to pick from and save as routes, no forecast.
     */
    considerWeather?: boolean;
}

/**
 * Check if a given object implements the RandomPrefsIn interface.
 */
export function instanceOfRandomPrefsIn(value: object): value is RandomPrefsIn {
    return true;
}

export function RandomPrefsInFromJSON(json: any): RandomPrefsIn {
    return RandomPrefsInFromJSONTyped(json, false);
}

export function RandomPrefsInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RandomPrefsIn {
    if (json == null) {
        return json;
    }
    return {
        
        'roundTrip': json['roundTrip'] == null ? undefined : json['roundTrip'],
        'heading': json['heading'] === undefined ? undefined : json['heading'] === null ? null : json['heading'],
        'considerWeather': json['considerWeather'] == null ? undefined : json['considerWeather'],
    };
}

export function RandomPrefsInToJSON(json: any): RandomPrefsIn {
    return RandomPrefsInToJSONTyped(json, false);
}

export function RandomPrefsInToJSONTyped(value?: RandomPrefsIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roundTrip': value['roundTrip'],
        'heading': value['heading'],
        'considerWeather': value['considerWeather'],
    };
}

