// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Receipt
 */
export interface Receipt {
    /**
     * 
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the Receipt interface.
 */
export function instanceOfReceipt(value: object): value is Receipt {
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function ReceiptFromJSON(json: any): Receipt {
    return ReceiptFromJSONTyped(json, false);
}

export function ReceiptFromJSONTyped(json: any, ignoreDiscriminator: boolean): Receipt {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expiresIn'],
    };
}

export function ReceiptToJSON(json: any): Receipt {
    return ReceiptToJSONTyped(json, false);
}

export function ReceiptToJSONTyped(value?: Receipt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiresIn': value['expiresIn'],
    };
}

