// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RouteThumbnail } from './RouteThumbnail';
import {
    RouteThumbnailFromJSON,
    RouteThumbnailFromJSONTyped,
    RouteThumbnailToJSON,
    RouteThumbnailToJSONTyped,
} from './RouteThumbnail';

/**
 * 
 * @export
 * @interface RecurringRouteOut
 */
export interface RecurringRouteOut {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    startLat: number;
    /**
     * 
     */
    startLon: number;
    /**
     * 
     */
    startName: string;
    /**
     * 
     */
    destLat: number;
    /**
     * 
     */
    destLon: number;
    /**
     * 
     */
    destName: string;
    /**
     * 
     */
    profile: string;
    /**
     * 
     */
    scheduleCron: string;
    /**
     * 
     */
    scheduleDescription: string;
    /**
     * 
     */
    active: boolean;
    /**
     * 
     */
    totalSeconds?: number | null;
    /**
     * 
     */
    totalDistanceM?: number | null;
    /**
     * 
     */
    hasGeometry?: boolean;
    /**
     * 
     */
    nextDeparture?: string | null;
    /**
     * 
     */
    forecastAvailable?: boolean;
    /**
     * 
     */
    createdAt?: Date | null;
    /**
     * 
     */
    updatedAt?: Date | null;
    /**
     * 
     */
    thumbnail?: RouteThumbnail | null;
}

/**
 * Check if a given object implements the RecurringRouteOut interface.
 */
export function instanceOfRecurringRouteOut(value: object): value is RecurringRouteOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('startLat' in (value as Record<string, any>)) && !('start_lat' in (value as Record<string, any>))) || ((value as Record<string, any>)['startLat'] === undefined && (value as Record<string, any>)['start_lat'] === undefined)) return false;
    if ((!('startLon' in (value as Record<string, any>)) && !('start_lon' in (value as Record<string, any>))) || ((value as Record<string, any>)['startLon'] === undefined && (value as Record<string, any>)['start_lon'] === undefined)) return false;
    if ((!('startName' in (value as Record<string, any>)) && !('start_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['startName'] === undefined && (value as Record<string, any>)['start_name'] === undefined)) return false;
    if ((!('destLat' in (value as Record<string, any>)) && !('dest_lat' in (value as Record<string, any>))) || ((value as Record<string, any>)['destLat'] === undefined && (value as Record<string, any>)['dest_lat'] === undefined)) return false;
    if ((!('destLon' in (value as Record<string, any>)) && !('dest_lon' in (value as Record<string, any>))) || ((value as Record<string, any>)['destLon'] === undefined && (value as Record<string, any>)['dest_lon'] === undefined)) return false;
    if ((!('destName' in (value as Record<string, any>)) && !('dest_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['destName'] === undefined && (value as Record<string, any>)['dest_name'] === undefined)) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if ((!('scheduleCron' in (value as Record<string, any>)) && !('schedule_cron' in (value as Record<string, any>))) || ((value as Record<string, any>)['scheduleCron'] === undefined && (value as Record<string, any>)['schedule_cron'] === undefined)) return false;
    if ((!('scheduleDescription' in (value as Record<string, any>)) && !('schedule_description' in (value as Record<string, any>))) || ((value as Record<string, any>)['scheduleDescription'] === undefined && (value as Record<string, any>)['schedule_description'] === undefined)) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function RecurringRouteOutFromJSON(json: any): RecurringRouteOut {
    return RecurringRouteOutFromJSONTyped(json, false);
}

export function RecurringRouteOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringRouteOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'startLat': json['start_lat'],
        'startLon': json['start_lon'],
        'startName': json['start_name'],
        'destLat': json['dest_lat'],
        'destLon': json['dest_lon'],
        'destName': json['dest_name'],
        'profile': json['profile'],
        'scheduleCron': json['schedule_cron'],
        'scheduleDescription': json['schedule_description'],
        'active': json['active'],
        'totalSeconds': json['total_seconds'] === undefined ? undefined : json['total_seconds'] === null ? null : json['total_seconds'],
        'totalDistanceM': json['total_distance_m'] === undefined ? undefined : json['total_distance_m'] === null ? null : json['total_distance_m'],
        'hasGeometry': json['has_geometry'] == null ? undefined : json['has_geometry'],
        'nextDeparture': json['next_departure'] === undefined ? undefined : json['next_departure'] === null ? null : json['next_departure'],
        'forecastAvailable': json['forecast_available'] == null ? undefined : json['forecast_available'],
        'createdAt': json['created_at'] === undefined ? undefined : json['created_at'] === null ? null : (parseDateTime(json['created_at'])),
        'updatedAt': json['updated_at'] === undefined ? undefined : json['updated_at'] === null ? null : (parseDateTime(json['updated_at'])),
        'thumbnail': json['thumbnail'] === undefined ? undefined : json['thumbnail'] === null ? null : RouteThumbnailFromJSON(json['thumbnail']),
    };
}

export function RecurringRouteOutToJSON(json: any): RecurringRouteOut {
    return RecurringRouteOutToJSONTyped(json, false);
}

export function RecurringRouteOutToJSONTyped(value?: RecurringRouteOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'start_lat': value['startLat'],
        'start_lon': value['startLon'],
        'start_name': value['startName'],
        'dest_lat': value['destLat'],
        'dest_lon': value['destLon'],
        'dest_name': value['destName'],
        'profile': value['profile'],
        'schedule_cron': value['scheduleCron'],
        'schedule_description': value['scheduleDescription'],
        'active': value['active'],
        'total_seconds': value['totalSeconds'],
        'total_distance_m': value['totalDistanceM'],
        'has_geometry': value['hasGeometry'],
        'next_departure': value['nextDeparture'],
        'forecast_available': value['forecastAvailable'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'thumbnail': RouteThumbnailToJSON(value['thumbnail']),
    };
}

