// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringRouteIn
 */
export interface RecurringRouteIn {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    startLat: number;
    /**
     * 
     */
    startLon: number;
    /**
     * 
     */
    startName: string;
    /**
     * 
     */
    destLat: number;
    /**
     * 
     */
    destLon: number;
    /**
     * 
     */
    destName: string;
    /**
     * 
     */
    profile?: string;
    /**
     * 
     */
    scheduleCron: string;
    /**
     * 
     */
    scheduleDescription: string;
    /**
     * 
     */
    departureFlexBeforeMinutes?: number;
    /**
     * 
     */
    departureFlexAfterMinutes?: number;
    /**
     * 
     */
    active?: boolean;
}

/**
 * Check if a given object implements the RecurringRouteIn interface.
 */
export function instanceOfRecurringRouteIn(value: object): value is RecurringRouteIn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startLat' in value) || value['startLat'] === undefined) return false;
    if (!('startLon' in value) || value['startLon'] === undefined) return false;
    if (!('startName' in value) || value['startName'] === undefined) return false;
    if (!('destLat' in value) || value['destLat'] === undefined) return false;
    if (!('destLon' in value) || value['destLon'] === undefined) return false;
    if (!('destName' in value) || value['destName'] === undefined) return false;
    if (!('scheduleCron' in value) || value['scheduleCron'] === undefined) return false;
    if (!('scheduleDescription' in value) || value['scheduleDescription'] === undefined) return false;
    return true;
}

export function RecurringRouteInFromJSON(json: any): RecurringRouteIn {
    return RecurringRouteInFromJSONTyped(json, false);
}

export function RecurringRouteInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringRouteIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startLat': json['startLat'],
        'startLon': json['startLon'],
        'startName': json['startName'],
        'destLat': json['destLat'],
        'destLon': json['destLon'],
        'destName': json['destName'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'scheduleCron': json['scheduleCron'],
        'scheduleDescription': json['scheduleDescription'],
        'departureFlexBeforeMinutes': json['departureFlexBeforeMinutes'] == null ? undefined : json['departureFlexBeforeMinutes'],
        'departureFlexAfterMinutes': json['departureFlexAfterMinutes'] == null ? undefined : json['departureFlexAfterMinutes'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function RecurringRouteInToJSON(json: any): RecurringRouteIn {
    return RecurringRouteInToJSONTyped(json, false);
}

export function RecurringRouteInToJSONTyped(value?: RecurringRouteIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'startLat': value['startLat'],
        'startLon': value['startLon'],
        'startName': value['startName'],
        'destLat': value['destLat'],
        'destLon': value['destLon'],
        'destName': value['destName'],
        'profile': value['profile'],
        'scheduleCron': value['scheduleCron'],
        'scheduleDescription': value['scheduleDescription'],
        'departureFlexBeforeMinutes': value['departureFlexBeforeMinutes'],
        'departureFlexAfterMinutes': value['departureFlexAfterMinutes'],
        'active': value['active'],
    };
}

