// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Journey road preferences (``core.road_prefs.RoadPrefs``); every one is a penalty.
 * @export
 * @interface RoadPrefsIn
 */
export interface RoadPrefsIn {
    /**
     * 
     */
    surface?: RoadPrefsInSurfaceEnum;
    /**
     * 
     */
    climbing?: RoadPrefsInClimbingEnum;
    /**
     * 
     */
    traffic?: RoadPrefsInTrafficEnum;
    /**
     * 
     */
    towns?: RoadPrefsInTownsEnum;
}

/**
* @export
* @enum {string}
*/
export enum RoadPrefsInSurfaceEnum {
    Any = 'any',
    AvoidUnpaved = 'avoid_unpaved',
    PavedOnly = 'paved_only'
}
/**
* @export
* @enum {string}
*/
export enum RoadPrefsInClimbingEnum {
    Neutral = 'neutral',
    Avoid = 'avoid'
}
/**
* @export
* @enum {string}
*/
export enum RoadPrefsInTrafficEnum {
    Neutral = 'neutral',
    AvoidMain = 'avoid_main',
    AvoidOffNetwork = 'avoid_off_network'
}
/**
* @export
* @enum {string}
*/
export enum RoadPrefsInTownsEnum {
    Neutral = 'neutral',
    Avoid = 'avoid'
}


/**
 * Check if a given object implements the RoadPrefsIn interface.
 */
export function instanceOfRoadPrefsIn(value: object): value is RoadPrefsIn {
    return true;
}

export function RoadPrefsInFromJSON(json: any): RoadPrefsIn {
    return RoadPrefsInFromJSONTyped(json, false);
}

export function RoadPrefsInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoadPrefsIn {
    if (json == null) {
        return json;
    }
    return {
        
        'surface': json['surface'] == null ? undefined : json['surface'],
        'climbing': json['climbing'] == null ? undefined : json['climbing'],
        'traffic': json['traffic'] == null ? undefined : json['traffic'],
        'towns': json['towns'] == null ? undefined : json['towns'],
    };
}

export function RoadPrefsInToJSON(json: any): RoadPrefsIn {
    return RoadPrefsInToJSONTyped(json, false);
}

export function RoadPrefsInToJSONTyped(value?: RoadPrefsIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'surface': value['surface'],
        'climbing': value['climbing'],
        'traffic': value['traffic'],
        'towns': value['towns'],
    };
}

