// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WindDistribution } from './WindDistribution';
import {
    WindDistributionFromJSON,
    WindDistributionFromJSONTyped,
    WindDistributionToJSON,
    WindDistributionToJSONTyped,
} from './WindDistribution';

/**
 * 
 * @export
 * @interface RouteWeatherSummary
 */
export interface RouteWeatherSummary {
    /**
     * 
     */
    willRain: boolean;
    /**
     * 
     */
    firstRainEta?: string | null;
    /**
     * 
     */
    firstRainPlace?: string | null;
    /**
     * 
     */
    maxRainMm: number;
    /**
     * 
     */
    rainProbability?: number | null;
    /**
     * 
     */
    rainAmount: number;
    /**
     * 
     */
    maxHeadwind?: number | null;
    /**
     * 
     */
    maxWindPowerW?: number | null;
    /**
     * 
     */
    windDistribution?: WindDistribution | null;
    /**
     * 
     */
    source: string;
    /**
     * 
     */
    stationCorrected?: boolean;
}

/**
 * Check if a given object implements the RouteWeatherSummary interface.
 */
export function instanceOfRouteWeatherSummary(value: object): value is RouteWeatherSummary {
    if ((!('willRain' in (value as Record<string, any>)) && !('will_rain' in (value as Record<string, any>))) || ((value as Record<string, any>)['willRain'] === undefined && (value as Record<string, any>)['will_rain'] === undefined)) return false;
    if ((!('maxRainMm' in (value as Record<string, any>)) && !('max_rain_mm' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxRainMm'] === undefined && (value as Record<string, any>)['max_rain_mm'] === undefined)) return false;
    if ((!('rainAmount' in (value as Record<string, any>)) && !('rain_amount' in (value as Record<string, any>))) || ((value as Record<string, any>)['rainAmount'] === undefined && (value as Record<string, any>)['rain_amount'] === undefined)) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function RouteWeatherSummaryFromJSON(json: any): RouteWeatherSummary {
    return RouteWeatherSummaryFromJSONTyped(json, false);
}

export function RouteWeatherSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteWeatherSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'willRain': json['will_rain'],
        'firstRainEta': json['first_rain_eta'] === undefined ? undefined : json['first_rain_eta'] === null ? null : json['first_rain_eta'],
        'firstRainPlace': json['first_rain_place'] === undefined ? undefined : json['first_rain_place'] === null ? null : json['first_rain_place'],
        'maxRainMm': json['max_rain_mm'],
        'rainProbability': json['rain_probability'] === undefined ? undefined : json['rain_probability'] === null ? null : json['rain_probability'],
        'rainAmount': json['rain_amount'],
        'maxHeadwind': json['max_headwind'] === undefined ? undefined : json['max_headwind'] === null ? null : json['max_headwind'],
        'maxWindPowerW': json['max_wind_power_w'] === undefined ? undefined : json['max_wind_power_w'] === null ? null : json['max_wind_power_w'],
        'windDistribution': json['wind_distribution'] === undefined ? undefined : json['wind_distribution'] === null ? null : WindDistributionFromJSON(json['wind_distribution']),
        'source': json['source'],
        'stationCorrected': json['station_corrected'] == null ? undefined : json['station_corrected'],
    };
}

export function RouteWeatherSummaryToJSON(json: any): RouteWeatherSummary {
    return RouteWeatherSummaryToJSONTyped(json, false);
}

export function RouteWeatherSummaryToJSONTyped(value?: RouteWeatherSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'will_rain': value['willRain'],
        'first_rain_eta': value['firstRainEta'],
        'first_rain_place': value['firstRainPlace'],
        'max_rain_mm': value['maxRainMm'],
        'rain_probability': value['rainProbability'],
        'rain_amount': value['rainAmount'],
        'max_headwind': value['maxHeadwind'],
        'max_wind_power_w': value['maxWindPowerW'],
        'wind_distribution': WindDistributionToJSON(value['windDistribution']),
        'source': value['source'],
        'station_corrected': value['stationCorrected'],
    };
}

