// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteSection
 */
export interface RouteSection {
    /**
     * 
     */
    startKm: number;
    /**
     * 
     */
    endKm: number;
    /**
     * 
     */
    startTime: string;
    /**
     * 
     */
    endTime: string;
    /**
     * 
     */
    condition: string;
    /**
     * 
     */
    maxRainMm: number;
    /**
     * 
     */
    maxHeadwind: number;
    /**
     * 
     */
    tempMin: number;
    /**
     * 
     */
    tempMax: number;
}

/**
 * Check if a given object implements the RouteSection interface.
 */
export function instanceOfRouteSection(value: object): value is RouteSection {
    if ((!('startKm' in (value as Record<string, any>)) && !('start_km' in (value as Record<string, any>))) || ((value as Record<string, any>)['startKm'] === undefined && (value as Record<string, any>)['start_km'] === undefined)) return false;
    if ((!('endKm' in (value as Record<string, any>)) && !('end_km' in (value as Record<string, any>))) || ((value as Record<string, any>)['endKm'] === undefined && (value as Record<string, any>)['end_km'] === undefined)) return false;
    if ((!('startTime' in (value as Record<string, any>)) && !('start_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['startTime'] === undefined && (value as Record<string, any>)['start_time'] === undefined)) return false;
    if ((!('endTime' in (value as Record<string, any>)) && !('end_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['endTime'] === undefined && (value as Record<string, any>)['end_time'] === undefined)) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if ((!('maxRainMm' in (value as Record<string, any>)) && !('max_rain_mm' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxRainMm'] === undefined && (value as Record<string, any>)['max_rain_mm'] === undefined)) return false;
    if ((!('maxHeadwind' in (value as Record<string, any>)) && !('max_headwind' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxHeadwind'] === undefined && (value as Record<string, any>)['max_headwind'] === undefined)) return false;
    if ((!('tempMin' in (value as Record<string, any>)) && !('temp_min' in (value as Record<string, any>))) || ((value as Record<string, any>)['tempMin'] === undefined && (value as Record<string, any>)['temp_min'] === undefined)) return false;
    if ((!('tempMax' in (value as Record<string, any>)) && !('temp_max' in (value as Record<string, any>))) || ((value as Record<string, any>)['tempMax'] === undefined && (value as Record<string, any>)['temp_max'] === undefined)) return false;
    return true;
}

export function RouteSectionFromJSON(json: any): RouteSection {
    return RouteSectionFromJSONTyped(json, false);
}

export function RouteSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteSection {
    if (json == null) {
        return json;
    }
    return {
        
        'startKm': json['start_km'],
        'endKm': json['end_km'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'condition': json['condition'],
        'maxRainMm': json['max_rain_mm'],
        'maxHeadwind': json['max_headwind'],
        'tempMin': json['temp_min'],
        'tempMax': json['temp_max'],
    };
}

export function RouteSectionToJSON(json: any): RouteSection {
    return RouteSectionToJSONTyped(json, false);
}

export function RouteSectionToJSONTyped(value?: RouteSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_km': value['startKm'],
        'end_km': value['endKm'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'condition': value['condition'],
        'max_rain_mm': value['maxRainMm'],
        'max_headwind': value['maxHeadwind'],
        'temp_min': value['tempMin'],
        'temp_max': value['tempMax'],
    };
}

