// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoutingProfile } from './RoutingProfile';
import {
    RoutingProfileFromJSON,
    RoutingProfileFromJSONTyped,
    RoutingProfileToJSON,
    RoutingProfileToJSONTyped,
} from './RoutingProfile';
import type { GeometrySource } from './GeometrySource';
import {
    GeometrySourceFromJSON,
    GeometrySourceFromJSONTyped,
    GeometrySourceToJSON,
    GeometrySourceToJSONTyped,
} from './GeometrySource';

/**
 * 
 * @export
 * @interface RoutePlanForecastIn
 */
export interface RoutePlanForecastIn {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    geometrySource?: GeometrySource;
    /**
     * 
     */
    coordinates: Array<Array<number>>;
    /**
     * 
     */
    durationSeconds?: number | null;
    /**
     * 
     */
    profile?: RoutingProfile;
    /**
     * 
     */
    departureTime: string;
    /**
     * 
     */
    intervalSeconds?: number;
    /**
     * 
     */
    departureFlexBeforeMinutes?: number;
    /**
     * 
     */
    departureFlexAfterMinutes?: number;
}



/**
 * Check if a given object implements the RoutePlanForecastIn interface.
 */
export function instanceOfRoutePlanForecastIn(value: object): value is RoutePlanForecastIn {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if (!('departureTime' in value) || value['departureTime'] === undefined) return false;
    return true;
}

export function RoutePlanForecastInFromJSON(json: any): RoutePlanForecastIn {
    return RoutePlanForecastInFromJSONTyped(json, false);
}

export function RoutePlanForecastInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePlanForecastIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'geometrySource': json['geometrySource'] == null ? undefined : GeometrySourceFromJSON(json['geometrySource']),
        'coordinates': json['coordinates'],
        'durationSeconds': json['durationSeconds'] === undefined ? undefined : json['durationSeconds'] === null ? null : json['durationSeconds'],
        'profile': json['profile'] == null ? undefined : RoutingProfileFromJSON(json['profile']),
        'departureTime': json['departureTime'],
        'intervalSeconds': json['intervalSeconds'] == null ? undefined : json['intervalSeconds'],
        'departureFlexBeforeMinutes': json['departureFlexBeforeMinutes'] == null ? undefined : json['departureFlexBeforeMinutes'],
        'departureFlexAfterMinutes': json['departureFlexAfterMinutes'] == null ? undefined : json['departureFlexAfterMinutes'],
    };
}

export function RoutePlanForecastInToJSON(json: any): RoutePlanForecastIn {
    return RoutePlanForecastInToJSONTyped(json, false);
}

export function RoutePlanForecastInToJSONTyped(value?: RoutePlanForecastIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'geometrySource': GeometrySourceToJSON(value['geometrySource']),
        'coordinates': value['coordinates'],
        'durationSeconds': value['durationSeconds'],
        'profile': RoutingProfileToJSON(value['profile']),
        'departureTime': value['departureTime'],
        'intervalSeconds': value['intervalSeconds'],
        'departureFlexBeforeMinutes': value['departureFlexBeforeMinutes'],
        'departureFlexAfterMinutes': value['departureFlexAfterMinutes'],
    };
}

