// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteWeatherSummary } from './RouteWeatherSummary';
import {
    RouteWeatherSummaryFromJSON,
    RouteWeatherSummaryFromJSONTyped,
    RouteWeatherSummaryToJSON,
    RouteWeatherSummaryToJSONTyped,
} from './RouteWeatherSummary';
import type { WeatherSample } from './WeatherSample';
import {
    WeatherSampleFromJSON,
    WeatherSampleFromJSONTyped,
    WeatherSampleToJSON,
    WeatherSampleToJSONTyped,
} from './WeatherSample';
import type { RouteSection } from './RouteSection';
import {
    RouteSectionFromJSON,
    RouteSectionFromJSONTyped,
    RouteSectionToJSON,
    RouteSectionToJSONTyped,
} from './RouteSection';

/**
 * 
 * @export
 * @interface RouteForecastOut
 */
export interface RouteForecastOut {
    /**
     * 
     */
    line: Array<Array<number>>;
    /**
     * 
     */
    totalSeconds: number;
    /**
     * 
     */
    totalDistanceM: number;
    /**
     * 
     */
    samples: Array<WeatherSample>;
    /**
     * 
     */
    summary: RouteWeatherSummary;
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    departureTime: string;
    /**
     * 
     */
    figures?: Array<{ [key: string]: any; }>;
    /**
     * 
     */
    sections?: Array<RouteSection>;
}

/**
 * Check if a given object implements the RouteForecastOut interface.
 */
export function instanceOfRouteForecastOut(value: object): value is RouteForecastOut {
    if (!('line' in value) || value['line'] === undefined) return false;
    if ((!('totalSeconds' in (value as Record<string, any>)) && !('total_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalSeconds'] === undefined && (value as Record<string, any>)['total_seconds'] === undefined)) return false;
    if ((!('totalDistanceM' in (value as Record<string, any>)) && !('total_distance_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalDistanceM'] === undefined && (value as Record<string, any>)['total_distance_m'] === undefined)) return false;
    if (!('samples' in value) || value['samples'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if ((!('routeId' in (value as Record<string, any>)) && !('route_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['routeId'] === undefined && (value as Record<string, any>)['route_id'] === undefined)) return false;
    if ((!('departureTime' in (value as Record<string, any>)) && !('departure_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['departureTime'] === undefined && (value as Record<string, any>)['departure_time'] === undefined)) return false;
    return true;
}

export function RouteForecastOutFromJSON(json: any): RouteForecastOut {
    return RouteForecastOutFromJSONTyped(json, false);
}

export function RouteForecastOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteForecastOut {
    if (json == null) {
        return json;
    }
    return {
        
        'line': json['line'],
        'totalSeconds': json['total_seconds'],
        'totalDistanceM': json['total_distance_m'],
        'samples': ((json['samples'] as Array<any>).map(WeatherSampleFromJSON)),
        'summary': RouteWeatherSummaryFromJSON(json['summary']),
        'routeId': json['route_id'],
        'departureTime': json['departure_time'],
        'figures': json['figures'] == null ? undefined : json['figures'],
        'sections': json['sections'] == null ? undefined : ((json['sections'] as Array<any>).map(RouteSectionFromJSON)),
    };
}

export function RouteForecastOutToJSON(json: any): RouteForecastOut {
    return RouteForecastOutToJSONTyped(json, false);
}

export function RouteForecastOutToJSONTyped(value?: RouteForecastOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line': value['line'],
        'total_seconds': value['totalSeconds'],
        'total_distance_m': value['totalDistanceM'],
        'samples': ((value['samples'] as Array<any>).map(WeatherSampleToJSON)),
        'summary': RouteWeatherSummaryToJSON(value['summary']),
        'route_id': value['routeId'],
        'departure_time': value['departureTime'],
        'figures': value['figures'],
        'sections': value['sections'] == null ? undefined : ((value['sections'] as Array<any>).map(RouteSectionToJSON)),
    };
}

