// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteWeatherSummary } from './RouteWeatherSummary';
import {
    RouteWeatherSummaryFromJSON,
    RouteWeatherSummaryFromJSONTyped,
    RouteWeatherSummaryToJSON,
    RouteWeatherSummaryToJSONTyped,
} from './RouteWeatherSummary';
import type { WeatherSample } from './WeatherSample';
import {
    WeatherSampleFromJSON,
    WeatherSampleFromJSONTyped,
    WeatherSampleToJSON,
    WeatherSampleToJSONTyped,
} from './WeatherSample';

/**
 * 
 * @export
 * @interface RouteWeatherOut
 */
export interface RouteWeatherOut {
    /**
     * 
     */
    line: Array<Array<number>>;
    /**
     * 
     */
    totalSeconds: number;
    /**
     * 
     */
    totalDistanceM: number;
    /**
     * 
     */
    samples: Array<WeatherSample>;
    /**
     * 
     */
    summary: RouteWeatherSummary;
}

/**
 * Check if a given object implements the RouteWeatherOut interface.
 */
export function instanceOfRouteWeatherOut(value: object): value is RouteWeatherOut {
    if (!('line' in value) || value['line'] === undefined) return false;
    if ((!('totalSeconds' in (value as Record<string, any>)) && !('total_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalSeconds'] === undefined && (value as Record<string, any>)['total_seconds'] === undefined)) return false;
    if ((!('totalDistanceM' in (value as Record<string, any>)) && !('total_distance_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalDistanceM'] === undefined && (value as Record<string, any>)['total_distance_m'] === undefined)) return false;
    if (!('samples' in value) || value['samples'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function RouteWeatherOutFromJSON(json: any): RouteWeatherOut {
    return RouteWeatherOutFromJSONTyped(json, false);
}

export function RouteWeatherOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteWeatherOut {
    if (json == null) {
        return json;
    }
    return {
        
        'line': json['line'],
        'totalSeconds': json['total_seconds'],
        'totalDistanceM': json['total_distance_m'],
        'samples': ((json['samples'] as Array<any>).map(WeatherSampleFromJSON)),
        'summary': RouteWeatherSummaryFromJSON(json['summary']),
    };
}

export function RouteWeatherOutToJSON(json: any): RouteWeatherOut {
    return RouteWeatherOutToJSONTyped(json, false);
}

export function RouteWeatherOutToJSONTyped(value?: RouteWeatherOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line': value['line'],
        'total_seconds': value['totalSeconds'],
        'total_distance_m': value['totalDistanceM'],
        'samples': ((value['samples'] as Array<any>).map(WeatherSampleToJSON)),
        'summary': RouteWeatherSummaryToJSON(value['summary']),
    };
}

