// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The route-list glyph: the simplified path and the ride quality of its worst sample.
 * 
 * The stored blob keeps the raw sample weather; only the verdict leaves the server, scored
 * when the list is served (see ``core.ride_quality``).
 * @export
 * @interface RouteThumbnail
 */
export interface RouteThumbnail {
    /**
     * 
     */
    computedAt?: string | null;
    /**
     * 
     */
    departure?: string | null;
    /**
     * 
     */
    path?: Array<Array<number>>;
    /**
     * 
     */
    rideLabel?: string | null;
    /**
     * 
     */
    rideScore?: number | null;
}

/**
 * Check if a given object implements the RouteThumbnail interface.
 */
export function instanceOfRouteThumbnail(value: object): value is RouteThumbnail {
    return true;
}

export function RouteThumbnailFromJSON(json: any): RouteThumbnail {
    return RouteThumbnailFromJSONTyped(json, false);
}

export function RouteThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteThumbnail {
    if (json == null) {
        return json;
    }
    return {
        
        'computedAt': json['computed_at'] === undefined ? undefined : json['computed_at'] === null ? null : json['computed_at'],
        'departure': json['departure'] === undefined ? undefined : json['departure'] === null ? null : json['departure'],
        'path': json['path'] == null ? undefined : json['path'],
        'rideLabel': json['ride_label'] === undefined ? undefined : json['ride_label'] === null ? null : json['ride_label'],
        'rideScore': json['ride_score'] === undefined ? undefined : json['ride_score'] === null ? null : json['ride_score'],
    };
}

export function RouteThumbnailToJSON(json: any): RouteThumbnail {
    return RouteThumbnailToJSONTyped(json, false);
}

export function RouteThumbnailToJSONTyped(value?: RouteThumbnail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computed_at': value['computedAt'],
        'departure': value['departure'],
        'path': value['path'],
        'ride_label': value['rideLabel'],
        'ride_score': value['rideScore'],
    };
}

