// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The route-list glyph: the simplified path, the ride quality of its worst sample, and
 * the rain and frost the row shows beside it.
 * 
 * The stored blob keeps the raw sample weather; only verdicts and two aggregates leave the
 * server, scored when the list is served (see ``core.ride_quality``). The rain and frost
 * levels are the *worst point of the ride*, not the worst-scoring sample: "will it rain on
 * my ride" is a different question from "what spoils it".
 * @export
 * @interface RouteThumbnail
 */
export interface RouteThumbnail {
    /**
     * 
     */
    departure?: string | null;
    /**
     * 
     */
    path?: Array<Array<number>>;
    /**
     * 
     */
    computedAt?: string | null;
    /**
     * 
     */
    rideScore?: number | null;
    /**
     * 
     */
    rideLabel?: string | null;
    /**
     * 
     */
    rainLevel?: string | null;
    /**
     * 
     */
    frostLevel?: string | null;
    /**
     * 
     */
    rainProbability?: number | null;
    /**
     * 
     */
    maxRainRateMmH?: number | null;
    /**
     * 
     */
    tempMin?: number | null;
}

/**
 * Check if a given object implements the RouteThumbnail interface.
 */
export function instanceOfRouteThumbnail(value: object): value is RouteThumbnail {
    return true;
}

export function RouteThumbnailFromJSON(json: any): RouteThumbnail {
    return RouteThumbnailFromJSONTyped(json, false);
}

export function RouteThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteThumbnail {
    if (json == null) {
        return json;
    }
    return {
        
        'departure': json['departure'] === undefined ? undefined : json['departure'] === null ? null : json['departure'],
        'path': json['path'] == null ? undefined : json['path'],
        'computedAt': json['computed_at'] === undefined ? undefined : json['computed_at'] === null ? null : json['computed_at'],
        'rideScore': json['ride_score'] === undefined ? undefined : json['ride_score'] === null ? null : json['ride_score'],
        'rideLabel': json['ride_label'] === undefined ? undefined : json['ride_label'] === null ? null : json['ride_label'],
        'rainLevel': json['rain_level'] === undefined ? undefined : json['rain_level'] === null ? null : json['rain_level'],
        'frostLevel': json['frost_level'] === undefined ? undefined : json['frost_level'] === null ? null : json['frost_level'],
        'rainProbability': json['rain_probability'] === undefined ? undefined : json['rain_probability'] === null ? null : json['rain_probability'],
        'maxRainRateMmH': json['max_rain_rate_mm_h'] === undefined ? undefined : json['max_rain_rate_mm_h'] === null ? null : json['max_rain_rate_mm_h'],
        'tempMin': json['temp_min'] === undefined ? undefined : json['temp_min'] === null ? null : json['temp_min'],
    };
}

export function RouteThumbnailToJSON(json: any): RouteThumbnail {
    return RouteThumbnailToJSONTyped(json, false);
}

export function RouteThumbnailToJSONTyped(value?: RouteThumbnail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departure': value['departure'],
        'path': value['path'],
        'computed_at': value['computedAt'],
        'ride_score': value['rideScore'],
        'ride_label': value['rideLabel'],
        'rain_level': value['rainLevel'],
        'frost_level': value['frostLevel'],
        'rain_probability': value['rainProbability'],
        'max_rain_rate_mm_h': value['maxRainRateMmH'],
        'temp_min': value['tempMin'],
    };
}

