// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForecastSampleOut } from './ForecastSampleOut';
import {
    ForecastSampleOutFromJSON,
    ForecastSampleOutFromJSONTyped,
    ForecastSampleOutToJSON,
    ForecastSampleOutToJSONTyped,
} from './ForecastSampleOut';
import type { RouteWeatherSummary } from './RouteWeatherSummary';
import {
    RouteWeatherSummaryFromJSON,
    RouteWeatherSummaryFromJSONTyped,
    RouteWeatherSummaryToJSON,
    RouteWeatherSummaryToJSONTyped,
} from './RouteWeatherSummary';
import type { WindArrow } from './WindArrow';
import {
    WindArrowFromJSON,
    WindArrowFromJSONTyped,
    WindArrowToJSON,
    WindArrowToJSONTyped,
} from './WindArrow';
import type { RouteSection } from './RouteSection';
import {
    RouteSectionFromJSON,
    RouteSectionFromJSONTyped,
    RouteSectionToJSON,
    RouteSectionToJSONTyped,
} from './RouteSection';

/**
 * A finished forecast as the job endpoint and the WebSocket serve it.
 * 
 * Slimmer than what the job stores (see ``core.jobs.forecast_view``): ``line`` is the
 * coarse route line, ``wind_arrows`` are about 2 km apart and the samples carry no
 * per-model breakdown. The chart figures, finer map detail and one sample's breakdown
 * each come from their own endpoint, keyed by ``job_id``; ``version`` changes whenever
 * the job is recomputed under the same id.
 * @export
 * @interface RouteForecastOut
 */
export interface RouteForecastOut {
    /**
     * 
     */
    departureTime: string;
    /**
     * 
     */
    jobId: string;
    /**
     * 
     */
    line: Array<Array<number>>;
    /**
     * 
     */
    routeId?: string | null;
    /**
     * 
     */
    samples: Array<ForecastSampleOut>;
    /**
     * 
     */
    sections?: Array<RouteSection>;
    /**
     * 
     */
    summary: RouteWeatherSummary;
    /**
     * 
     */
    totalDistanceM: number;
    /**
     * 
     */
    totalSeconds: number;
    /**
     * 
     */
    uncertaintyPartial?: boolean;
    /**
     * 
     */
    version: string;
    /**
     * 
     */
    windArrows?: Array<WindArrow>;
}

/**
 * Check if a given object implements the RouteForecastOut interface.
 */
export function instanceOfRouteForecastOut(value: object): value is RouteForecastOut {
    if ((!('departureTime' in (value as Record<string, any>)) && !('departure_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['departureTime'] === undefined && (value as Record<string, any>)['departure_time'] === undefined)) return false;
    if ((!('jobId' in (value as Record<string, any>)) && !('job_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['jobId'] === undefined && (value as Record<string, any>)['job_id'] === undefined)) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('samples' in value) || value['samples'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if ((!('totalDistanceM' in (value as Record<string, any>)) && !('total_distance_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalDistanceM'] === undefined && (value as Record<string, any>)['total_distance_m'] === undefined)) return false;
    if ((!('totalSeconds' in (value as Record<string, any>)) && !('total_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalSeconds'] === undefined && (value as Record<string, any>)['total_seconds'] === undefined)) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RouteForecastOutFromJSON(json: any): RouteForecastOut {
    return RouteForecastOutFromJSONTyped(json, false);
}

export function RouteForecastOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteForecastOut {
    if (json == null) {
        return json;
    }
    return {
        
        'departureTime': json['departure_time'],
        'jobId': json['job_id'],
        'line': json['line'],
        'routeId': json['route_id'] === undefined ? undefined : json['route_id'] === null ? null : json['route_id'],
        'samples': ((json['samples'] as Array<any>).map(ForecastSampleOutFromJSON)),
        'sections': json['sections'] == null ? undefined : ((json['sections'] as Array<any>).map(RouteSectionFromJSON)),
        'summary': RouteWeatherSummaryFromJSON(json['summary']),
        'totalDistanceM': json['total_distance_m'],
        'totalSeconds': json['total_seconds'],
        'uncertaintyPartial': json['uncertainty_partial'] == null ? undefined : json['uncertainty_partial'],
        'version': json['version'],
        'windArrows': json['wind_arrows'] == null ? undefined : ((json['wind_arrows'] as Array<any>).map(WindArrowFromJSON)),
    };
}

export function RouteForecastOutToJSON(json: any): RouteForecastOut {
    return RouteForecastOutToJSONTyped(json, false);
}

export function RouteForecastOutToJSONTyped(value?: RouteForecastOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departure_time': value['departureTime'],
        'job_id': value['jobId'],
        'line': value['line'],
        'route_id': value['routeId'],
        'samples': ((value['samples'] as Array<any>).map(ForecastSampleOutToJSON)),
        'sections': value['sections'] == null ? undefined : ((value['sections'] as Array<any>).map(RouteSectionToJSON)),
        'summary': RouteWeatherSummaryToJSON(value['summary']),
        'total_distance_m': value['totalDistanceM'],
        'total_seconds': value['totalSeconds'],
        'uncertainty_partial': value['uncertaintyPartial'],
        'version': value['version'],
        'wind_arrows': value['windArrows'] == null ? undefined : ((value['windArrows'] as Array<any>).map(WindArrowToJSON)),
    };
}

