// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoutingProfile } from './RoutingProfile';
import {
    RoutingProfileFromJSON,
    RoutingProfileFromJSONTyped,
    RoutingProfileToJSON,
    RoutingProfileToJSONTyped,
} from './RoutingProfile';
import type { GeometrySource } from './GeometrySource';
import {
    GeometrySourceFromJSON,
    GeometrySourceFromJSONTyped,
    GeometrySourceToJSON,
    GeometrySourceToJSONTyped,
} from './GeometrySource';

/**
 * 
 * @export
 * @interface RoutePlanIn
 */
export interface RoutePlanIn {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    geometrySource?: GeometrySource;
    /**
     * 
     */
    coordinates: Array<Array<number>>;
    /**
     * 
     */
    durationSeconds?: number | null;
    /**
     * 
     */
    profile?: RoutingProfile;
}



/**
 * Check if a given object implements the RoutePlanIn interface.
 */
export function instanceOfRoutePlanIn(value: object): value is RoutePlanIn {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function RoutePlanInFromJSON(json: any): RoutePlanIn {
    return RoutePlanInFromJSONTyped(json, false);
}

export function RoutePlanInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePlanIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'geometrySource': json['geometrySource'] == null ? undefined : GeometrySourceFromJSON(json['geometrySource']),
        'coordinates': json['coordinates'],
        'durationSeconds': json['durationSeconds'] === undefined ? undefined : json['durationSeconds'] === null ? null : json['durationSeconds'],
        'profile': json['profile'] == null ? undefined : RoutingProfileFromJSON(json['profile']),
    };
}

export function RoutePlanInToJSON(json: any): RoutePlanIn {
    return RoutePlanInToJSONTyped(json, false);
}

export function RoutePlanInToJSONTyped(value?: RoutePlanIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'geometrySource': GeometrySourceToJSON(value['geometrySource']),
        'coordinates': value['coordinates'],
        'durationSeconds': value['durationSeconds'],
        'profile': RoutingProfileToJSON(value['profile']),
    };
}

