// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveVariantIn
 */
export interface SaveVariantIn {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    scheduleCron: string;
    /**
     * 
     */
    scheduleDescription: string;
}

/**
 * Check if a given object implements the SaveVariantIn interface.
 */
export function instanceOfSaveVariantIn(value: object): value is SaveVariantIn {
    if (!('scheduleCron' in value) || value['scheduleCron'] === undefined) return false;
    if (!('scheduleDescription' in value) || value['scheduleDescription'] === undefined) return false;
    return true;
}

export function SaveVariantInFromJSON(json: any): SaveVariantIn {
    return SaveVariantInFromJSONTyped(json, false);
}

export function SaveVariantInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveVariantIn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'scheduleCron': json['scheduleCron'],
        'scheduleDescription': json['scheduleDescription'],
    };
}

export function SaveVariantInToJSON(json: any): SaveVariantIn {
    return SaveVariantInToJSONTyped(json, false);
}

export function SaveVariantInToJSONTyped(value?: SaveVariantIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'scheduleCron': value['scheduleCron'],
        'scheduleDescription': value['scheduleDescription'],
    };
}

