// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SharingOut
 */
export interface SharingOut {
    /**
     * 
     */
    visibility: SharingOutVisibilityEnum;
    /**
     * 
     */
    publicSlug?: string | null;
    /**
     * 
     */
    publishedAt?: Date | null;
    /**
     * 
     */
    privacyZoneM: number;
    /**
     * 
     */
    publicDistanceM?: number | null;
    /**
     * 
     */
    publicLine?: Array<Array<number>> | null;
}

/**
* @export
* @enum {string}
*/
export enum SharingOutVisibilityEnum {
    Private = 'private',
    Public = 'public'
}


/**
 * Check if a given object implements the SharingOut interface.
 */
export function instanceOfSharingOut(value: object): value is SharingOut {
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if ((!('privacyZoneM' in (value as Record<string, any>)) && !('privacy_zone_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['privacyZoneM'] === undefined && (value as Record<string, any>)['privacy_zone_m'] === undefined)) return false;
    return true;
}

export function SharingOutFromJSON(json: any): SharingOut {
    return SharingOutFromJSONTyped(json, false);
}

export function SharingOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharingOut {
    if (json == null) {
        return json;
    }
    return {
        
        'visibility': json['visibility'],
        'publicSlug': json['public_slug'] === undefined ? undefined : json['public_slug'] === null ? null : json['public_slug'],
        'publishedAt': json['published_at'] === undefined ? undefined : json['published_at'] === null ? null : (parseDateTime(json['published_at'])),
        'privacyZoneM': json['privacy_zone_m'],
        'publicDistanceM': json['public_distance_m'] === undefined ? undefined : json['public_distance_m'] === null ? null : json['public_distance_m'],
        'publicLine': json['public_line'] === undefined ? undefined : json['public_line'] === null ? null : json['public_line'],
    };
}

export function SharingOutToJSON(json: any): SharingOut {
    return SharingOutToJSONTyped(json, false);
}

export function SharingOutToJSONTyped(value?: SharingOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'visibility': value['visibility'],
        'public_slug': value['publicSlug'],
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : serializeDateTime(value['publishedAt']),
        'privacy_zone_m': value['privacyZoneM'],
        'public_distance_m': value['publicDistanceM'],
        'public_line': value['publicLine'],
    };
}

