// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharingIn
 */
export interface SharingIn {
    /**
     * 
     */
    visibility: SharingInVisibilityEnum;
    /**
     * 
     */
    privacyZoneM?: number;
}

/**
* @export
* @enum {string}
*/
export enum SharingInVisibilityEnum {
    Private = 'private',
    Public = 'public'
}


/**
 * Check if a given object implements the SharingIn interface.
 */
export function instanceOfSharingIn(value: object): value is SharingIn {
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function SharingInFromJSON(json: any): SharingIn {
    return SharingInFromJSONTyped(json, false);
}

export function SharingInFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharingIn {
    if (json == null) {
        return json;
    }
    return {
        
        'visibility': json['visibility'],
        'privacyZoneM': json['privacyZoneM'] == null ? undefined : json['privacyZoneM'],
    };
}

export function SharingInToJSON(json: any): SharingIn {
    return SharingInToJSONTyped(json, false);
}

export function SharingInToJSONTyped(value?: SharingIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'visibility': value['visibility'],
        'privacyZoneM': value['privacyZoneM'],
    };
}

