// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     */
    challenge: string;
    /**
     * 
     */
    payload: string;
    /**
     * 
     */
    publicKey: string;
    /**
     * 
     */
    signature: string;
    /**
     * 
     */
    pow: string;
}

/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): value is Submission {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('pow' in value) || value['pow'] === undefined) return false;
    return true;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'payload': json['payload'],
        'publicKey': json['publicKey'],
        'signature': json['signature'],
        'pow': json['pow'],
    };
}

export function SubmissionToJSON(json: any): Submission {
    return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(value?: Submission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'payload': value['payload'],
        'publicKey': value['publicKey'],
        'signature': value['signature'],
        'pow': value['pow'],
    };
}

