// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribeOut
 */
export interface SubscribeOut {
    /**
     * 
     */
    status: SubscribeOutStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum SubscribeOutStatusEnum {
    Pending = 'pending',
    Confirmed = 'confirmed'
}


/**
 * Check if a given object implements the SubscribeOut interface.
 */
export function instanceOfSubscribeOut(value: object): value is SubscribeOut {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SubscribeOutFromJSON(json: any): SubscribeOut {
    return SubscribeOutFromJSONTyped(json, false);
}

export function SubscribeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeOut {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function SubscribeOutToJSON(json: any): SubscribeOut {
    return SubscribeOutToJSONTyped(json, false);
}

export function SubscribeOutToJSONTyped(value?: SubscribeOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

