// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { SystemCacheCount } from './SystemCacheCount';
import {
    SystemCacheCountFromJSON,
    SystemCacheCountFromJSONTyped,
    SystemCacheCountToJSON,
    SystemCacheCountToJSONTyped,
} from './SystemCacheCount';

/**
 * 
 * @export
 * @interface SystemSummary
 */
export interface SystemSummary {
    /**
     * 
     */
    generatedAt: Date;
    /**
     * 
     */
    maxCellAgeSeconds: number;
    /**
     * 
     */
    recurringRoutes: number;
    /**
     * 
     */
    journeys: number;
    /**
     * 
     */
    stages: number;
    /**
     * 
     */
    missingGeometry: number;
    /**
     * 
     */
    cacheLocations: number;
    /**
     * 
     */
    caches: Array<SystemCacheCount>;
    /**
     * 
     */
    bounds: Array<number> | null;
}

/**
 * Check if a given object implements the SystemSummary interface.
 */
export function instanceOfSystemSummary(value: object): value is SystemSummary {
    if ((!('generatedAt' in (value as Record<string, any>)) && !('generated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['generatedAt'] === undefined && (value as Record<string, any>)['generated_at'] === undefined)) return false;
    if ((!('maxCellAgeSeconds' in (value as Record<string, any>)) && !('max_cell_age_seconds' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxCellAgeSeconds'] === undefined && (value as Record<string, any>)['max_cell_age_seconds'] === undefined)) return false;
    if ((!('recurringRoutes' in (value as Record<string, any>)) && !('recurring_routes' in (value as Record<string, any>))) || ((value as Record<string, any>)['recurringRoutes'] === undefined && (value as Record<string, any>)['recurring_routes'] === undefined)) return false;
    if (!('journeys' in value) || value['journeys'] === undefined) return false;
    if (!('stages' in value) || value['stages'] === undefined) return false;
    if ((!('missingGeometry' in (value as Record<string, any>)) && !('missing_geometry' in (value as Record<string, any>))) || ((value as Record<string, any>)['missingGeometry'] === undefined && (value as Record<string, any>)['missing_geometry'] === undefined)) return false;
    if ((!('cacheLocations' in (value as Record<string, any>)) && !('cache_locations' in (value as Record<string, any>))) || ((value as Record<string, any>)['cacheLocations'] === undefined && (value as Record<string, any>)['cache_locations'] === undefined)) return false;
    if (!('caches' in value) || value['caches'] === undefined) return false;
    if (!('bounds' in value) || value['bounds'] === undefined) return false;
    return true;
}

export function SystemSummaryFromJSON(json: any): SystemSummary {
    return SystemSummaryFromJSONTyped(json, false);
}

export function SystemSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': (json['generated_at'] == null ? json['generated_at'] : parseDateTime(json['generated_at'])),
        'maxCellAgeSeconds': json['max_cell_age_seconds'],
        'recurringRoutes': json['recurring_routes'],
        'journeys': json['journeys'],
        'stages': json['stages'],
        'missingGeometry': json['missing_geometry'],
        'cacheLocations': json['cache_locations'],
        'caches': ((json['caches'] as Array<any>).map(SystemCacheCountFromJSON)),
        'bounds': json['bounds'] == null ? null : json['bounds'],
    };
}

export function SystemSummaryToJSON(json: any): SystemSummary {
    return SystemSummaryToJSONTyped(json, false);
}

export function SystemSummaryToJSONTyped(value?: SystemSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : serializeDateTime(value['generatedAt']),
        'max_cell_age_seconds': value['maxCellAgeSeconds'],
        'recurring_routes': value['recurringRoutes'],
        'journeys': value['journeys'],
        'stages': value['stages'],
        'missing_geometry': value['missingGeometry'],
        'cache_locations': value['cacheLocations'],
        'caches': ((value['caches'] as Array<any>).map(SystemCacheCountToJSON)),
        'bounds': value['bounds'],
    };
}

