// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemBrowserStatsDay } from './SystemBrowserStatsDay';
import {
    SystemBrowserStatsDayFromJSON,
    SystemBrowserStatsDayFromJSONTyped,
    SystemBrowserStatsDayToJSON,
    SystemBrowserStatsDayToJSONTyped,
} from './SystemBrowserStatsDay';

/**
 * 
 * @export
 * @interface SystemBrowserStats
 */
export interface SystemBrowserStats {
    /**
     * 
     */
    observed: Array<string>;
    /**
     * 
     */
    days: Array<SystemBrowserStatsDay>;
}

/**
 * Check if a given object implements the SystemBrowserStats interface.
 */
export function instanceOfSystemBrowserStats(value: object): value is SystemBrowserStats {
    if (!('observed' in value) || value['observed'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    return true;
}

export function SystemBrowserStatsFromJSON(json: any): SystemBrowserStats {
    return SystemBrowserStatsFromJSONTyped(json, false);
}

export function SystemBrowserStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemBrowserStats {
    if (json == null) {
        return json;
    }
    return {
        
        'observed': json['observed'],
        'days': ((json['days'] as Array<any>).map(SystemBrowserStatsDayFromJSON)),
    };
}

export function SystemBrowserStatsToJSON(json: any): SystemBrowserStats {
    return SystemBrowserStatsToJSONTyped(json, false);
}

export function SystemBrowserStatsToJSONTyped(value?: SystemBrowserStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'observed': value['observed'],
        'days': ((value['days'] as Array<any>).map(SystemBrowserStatsDayToJSON)),
    };
}

