// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemTerrainCheck
 */
export interface SystemTerrainCheck {
    /**
     * 
     */
    zoom: number | null;
    /**
     * 
     */
    positions: number;
    /**
     * 
     */
    decoded: boolean;
    /**
     * 
     */
    missing?: number | null;
    /**
     * 
     */
    nodata?: number | null;
}

/**
 * Check if a given object implements the SystemTerrainCheck interface.
 */
export function instanceOfSystemTerrainCheck(value: object): value is SystemTerrainCheck {
    if (!('zoom' in value) || value['zoom'] === undefined) return false;
    if (!('positions' in value) || value['positions'] === undefined) return false;
    if (!('decoded' in value) || value['decoded'] === undefined) return false;
    return true;
}

export function SystemTerrainCheckFromJSON(json: any): SystemTerrainCheck {
    return SystemTerrainCheckFromJSONTyped(json, false);
}

export function SystemTerrainCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemTerrainCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'zoom': json['zoom'],
        'positions': json['positions'],
        'decoded': json['decoded'],
        'missing': json['missing'] === undefined ? undefined : json['missing'] === null ? null : json['missing'],
        'nodata': json['nodata'] === undefined ? undefined : json['nodata'] === null ? null : json['nodata'],
    };
}

export function SystemTerrainCheckToJSON(json: any): SystemTerrainCheck {
    return SystemTerrainCheckToJSONTyped(json, false);
}

export function SystemTerrainCheckToJSONTyped(value?: SystemTerrainCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'zoom': value['zoom'],
        'positions': value['positions'],
        'decoded': value['decoded'],
        'missing': value['missing'],
        'nodata': value['nodata'],
    };
}

