// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemFeature
 */
export interface SystemFeature {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    kind: string;
    /**
     * 
     */
    coordinates: Array<Array<number>>;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    profile?: string;
    /**
     * 
     */
    active?: boolean | null;
    /**
     * 
     */
    rank?: number | null;
    /**
     * 
     */
    source?: string;
    /**
     * 
     */
    fetchedAt?: Date | null;
    /**
     * 
     */
    dayKey?: Date | null;
    /**
     * 
     */
    forecastDays?: number | null;
    /**
     * 
     */
    lat?: number | null;
    /**
     * 
     */
    lon?: number | null;
}

/**
 * Check if a given object implements the SystemFeature interface.
 */
export function instanceOfSystemFeature(value: object): value is SystemFeature {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function SystemFeatureFromJSON(json: any): SystemFeature {
    return SystemFeatureFromJSONTyped(json, false);
}

export function SystemFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'coordinates': json['coordinates'],
        'name': json['name'] == null ? undefined : json['name'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'active': json['active'] === undefined ? undefined : json['active'] === null ? null : json['active'],
        'rank': json['rank'] === undefined ? undefined : json['rank'] === null ? null : json['rank'],
        'source': json['source'] == null ? undefined : json['source'],
        'fetchedAt': json['fetched_at'] === undefined ? undefined : json['fetched_at'] === null ? null : (parseDateTime(json['fetched_at'])),
        'dayKey': json['day_key'] === undefined ? undefined : json['day_key'] === null ? null : (parseDate(json['day_key'])),
        'forecastDays': json['forecast_days'] === undefined ? undefined : json['forecast_days'] === null ? null : json['forecast_days'],
        'lat': json['lat'] === undefined ? undefined : json['lat'] === null ? null : json['lat'],
        'lon': json['lon'] === undefined ? undefined : json['lon'] === null ? null : json['lon'],
    };
}

export function SystemFeatureToJSON(json: any): SystemFeature {
    return SystemFeatureToJSONTyped(json, false);
}

export function SystemFeatureToJSONTyped(value?: SystemFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'coordinates': value['coordinates'],
        'name': value['name'],
        'profile': value['profile'],
        'active': value['active'],
        'rank': value['rank'],
        'source': value['source'],
        'fetched_at': value['fetchedAt'] == null ? value['fetchedAt'] : serializeDateTime(value['fetchedAt']),
        'day_key': value['dayKey'] == null ? value['dayKey'] : serializeDate(value['dayKey']),
        'forecast_days': value['forecastDays'],
        'lat': value['lat'],
        'lon': value['lon'],
    };
}

