// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemCacheCount
 */
export interface SystemCacheCount {
    /**
     * 
     */
    kind: string;
    /**
     * 
     */
    source: string;
    /**
     * 
     */
    records: number;
    /**
     * 
     */
    fresh: number;
    /**
     * 
     */
    stale: number;
    /**
     * 
     */
    locations: number;
}

/**
 * Check if a given object implements the SystemCacheCount interface.
 */
export function instanceOfSystemCacheCount(value: object): value is SystemCacheCount {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('fresh' in value) || value['fresh'] === undefined) return false;
    if (!('stale' in value) || value['stale'] === undefined) return false;
    if (!('locations' in value) || value['locations'] === undefined) return false;
    return true;
}

export function SystemCacheCountFromJSON(json: any): SystemCacheCount {
    return SystemCacheCountFromJSONTyped(json, false);
}

export function SystemCacheCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemCacheCount {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'source': json['source'],
        'records': json['records'],
        'fresh': json['fresh'],
        'stale': json['stale'],
        'locations': json['locations'],
    };
}

export function SystemCacheCountToJSON(json: any): SystemCacheCount {
    return SystemCacheCountToJSONTyped(json, false);
}

export function SystemCacheCountToJSONTyped(value?: SystemCacheCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'source': value['source'],
        'records': value['records'],
        'fresh': value['fresh'],
        'stale': value['stale'],
        'locations': value['locations'],
    };
}

