// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemElevationCounts
 */
export interface SystemElevationCounts {
    /**
     * 
     */
    full: number;
    /**
     * 
     */
    partial: number;
    /**
     * 
     */
    fallback: number;
}

/**
 * Check if a given object implements the SystemElevationCounts interface.
 */
export function instanceOfSystemElevationCounts(value: object): value is SystemElevationCounts {
    if (!('full' in value) || value['full'] === undefined) return false;
    if (!('partial' in value) || value['partial'] === undefined) return false;
    if (!('fallback' in value) || value['fallback'] === undefined) return false;
    return true;
}

export function SystemElevationCountsFromJSON(json: any): SystemElevationCounts {
    return SystemElevationCountsFromJSONTyped(json, false);
}

export function SystemElevationCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemElevationCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'full': json['full'],
        'partial': json['partial'],
        'fallback': json['fallback'],
    };
}

export function SystemElevationCountsToJSON(json: any): SystemElevationCounts {
    return SystemElevationCountsToJSONTyped(json, false);
}

export function SystemElevationCountsToJSONTyped(value?: SystemElevationCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full': value['full'],
        'partial': value['partial'],
        'fallback': value['fallback'],
    };
}

