// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemElevationBoxes } from './SystemElevationBoxes';
import {
    SystemElevationBoxesFromJSON,
    SystemElevationBoxesFromJSONTyped,
    SystemElevationBoxesToJSON,
    SystemElevationBoxesToJSONTyped,
} from './SystemElevationBoxes';
import type { SystemTerrainCoverage } from './SystemTerrainCoverage';
import {
    SystemTerrainCoverageFromJSON,
    SystemTerrainCoverageFromJSONTyped,
    SystemTerrainCoverageToJSON,
    SystemTerrainCoverageToJSONTyped,
} from './SystemTerrainCoverage';
import type { SystemGraphCoverage } from './SystemGraphCoverage';
import {
    SystemGraphCoverageFromJSON,
    SystemGraphCoverageFromJSONTyped,
    SystemGraphCoverageToJSON,
    SystemGraphCoverageToJSONTyped,
} from './SystemGraphCoverage';
import type { SystemPhotonCoverage } from './SystemPhotonCoverage';
import {
    SystemPhotonCoverageFromJSON,
    SystemPhotonCoverageFromJSONTyped,
    SystemPhotonCoverageToJSON,
    SystemPhotonCoverageToJSONTyped,
} from './SystemPhotonCoverage';

/**
 * None for a part that could not be read; the others still answer.
 * @export
 * @interface SystemDataCoverage
 */
export interface SystemDataCoverage {
    /**
     * 
     */
    graph: SystemGraphCoverage | null;
    /**
     * 
     */
    terrain: SystemTerrainCoverage | null;
    /**
     * 
     */
    photon: SystemPhotonCoverage | null;
    /**
     * 
     */
    roadBoxes: Array<Array<number>>;
    /**
     * 
     */
    elevationBoxes: SystemElevationBoxes;
    /**
     * 
     */
    bounds: Array<number> | null;
}

/**
 * Check if a given object implements the SystemDataCoverage interface.
 */
export function instanceOfSystemDataCoverage(value: object): value is SystemDataCoverage {
    if (!('graph' in value) || value['graph'] === undefined) return false;
    if (!('terrain' in value) || value['terrain'] === undefined) return false;
    if (!('photon' in value) || value['photon'] === undefined) return false;
    if ((!('roadBoxes' in (value as Record<string, any>)) && !('road_boxes' in (value as Record<string, any>))) || ((value as Record<string, any>)['roadBoxes'] === undefined && (value as Record<string, any>)['road_boxes'] === undefined)) return false;
    if ((!('elevationBoxes' in (value as Record<string, any>)) && !('elevation_boxes' in (value as Record<string, any>))) || ((value as Record<string, any>)['elevationBoxes'] === undefined && (value as Record<string, any>)['elevation_boxes'] === undefined)) return false;
    if (!('bounds' in value) || value['bounds'] === undefined) return false;
    return true;
}

export function SystemDataCoverageFromJSON(json: any): SystemDataCoverage {
    return SystemDataCoverageFromJSONTyped(json, false);
}

export function SystemDataCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemDataCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'graph': SystemGraphCoverageFromJSON(json['graph']),
        'terrain': SystemTerrainCoverageFromJSON(json['terrain']),
        'photon': SystemPhotonCoverageFromJSON(json['photon']),
        'roadBoxes': json['road_boxes'],
        'elevationBoxes': SystemElevationBoxesFromJSON(json['elevation_boxes']),
        'bounds': json['bounds'] == null ? null : json['bounds'],
    };
}

export function SystemDataCoverageToJSON(json: any): SystemDataCoverage {
    return SystemDataCoverageToJSONTyped(json, false);
}

export function SystemDataCoverageToJSONTyped(value?: SystemDataCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'graph': SystemGraphCoverageToJSON(value['graph']),
        'terrain': SystemTerrainCoverageToJSON(value['terrain']),
        'photon': SystemPhotonCoverageToJSON(value['photon']),
        'road_boxes': value['roadBoxes'],
        'elevation_boxes': SystemElevationBoxesToJSON(value['elevationBoxes']),
        'bounds': value['bounds'],
    };
}

