// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemTerrainSource } from './SystemTerrainSource';
import {
    SystemTerrainSourceFromJSON,
    SystemTerrainSourceFromJSONTyped,
    SystemTerrainSourceToJSON,
    SystemTerrainSourceToJSONTyped,
} from './SystemTerrainSource';
import type { SystemElevationCounts } from './SystemElevationCounts';
import {
    SystemElevationCountsFromJSON,
    SystemElevationCountsFromJSONTyped,
    SystemElevationCountsToJSON,
    SystemElevationCountsToJSONTyped,
} from './SystemElevationCounts';
import type { SystemTerrainCheck } from './SystemTerrainCheck';
import {
    SystemTerrainCheckFromJSON,
    SystemTerrainCheckFromJSONTyped,
    SystemTerrainCheckToJSON,
    SystemTerrainCheckToJSONTyped,
} from './SystemTerrainCheck';

/**
 * 
 * @export
 * @interface SystemTerrainCoverage
 */
export interface SystemTerrainCoverage {
    /**
     * 
     */
    key: string;
    /**
     * 
     */
    catalogVersion: string;
    /**
     * 
     */
    zoom: number | null;
    /**
     * 
     */
    fallbackZoom: number | null;
    /**
     * 
     */
    sources: Array<SystemTerrainSource>;
    /**
     * 
     */
    fallbackSource: string | null;
    /**
     * 
     */
    checks: Array<SystemTerrainCheck>;
    /**
     * 
     */
    cellCounts: SystemElevationCounts | null;
}

/**
 * Check if a given object implements the SystemTerrainCoverage interface.
 */
export function instanceOfSystemTerrainCoverage(value: object): value is SystemTerrainCoverage {
    if (!('key' in value) || value['key'] === undefined) return false;
    if ((!('catalogVersion' in (value as Record<string, any>)) && !('catalog_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['catalogVersion'] === undefined && (value as Record<string, any>)['catalog_version'] === undefined)) return false;
    if (!('zoom' in value) || value['zoom'] === undefined) return false;
    if ((!('fallbackZoom' in (value as Record<string, any>)) && !('fallback_zoom' in (value as Record<string, any>))) || ((value as Record<string, any>)['fallbackZoom'] === undefined && (value as Record<string, any>)['fallback_zoom'] === undefined)) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    if ((!('fallbackSource' in (value as Record<string, any>)) && !('fallback_source' in (value as Record<string, any>))) || ((value as Record<string, any>)['fallbackSource'] === undefined && (value as Record<string, any>)['fallback_source'] === undefined)) return false;
    if (!('checks' in value) || value['checks'] === undefined) return false;
    if ((!('cellCounts' in (value as Record<string, any>)) && !('cell_counts' in (value as Record<string, any>))) || ((value as Record<string, any>)['cellCounts'] === undefined && (value as Record<string, any>)['cell_counts'] === undefined)) return false;
    return true;
}

export function SystemTerrainCoverageFromJSON(json: any): SystemTerrainCoverage {
    return SystemTerrainCoverageFromJSONTyped(json, false);
}

export function SystemTerrainCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemTerrainCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'catalogVersion': json['catalog_version'],
        'zoom': json['zoom'],
        'fallbackZoom': json['fallback_zoom'],
        'sources': ((json['sources'] as Array<any>).map(SystemTerrainSourceFromJSON)),
        'fallbackSource': json['fallback_source'],
        'checks': ((json['checks'] as Array<any>).map(SystemTerrainCheckFromJSON)),
        'cellCounts': SystemElevationCountsFromJSON(json['cell_counts']),
    };
}

export function SystemTerrainCoverageToJSON(json: any): SystemTerrainCoverage {
    return SystemTerrainCoverageToJSONTyped(json, false);
}

export function SystemTerrainCoverageToJSONTyped(value?: SystemTerrainCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'catalog_version': value['catalogVersion'],
        'zoom': value['zoom'],
        'fallback_zoom': value['fallbackZoom'],
        'sources': ((value['sources'] as Array<any>).map(SystemTerrainSourceToJSON)),
        'fallback_source': value['fallbackSource'],
        'checks': ((value['checks'] as Array<any>).map(SystemTerrainCheckToJSON)),
        'cell_counts': SystemElevationCountsToJSON(value['cellCounts']),
    };
}

