// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemGraphCoverage
 */
export interface SystemGraphCoverage {
    /**
     * 
     */
    release: string;
    /**
     * 
     */
    revision: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    builtAt: Date | null;
    /**
     * 
     */
    osmFile: string | null;
    /**
     * 
     */
    osmFileModified: Date | null;
    /**
     * 
     */
    cellsSource: SystemGraphCoverageCellsSourceEnum;
    /**
     * 
     */
    cells: number;
}

/**
* @export
* @enum {string}
*/
export enum SystemGraphCoverageCellsSourceEnum {
    Graph = 'graph',
    Terrain = 'terrain',
    Bounds = 'bounds'
}


/**
 * Check if a given object implements the SystemGraphCoverage interface.
 */
export function instanceOfSystemGraphCoverage(value: object): value is SystemGraphCoverage {
    if (!('release' in value) || value['release'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('builtAt' in (value as Record<string, any>)) && !('built_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['builtAt'] === undefined && (value as Record<string, any>)['built_at'] === undefined)) return false;
    if ((!('osmFile' in (value as Record<string, any>)) && !('osm_file' in (value as Record<string, any>))) || ((value as Record<string, any>)['osmFile'] === undefined && (value as Record<string, any>)['osm_file'] === undefined)) return false;
    if ((!('osmFileModified' in (value as Record<string, any>)) && !('osm_file_modified' in (value as Record<string, any>))) || ((value as Record<string, any>)['osmFileModified'] === undefined && (value as Record<string, any>)['osm_file_modified'] === undefined)) return false;
    if ((!('cellsSource' in (value as Record<string, any>)) && !('cells_source' in (value as Record<string, any>))) || ((value as Record<string, any>)['cellsSource'] === undefined && (value as Record<string, any>)['cells_source'] === undefined)) return false;
    if (!('cells' in value) || value['cells'] === undefined) return false;
    return true;
}

export function SystemGraphCoverageFromJSON(json: any): SystemGraphCoverage {
    return SystemGraphCoverageFromJSONTyped(json, false);
}

export function SystemGraphCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemGraphCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'release': json['release'],
        'revision': json['revision'],
        'status': json['status'],
        'builtAt': (json['built_at'] == null ? null : parseDateTime(json['built_at'])),
        'osmFile': json['osm_file'],
        'osmFileModified': (json['osm_file_modified'] == null ? null : parseDateTime(json['osm_file_modified'])),
        'cellsSource': json['cells_source'],
        'cells': json['cells'],
    };
}

export function SystemGraphCoverageToJSON(json: any): SystemGraphCoverage {
    return SystemGraphCoverageToJSONTyped(json, false);
}

export function SystemGraphCoverageToJSONTyped(value?: SystemGraphCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'release': value['release'],
        'revision': value['revision'],
        'status': value['status'],
        'built_at': value['builtAt'] == null ? value['builtAt'] : serializeDateTime(value['builtAt']),
        'osm_file': value['osmFile'],
        'osm_file_modified': value['osmFileModified'] == null ? value['osmFileModified'] : serializeDateTime(value['osmFileModified']),
        'cells_source': value['cellsSource'],
        'cells': value['cells'],
    };
}

