// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemTerrainSource
 */
export interface SystemTerrainSource {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    bbox: Array<number | null>;
}

/**
 * Check if a given object implements the SystemTerrainSource interface.
 */
export function instanceOfSystemTerrainSource(value: object): value is SystemTerrainSource {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    return true;
}

export function SystemTerrainSourceFromJSON(json: any): SystemTerrainSource {
    return SystemTerrainSourceFromJSONTyped(json, false);
}

export function SystemTerrainSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemTerrainSource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bbox': json['bbox'],
    };
}

export function SystemTerrainSourceToJSON(json: any): SystemTerrainSource {
    return SystemTerrainSourceToJSONTyped(json, false);
}

export function SystemTerrainSourceToJSONTyped(value?: SystemTerrainSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'bbox': value['bbox'],
    };
}

