// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemBrowserStatsDay
 */
export interface SystemBrowserStatsDay {
    /**
     * 
     */
    day: Date;
    /**
     * 
     */
    counts: { [key: string]: number; };
}

/**
 * Check if a given object implements the SystemBrowserStatsDay interface.
 */
export function instanceOfSystemBrowserStatsDay(value: object): value is SystemBrowserStatsDay {
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('counts' in value) || value['counts'] === undefined) return false;
    return true;
}

export function SystemBrowserStatsDayFromJSON(json: any): SystemBrowserStatsDay {
    return SystemBrowserStatsDayFromJSONTyped(json, false);
}

export function SystemBrowserStatsDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemBrowserStatsDay {
    if (json == null) {
        return json;
    }
    return {
        
        'day': (json['day'] == null ? json['day'] : parseDate(json['day'])),
        'counts': json['counts'],
    };
}

export function SystemBrowserStatsDayToJSON(json: any): SystemBrowserStatsDay {
    return SystemBrowserStatsDayToJSONTyped(json, false);
}

export function SystemBrowserStatsDayToJSONTyped(value?: SystemBrowserStatsDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'] == null ? value['day'] : serializeDate(value['day']),
        'counts': value['counts'],
    };
}

