// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { SystemFeature } from './SystemFeature';
import {
    SystemFeatureFromJSON,
    SystemFeatureFromJSONTyped,
    SystemFeatureToJSON,
    SystemFeatureToJSONTyped,
} from './SystemFeature';

/**
 * 
 * @export
 * @interface SystemMapPage
 */
export interface SystemMapPage {
    /**
     * 
     */
    items: Array<SystemFeature>;
    /**
     * 
     */
    total: number;
    /**
     * 
     */
    nextOffset: number | null;
    /**
     * 
     */
    generatedAt: Date;
}

/**
 * Check if a given object implements the SystemMapPage interface.
 */
export function instanceOfSystemMapPage(value: object): value is SystemMapPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if ((!('nextOffset' in (value as Record<string, any>)) && !('next_offset' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextOffset'] === undefined && (value as Record<string, any>)['next_offset'] === undefined)) return false;
    if ((!('generatedAt' in (value as Record<string, any>)) && !('generated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['generatedAt'] === undefined && (value as Record<string, any>)['generated_at'] === undefined)) return false;
    return true;
}

export function SystemMapPageFromJSON(json: any): SystemMapPage {
    return SystemMapPageFromJSONTyped(json, false);
}

export function SystemMapPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemMapPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SystemFeatureFromJSON)),
        'total': json['total'],
        'nextOffset': json['next_offset'],
        'generatedAt': (json['generated_at'] == null ? json['generated_at'] : parseDateTime(json['generated_at'])),
    };
}

export function SystemMapPageToJSON(json: any): SystemMapPage {
    return SystemMapPageToJSONTyped(json, false);
}

export function SystemMapPageToJSONTyped(value?: SystemMapPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SystemFeatureToJSON)),
        'total': value['total'],
        'next_offset': value['nextOffset'],
        'generated_at': value['generatedAt'] == null ? value['generatedAt'] : serializeDateTime(value['generatedAt']),
    };
}

