// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemJob
 */
export interface SystemJob {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    kind: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    cellsTotal: number;
    /**
     * 
     */
    cellsSettled: number;
    /**
     * 
     */
    cellsFailed: number;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    error: string;
    /**
     * 
     */
    possiblyStalled: boolean;
}

/**
 * Check if a given object implements the SystemJob interface.
 */
export function instanceOfSystemJob(value: object): value is SystemJob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('cellsTotal' in (value as Record<string, any>)) && !('cells_total' in (value as Record<string, any>))) || ((value as Record<string, any>)['cellsTotal'] === undefined && (value as Record<string, any>)['cells_total'] === undefined)) return false;
    if ((!('cellsSettled' in (value as Record<string, any>)) && !('cells_settled' in (value as Record<string, any>))) || ((value as Record<string, any>)['cellsSettled'] === undefined && (value as Record<string, any>)['cells_settled'] === undefined)) return false;
    if ((!('cellsFailed' in (value as Record<string, any>)) && !('cells_failed' in (value as Record<string, any>))) || ((value as Record<string, any>)['cellsFailed'] === undefined && (value as Record<string, any>)['cells_failed'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if ((!('possiblyStalled' in (value as Record<string, any>)) && !('possibly_stalled' in (value as Record<string, any>))) || ((value as Record<string, any>)['possiblyStalled'] === undefined && (value as Record<string, any>)['possibly_stalled'] === undefined)) return false;
    return true;
}

export function SystemJobFromJSON(json: any): SystemJob {
    return SystemJobFromJSONTyped(json, false);
}

export function SystemJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'status': json['status'],
        'cellsTotal': json['cells_total'],
        'cellsSettled': json['cells_settled'],
        'cellsFailed': json['cells_failed'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'error': json['error'],
        'possiblyStalled': json['possibly_stalled'],
    };
}

export function SystemJobToJSON(json: any): SystemJob {
    return SystemJobToJSONTyped(json, false);
}

export function SystemJobToJSONTyped(value?: SystemJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'status': value['status'],
        'cells_total': value['cellsTotal'],
        'cells_settled': value['cellsSettled'],
        'cells_failed': value['cellsFailed'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'error': value['error'],
        'possibly_stalled': value['possiblyStalled'],
    };
}

