// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemElevationBoxes
 */
export interface SystemElevationBoxes {
    /**
     * 
     */
    full: Array<Array<number>>;
    /**
     * 
     */
    partial: Array<Array<number>>;
    /**
     * 
     */
    fallback: Array<Array<number>>;
}

/**
 * Check if a given object implements the SystemElevationBoxes interface.
 */
export function instanceOfSystemElevationBoxes(value: object): value is SystemElevationBoxes {
    if (!('full' in value) || value['full'] === undefined) return false;
    if (!('partial' in value) || value['partial'] === undefined) return false;
    if (!('fallback' in value) || value['fallback'] === undefined) return false;
    return true;
}

export function SystemElevationBoxesFromJSON(json: any): SystemElevationBoxes {
    return SystemElevationBoxesFromJSONTyped(json, false);
}

export function SystemElevationBoxesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemElevationBoxes {
    if (json == null) {
        return json;
    }
    return {
        
        'full': json['full'],
        'partial': json['partial'],
        'fallback': json['fallback'],
    };
}

export function SystemElevationBoxesToJSON(json: any): SystemElevationBoxes {
    return SystemElevationBoxesToJSONTyped(json, false);
}

export function SystemElevationBoxesToJSONTyped(value?: SystemElevationBoxes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full': value['full'],
        'partial': value['partial'],
        'fallback': value['fallback'],
    };
}

