// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemBrowserAssessment
 */
export interface SystemBrowserAssessment {
    /**
     * 
     */
    tier: SystemBrowserAssessmentTierEnum;
    /**
     * 
     */
    indicators: Array<string>;
    /**
     * 
     */
    persistent: boolean;
    /**
     * 
     */
    established: boolean;
    /**
     * 
     */
    continuity: boolean;
    /**
     * 
     */
    similarity: number | null;
    /**
     * 
     */
    browserId: string;
    /**
     * 
     */
    fingerprintId: string | null;
    /**
     * 
     */
    components: { [key: string]: string; };
    /**
     * 
     */
    keys: Array<string>;
    /**
     * 
     */
    path?: string | null;
    /**
     * 
     */
    pathTransport?: string | null;
    /**
     * 
     */
    pathExcess?: number | null;
}

/**
* @export
* @enum {string}
*/
export enum SystemBrowserAssessmentTierEnum {
    High = 'high',
    Low = 'low',
    Suspicious = 'suspicious'
}


/**
 * Check if a given object implements the SystemBrowserAssessment interface.
 */
export function instanceOfSystemBrowserAssessment(value: object): value is SystemBrowserAssessment {
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('indicators' in value) || value['indicators'] === undefined) return false;
    if (!('persistent' in value) || value['persistent'] === undefined) return false;
    if (!('established' in value) || value['established'] === undefined) return false;
    if (!('continuity' in value) || value['continuity'] === undefined) return false;
    if (!('similarity' in value) || value['similarity'] === undefined) return false;
    if ((!('browserId' in (value as Record<string, any>)) && !('browser_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['browserId'] === undefined && (value as Record<string, any>)['browser_id'] === undefined)) return false;
    if ((!('fingerprintId' in (value as Record<string, any>)) && !('fingerprint_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['fingerprintId'] === undefined && (value as Record<string, any>)['fingerprint_id'] === undefined)) return false;
    if (!('components' in value) || value['components'] === undefined) return false;
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function SystemBrowserAssessmentFromJSON(json: any): SystemBrowserAssessment {
    return SystemBrowserAssessmentFromJSONTyped(json, false);
}

export function SystemBrowserAssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemBrowserAssessment {
    if (json == null) {
        return json;
    }
    return {
        
        'tier': json['tier'],
        'indicators': json['indicators'],
        'persistent': json['persistent'],
        'established': json['established'],
        'continuity': json['continuity'],
        'similarity': json['similarity'],
        'browserId': json['browser_id'],
        'fingerprintId': json['fingerprint_id'],
        'components': json['components'],
        'keys': json['keys'],
        'path': json['path'] === undefined ? undefined : json['path'] === null ? null : json['path'],
        'pathTransport': json['path_transport'] === undefined ? undefined : json['path_transport'] === null ? null : json['path_transport'],
        'pathExcess': json['path_excess'] === undefined ? undefined : json['path_excess'] === null ? null : json['path_excess'],
    };
}

export function SystemBrowserAssessmentToJSON(json: any): SystemBrowserAssessment {
    return SystemBrowserAssessmentToJSONTyped(json, false);
}

export function SystemBrowserAssessmentToJSONTyped(value?: SystemBrowserAssessment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tier': value['tier'],
        'indicators': value['indicators'],
        'persistent': value['persistent'],
        'established': value['established'],
        'continuity': value['continuity'],
        'similarity': value['similarity'],
        'browser_id': value['browserId'],
        'fingerprint_id': value['fingerprintId'],
        'components': value['components'],
        'keys': value['keys'],
        'path': value['path'],
        'path_transport': value['pathTransport'],
        'path_excess': value['pathExcess'],
    };
}

