// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemMapFilter
 */
export interface SystemMapFilter {
    /**
     * 
     */
    layer: SystemMapFilterLayerEnum;
    /**
     * 
     */
    bbox?: string | null;
    /**
     * 
     */
    zoom?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    kind?: SystemMapFilterKindEnum;
    /**
     * 
     */
    source?: SystemMapFilterSourceEnum;
    /**
     * 
     */
    day?: Date | null;
    /**
     * 
     */
    active?: boolean | null;
    /**
     * 
     */
    profile?: SystemMapFilterProfileEnum | null;
    /**
     * 
     */
    alternatives?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum SystemMapFilterLayerEnum {
    Routes = 'routes',
    Journeys = 'journeys',
    Cells = 'cells'
}
/**
* @export
* @enum {string}
*/
export enum SystemMapFilterKindEnum {
    Forecast = 'forecast',
    Ensemble = 'ensemble'
}
/**
* @export
* @enum {string}
*/
export enum SystemMapFilterSourceEnum {
    All = 'all',
    OpenMeteo = 'open-meteo',
    Openweathermap = 'openweathermap'
}
/**
* @export
* @enum {string}
*/
export enum SystemMapFilterProfileEnum {
    Bike = 'bike',
    Ebike = 'ebike',
    FastEbike = 'fast_ebike',
    Hike = 'hike'
}


/**
 * Check if a given object implements the SystemMapFilter interface.
 */
export function instanceOfSystemMapFilter(value: object): value is SystemMapFilter {
    if (!('layer' in value) || value['layer'] === undefined) return false;
    return true;
}

export function SystemMapFilterFromJSON(json: any): SystemMapFilter {
    return SystemMapFilterFromJSONTyped(json, false);
}

export function SystemMapFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemMapFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'layer': json['layer'],
        'bbox': json['bbox'] === undefined ? undefined : json['bbox'] === null ? null : json['bbox'],
        'zoom': json['zoom'] == null ? undefined : json['zoom'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'source': json['source'] == null ? undefined : json['source'],
        'day': json['day'] === undefined ? undefined : json['day'] === null ? null : (parseDate(json['day'])),
        'active': json['active'] === undefined ? undefined : json['active'] === null ? null : json['active'],
        'profile': json['profile'] === undefined ? undefined : json['profile'] === null ? null : json['profile'],
        'alternatives': json['alternatives'] == null ? undefined : json['alternatives'],
    };
}

export function SystemMapFilterToJSON(json: any): SystemMapFilter {
    return SystemMapFilterToJSONTyped(json, false);
}

export function SystemMapFilterToJSONTyped(value?: SystemMapFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layer': value['layer'],
        'bbox': value['bbox'],
        'zoom': value['zoom'],
        'offset': value['offset'],
        'limit': value['limit'],
        'kind': value['kind'],
        'source': value['source'],
        'day': value['day'] == null ? value['day'] : serializeDate(value['day']),
        'active': value['active'],
        'profile': value['profile'],
        'alternatives': value['alternatives'],
    };
}

