// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemPhotonCountry
 */
export interface SystemPhotonCountry {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    places: number;
}

/**
 * Check if a given object implements the SystemPhotonCountry interface.
 */
export function instanceOfSystemPhotonCountry(value: object): value is SystemPhotonCountry {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('places' in value) || value['places'] === undefined) return false;
    return true;
}

export function SystemPhotonCountryFromJSON(json: any): SystemPhotonCountry {
    return SystemPhotonCountryFromJSONTyped(json, false);
}

export function SystemPhotonCountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemPhotonCountry {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'places': json['places'],
    };
}

export function SystemPhotonCountryToJSON(json: any): SystemPhotonCountry {
    return SystemPhotonCountryToJSONTyped(json, false);
}

export function SystemPhotonCountryToJSONTyped(value?: SystemPhotonCountry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'places': value['places'],
    };
}

