// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenIn
 */
export interface TokenIn {
    /**
     * 
     */
    token: string;
}

/**
 * Check if a given object implements the TokenIn interface.
 */
export function instanceOfTokenIn(value: object): value is TokenIn {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TokenInFromJSON(json: any): TokenIn {
    return TokenInFromJSONTyped(json, false);
}

export function TokenInFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenIn {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TokenInToJSON(json: any): TokenIn {
    return TokenInToJSONTyped(json, false);
}

export function TokenInToJSONTyped(value?: TokenIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

