// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Whether to ride around bad weather: the rider's choice, off unless they make it, and only
 * kept for accounts with ``weather_routing`` (Plus). See ``_values``.
 * @export
 * @interface WeatherPrefsIn
 */
export interface WeatherPrefsIn {
    /**
     * 
     */
    avoidRain?: boolean;
    /**
     * 
     */
    avoidHeadwind?: boolean;
    /**
     * 
     */
    avoidShade?: boolean;
    /**
     * 
     */
    departureWindowMinutes?: number;
}

/**
 * Check if a given object implements the WeatherPrefsIn interface.
 */
export function instanceOfWeatherPrefsIn(value: object): value is WeatherPrefsIn {
    return true;
}

export function WeatherPrefsInFromJSON(json: any): WeatherPrefsIn {
    return WeatherPrefsInFromJSONTyped(json, false);
}

export function WeatherPrefsInFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherPrefsIn {
    if (json == null) {
        return json;
    }
    return {
        
        'avoidRain': json['avoid_rain'] == null ? undefined : json['avoid_rain'],
        'avoidHeadwind': json['avoid_headwind'] == null ? undefined : json['avoid_headwind'],
        'avoidShade': json['avoid_shade'] == null ? undefined : json['avoid_shade'],
        'departureWindowMinutes': json['departure_window_minutes'] == null ? undefined : json['departure_window_minutes'],
    };
}

export function WeatherPrefsInToJSON(json: any): WeatherPrefsIn {
    return WeatherPrefsInToJSONTyped(json, false);
}

export function WeatherPrefsInToJSONTyped(value?: WeatherPrefsIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avoid_rain': value['avoidRain'],
        'avoid_headwind': value['avoidHeadwind'],
        'avoid_shade': value['avoidShade'],
        'departure_window_minutes': value['departureWindowMinutes'],
    };
}

