// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WindDistribution
 */
export interface WindDistribution {
    /**
     * 
     */
    headwindM: number;
    /**
     * 
     */
    crosswindM: number;
    /**
     * 
     */
    tailwindM: number;
    /**
     * 
     */
    calmM: number;
    /**
     * 
     */
    unknownM: number;
    /**
     * 
     */
    meanFeltSpeed?: number | null;
    /**
     * 
     */
    maxFeltSpeed?: number | null;
    /**
     * 
     */
    feltCoveredM: number;
    /**
     * 
     */
    meanWindPowerW?: number | null;
    /**
     * 
     */
    maxWindPowerW?: number | null;
    /**
     * 
     */
    timingSource: WindDistributionTimingSourceEnum;
}

/**
* @export
* @enum {string}
*/
export enum WindDistributionTimingSourceEnum {
    Routing = 'routing',
    SampleInterpolation = 'sample-interpolation',
    Unavailable = 'unavailable'
}


/**
 * Check if a given object implements the WindDistribution interface.
 */
export function instanceOfWindDistribution(value: object): value is WindDistribution {
    if ((!('headwindM' in (value as Record<string, any>)) && !('headwind_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['headwindM'] === undefined && (value as Record<string, any>)['headwind_m'] === undefined)) return false;
    if ((!('crosswindM' in (value as Record<string, any>)) && !('crosswind_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['crosswindM'] === undefined && (value as Record<string, any>)['crosswind_m'] === undefined)) return false;
    if ((!('tailwindM' in (value as Record<string, any>)) && !('tailwind_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['tailwindM'] === undefined && (value as Record<string, any>)['tailwind_m'] === undefined)) return false;
    if ((!('calmM' in (value as Record<string, any>)) && !('calm_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['calmM'] === undefined && (value as Record<string, any>)['calm_m'] === undefined)) return false;
    if ((!('unknownM' in (value as Record<string, any>)) && !('unknown_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['unknownM'] === undefined && (value as Record<string, any>)['unknown_m'] === undefined)) return false;
    if ((!('feltCoveredM' in (value as Record<string, any>)) && !('felt_covered_m' in (value as Record<string, any>))) || ((value as Record<string, any>)['feltCoveredM'] === undefined && (value as Record<string, any>)['felt_covered_m'] === undefined)) return false;
    if ((!('timingSource' in (value as Record<string, any>)) && !('timing_source' in (value as Record<string, any>))) || ((value as Record<string, any>)['timingSource'] === undefined && (value as Record<string, any>)['timing_source'] === undefined)) return false;
    return true;
}

export function WindDistributionFromJSON(json: any): WindDistribution {
    return WindDistributionFromJSONTyped(json, false);
}

export function WindDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WindDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'headwindM': json['headwind_m'],
        'crosswindM': json['crosswind_m'],
        'tailwindM': json['tailwind_m'],
        'calmM': json['calm_m'],
        'unknownM': json['unknown_m'],
        'meanFeltSpeed': json['mean_felt_speed'] === undefined ? undefined : json['mean_felt_speed'] === null ? null : json['mean_felt_speed'],
        'maxFeltSpeed': json['max_felt_speed'] === undefined ? undefined : json['max_felt_speed'] === null ? null : json['max_felt_speed'],
        'feltCoveredM': json['felt_covered_m'],
        'meanWindPowerW': json['mean_wind_power_w'] === undefined ? undefined : json['mean_wind_power_w'] === null ? null : json['mean_wind_power_w'],
        'maxWindPowerW': json['max_wind_power_w'] === undefined ? undefined : json['max_wind_power_w'] === null ? null : json['max_wind_power_w'],
        'timingSource': json['timing_source'],
    };
}

export function WindDistributionToJSON(json: any): WindDistribution {
    return WindDistributionToJSONTyped(json, false);
}

export function WindDistributionToJSONTyped(value?: WindDistribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headwind_m': value['headwindM'],
        'crosswind_m': value['crosswindM'],
        'tailwind_m': value['tailwindM'],
        'calm_m': value['calmM'],
        'unknown_m': value['unknownM'],
        'mean_felt_speed': value['meanFeltSpeed'],
        'max_felt_speed': value['maxFeltSpeed'],
        'felt_covered_m': value['feltCoveredM'],
        'mean_wind_power_w': value['meanWindPowerW'],
        'max_wind_power_w': value['maxWindPowerW'],
        'timing_source': value['timingSource'],
    };
}

