// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One felt-wind arrow for the map: only segments with complete felt-wind data.
 * @export
 * @interface WindArrow
 */
export interface WindArrow {
    /**
     * 
     */
    lat: number;
    /**
     * 
     */
    lon: number;
    /**
     * 
     */
    bearing: number;
    /**
     * 
     */
    feltSpeed: number;
    /**
     * 
     */
    feltAngle: number;
}

/**
 * Check if a given object implements the WindArrow interface.
 */
export function instanceOfWindArrow(value: object): value is WindArrow {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if (!('bearing' in value) || value['bearing'] === undefined) return false;
    if ((!('feltSpeed' in (value as Record<string, any>)) && !('felt_speed' in (value as Record<string, any>))) || ((value as Record<string, any>)['feltSpeed'] === undefined && (value as Record<string, any>)['felt_speed'] === undefined)) return false;
    if ((!('feltAngle' in (value as Record<string, any>)) && !('felt_angle' in (value as Record<string, any>))) || ((value as Record<string, any>)['feltAngle'] === undefined && (value as Record<string, any>)['felt_angle'] === undefined)) return false;
    return true;
}

export function WindArrowFromJSON(json: any): WindArrow {
    return WindArrowFromJSONTyped(json, false);
}

export function WindArrowFromJSONTyped(json: any, ignoreDiscriminator: boolean): WindArrow {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lon': json['lon'],
        'bearing': json['bearing'],
        'feltSpeed': json['felt_speed'],
        'feltAngle': json['felt_angle'],
    };
}

export function WindArrowToJSON(json: any): WindArrow {
    return WindArrowToJSONTyped(json, false);
}

export function WindArrowToJSONTyped(value?: WindArrow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lon': value['lon'],
        'bearing': value['bearing'],
        'felt_speed': value['feltSpeed'],
        'felt_angle': value['feltAngle'],
    };
}

