// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One real-wind arrow for the map: only segments with complete ground-wind data.
 * @export
 * @interface WindArrow
 */
export interface WindArrow {
    /**
     * 
     */
    bearing: number;
    /**
     * 
     */
    lat: number;
    /**
     * 
     */
    lon: number;
    /**
     * 
     */
    windDir: number;
    /**
     * 
     */
    windEffort?: number;
    /**
     * 
     */
    windEffortLevel?: string | null;
    /**
     * 
     */
    windPowerW?: number | null;
    /**
     * 
     */
    windSpeed: number;
}

/**
 * Check if a given object implements the WindArrow interface.
 */
export function instanceOfWindArrow(value: object): value is WindArrow {
    if (!('bearing' in value) || value['bearing'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if ((!('windDir' in (value as Record<string, any>)) && !('wind_dir' in (value as Record<string, any>))) || ((value as Record<string, any>)['windDir'] === undefined && (value as Record<string, any>)['wind_dir'] === undefined)) return false;
    if ((!('windSpeed' in (value as Record<string, any>)) && !('wind_speed' in (value as Record<string, any>))) || ((value as Record<string, any>)['windSpeed'] === undefined && (value as Record<string, any>)['wind_speed'] === undefined)) return false;
    return true;
}

export function WindArrowFromJSON(json: any): WindArrow {
    return WindArrowFromJSONTyped(json, false);
}

export function WindArrowFromJSONTyped(json: any, ignoreDiscriminator: boolean): WindArrow {
    if (json == null) {
        return json;
    }
    return {
        
        'bearing': json['bearing'],
        'lat': json['lat'],
        'lon': json['lon'],
        'windDir': json['wind_dir'],
        'windEffort': json['wind_effort'] == null ? undefined : json['wind_effort'],
        'windEffortLevel': json['wind_effort_level'] === undefined ? undefined : json['wind_effort_level'] === null ? null : json['wind_effort_level'],
        'windPowerW': json['wind_power_w'] === undefined ? undefined : json['wind_power_w'] === null ? null : json['wind_power_w'],
        'windSpeed': json['wind_speed'],
    };
}

export function WindArrowToJSON(json: any): WindArrow {
    return WindArrowToJSONTyped(json, false);
}

export function WindArrowToJSONTyped(value?: WindArrow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bearing': value['bearing'],
        'lat': value['lat'],
        'lon': value['lon'],
        'wind_dir': value['windDir'],
        'wind_effort': value['windEffort'],
        'wind_effort_level': value['windEffortLevel'],
        'wind_power_w': value['windPowerW'],
        'wind_speed': value['windSpeed'],
    };
}

