/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ElevationIn,
    ElevationInFromJSON,
    ElevationInToJSON,
} from '../models/ElevationIn';
import {
    type ElevationOut,
    ElevationOutFromJSON,
    ElevationOutToJSON,
} from '../models/ElevationOut';

export interface ElevationApiCoreApiElevationForecastElevationRequest {
    /**
     * 
     */
    jobId: string;
}

export interface ElevationApiCoreApiElevationPreviewElevationRequest {
    /**
     * 
     */
    elevationIn: ElevationIn;
}

export interface ElevationApiCoreApiElevationRouteElevationRequest {
    /**
     * 
     */
    routeId: string;
}

export interface ElevationApiCoreApiElevationStageElevationRequest {
    /**
     * 
     */
    stageId: string;
}

/**
 * 
 */
export class ElevationApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiElevationForecastElevation without sending the request
     */
    async coreApiElevationForecastElevationRequestOpts(requestParameters: ElevationApiCoreApiElevationForecastElevationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling coreApiElevationForecastElevation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/forecast_jobs/{job_id}/elevation`;
        urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Forecast Elevation
     */
    async coreApiElevationForecastElevationRaw(requestParameters: ElevationApiCoreApiElevationForecastElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElevationOut>> {
        const requestOptions = await this.coreApiElevationForecastElevationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElevationOutFromJSON(jsonValue));
    }

    /**
     * Forecast Elevation
     */
    async coreApiElevationForecastElevation(requestParameters: ElevationApiCoreApiElevationForecastElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElevationOut> {
        const response = await this.coreApiElevationForecastElevationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiElevationPreviewElevation without sending the request
     */
    async coreApiElevationPreviewElevationRequestOpts(requestParameters: ElevationApiCoreApiElevationPreviewElevationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['elevationIn'] == null) {
            throw new runtime.RequiredError(
                'elevationIn',
                'Required parameter "elevationIn" was null or undefined when calling coreApiElevationPreviewElevation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/elevation`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ElevationInToJSON(requestParameters['elevationIn']),
        };
    }

    /**
     * Preview Elevation
     */
    async coreApiElevationPreviewElevationRaw(requestParameters: ElevationApiCoreApiElevationPreviewElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElevationOut>> {
        const requestOptions = await this.coreApiElevationPreviewElevationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElevationOutFromJSON(jsonValue));
    }

    /**
     * Preview Elevation
     */
    async coreApiElevationPreviewElevation(requestParameters: ElevationApiCoreApiElevationPreviewElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElevationOut> {
        const response = await this.coreApiElevationPreviewElevationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiElevationRouteElevation without sending the request
     */
    async coreApiElevationRouteElevationRequestOpts(requestParameters: ElevationApiCoreApiElevationRouteElevationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiElevationRouteElevation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}/elevation`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Route Elevation
     */
    async coreApiElevationRouteElevationRaw(requestParameters: ElevationApiCoreApiElevationRouteElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElevationOut>> {
        const requestOptions = await this.coreApiElevationRouteElevationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElevationOutFromJSON(jsonValue));
    }

    /**
     * Route Elevation
     */
    async coreApiElevationRouteElevation(requestParameters: ElevationApiCoreApiElevationRouteElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElevationOut> {
        const response = await this.coreApiElevationRouteElevationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiElevationStageElevation without sending the request
     */
    async coreApiElevationStageElevationRequestOpts(requestParameters: ElevationApiCoreApiElevationStageElevationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['stageId'] == null) {
            throw new runtime.RequiredError(
                'stageId',
                'Required parameter "stageId" was null or undefined when calling coreApiElevationStageElevation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/journey_stages/{stage_id}/elevation`;
        urlPath = urlPath.replace('{stage_id}', encodeURIComponent(String(requestParameters['stageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stage Elevation
     */
    async coreApiElevationStageElevationRaw(requestParameters: ElevationApiCoreApiElevationStageElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElevationOut>> {
        const requestOptions = await this.coreApiElevationStageElevationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElevationOutFromJSON(jsonValue));
    }

    /**
     * Stage Elevation
     */
    async coreApiElevationStageElevation(requestParameters: ElevationApiCoreApiElevationStageElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElevationOut> {
        const response = await this.coreApiElevationStageElevationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
