/* tslint:disable */
/* eslint-disable */
/**
 * MeteoLane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Challenge,
    ChallengeFromJSON,
    ChallengeToJSON,
} from '../models/Challenge';
import {
    type Receipt,
    ReceiptFromJSON,
    ReceiptToJSON,
} from '../models/Receipt';
import {
    type Submission,
    SubmissionFromJSON,
    SubmissionToJSON,
} from '../models/Submission';

export interface FingerprintApiCoreApiFingerprintVerifyRequest {
    /**
     * 
     */
    submission: Submission;
}

/**
 * 
 */
export class FingerprintApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiFingerprintChallenge without sending the request
     */
    async coreApiFingerprintChallengeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/fingerprint/challenge`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Challenge
     */
    async coreApiFingerprintChallengeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Challenge>> {
        const requestOptions = await this.coreApiFingerprintChallengeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeFromJSON(jsonValue));
    }

    /**
     * Challenge
     */
    async coreApiFingerprintChallenge(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Challenge> {
        const response = await this.coreApiFingerprintChallengeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiFingerprintVerify without sending the request
     */
    async coreApiFingerprintVerifyRequestOpts(requestParameters: FingerprintApiCoreApiFingerprintVerifyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['submission'] == null) {
            throw new runtime.RequiredError(
                'submission',
                'Required parameter "submission" was null or undefined when calling coreApiFingerprintVerify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/fingerprint/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmissionToJSON(requestParameters['submission']),
        };
    }

    /**
     * Verify
     */
    async coreApiFingerprintVerifyRaw(requestParameters: FingerprintApiCoreApiFingerprintVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Receipt>> {
        const requestOptions = await this.coreApiFingerprintVerifyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptFromJSON(jsonValue));
    }

    /**
     * Verify
     */
    async coreApiFingerprintVerify(requestParameters: FingerprintApiCoreApiFingerprintVerifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Receipt> {
        const response = await this.coreApiFingerprintVerifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
