/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PlacesSearchResult,
    PlacesSearchResultFromJSON,
    PlacesSearchResultToJSON,
} from '../models/PlacesSearchResult';

export interface CoreApiPlacesSearchRequest {
    /**
     * 
     */
    query: string;
    /**
     * 
     */
    zoom: number;
    /**
     * 
     */
    lat: number;
    /**
     * 
     */
    lon: number;
}

/**
 * 
 */
export class PlacesApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiPlacesSearch without sending the request
     */
    async coreApiPlacesSearchRequestOpts(requestParameters: CoreApiPlacesSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling coreApiPlacesSearch().'
            );
        }

        if (requestParameters['zoom'] == null) {
            throw new runtime.RequiredError(
                'zoom',
                'Required parameter "zoom" was null or undefined when calling coreApiPlacesSearch().'
            );
        }

        if (requestParameters['lat'] == null) {
            throw new runtime.RequiredError(
                'lat',
                'Required parameter "lat" was null or undefined when calling coreApiPlacesSearch().'
            );
        }

        if (requestParameters['lon'] == null) {
            throw new runtime.RequiredError(
                'lon',
                'Required parameter "lon" was null or undefined when calling coreApiPlacesSearch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['zoom'] != null) {
            queryParameters['zoom'] = requestParameters['zoom'];
        }

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search
     */
    async coreApiPlacesSearchRaw(requestParameters: CoreApiPlacesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlacesSearchResult>>> {
        const requestOptions = await this.coreApiPlacesSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlacesSearchResultFromJSON));
    }

    /**
     * Search
     */
    async coreApiPlacesSearch(requestParameters: CoreApiPlacesSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlacesSearchResult>> {
        const response = await this.coreApiPlacesSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
