/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommentIn,
    CommentInFromJSON,
    CommentInToJSON,
} from '../models/CommentIn';
import {
    type CommentOut,
    CommentOutFromJSON,
    CommentOutToJSON,
} from '../models/CommentOut';
import {
    type CopyIn,
    CopyInFromJSON,
    CopyInToJSON,
} from '../models/CopyIn';
import {
    type ElevationOut,
    ElevationOutFromJSON,
    ElevationOutToJSON,
} from '../models/ElevationOut';
import {
    type ForecastJobOut,
    ForecastJobOutFromJSON,
    ForecastJobOutToJSON,
} from '../models/ForecastJobOut';
import {
    type LikeOut,
    LikeOutFromJSON,
    LikeOutToJSON,
} from '../models/LikeOut';
import {
    type PublicRouteDetail,
    PublicRouteDetailFromJSON,
    PublicRouteDetailToJSON,
} from '../models/PublicRouteDetail';
import {
    type PublicRouteSummary,
    PublicRouteSummaryFromJSON,
    PublicRouteSummaryToJSON,
} from '../models/PublicRouteSummary';
import {
    type RecurringRouteOut,
    RecurringRouteOutFromJSON,
    RecurringRouteOutToJSON,
} from '../models/RecurringRouteOut';

export interface PublicRoutesApiCoreApiCommunityAddCommentRequest {
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    commentIn: CommentIn;
}

export interface PublicRoutesApiCoreApiCommunityCopyRouteRequest {
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    copyIn: CopyIn;
}

export interface PublicRoutesApiCoreApiCommunityDeleteCommentRequest {
    /**
     * 
     */
    commentId: string;
}

export interface PublicRoutesApiCoreApiCommunityEditCommentRequest {
    /**
     * 
     */
    commentId: string;
    /**
     * 
     */
    commentIn: CommentIn;
}

export interface PublicRoutesApiCoreApiCommunityGetPublicRouteRequest {
    /**
     * 
     */
    slug: string;
}

export interface PublicRoutesApiCoreApiCommunityLikeRouteRequest {
    /**
     * 
     */
    slug: string;
}

export interface PublicRoutesApiCoreApiCommunityListCommentsRequest {
    /**
     * 
     */
    slug: string;
}

export interface PublicRoutesApiCoreApiCommunityListPublicRoutesRequest {
    /**
     * 
     */
    sort?: CoreApiCommunityListPublicRoutesSortEnum;
    /**
     * 
     */
    q?: string;
    /**
     * 
     */
    bbox?: string | null;
    /**
     * 
     */
    offset?: number;
}

export interface PublicRoutesApiCoreApiCommunityPhotoFileRequest {
    /**
     * 
     */
    photoId: string;
    /**
     * 
     */
    size: CoreApiCommunityPhotoFileSizeEnum;
}

export interface PublicRoutesApiCoreApiCommunityPublicRouteElevationRequest {
    /**
     * 
     */
    slug: string;
}

export interface PublicRoutesApiCoreApiCommunityPublicRouteForecastRequest {
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    date: string;
    /**
     * 
     */
    time: string;
}

export interface PublicRoutesApiCoreApiCommunityUnlikeRouteRequest {
    /**
     * 
     */
    slug: string;
}

/**
 * 
 */
export class PublicRoutesApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiCommunityAddComment without sending the request
     */
    async coreApiCommunityAddCommentRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityAddCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityAddComment().'
            );
        }

        if (requestParameters['commentIn'] == null) {
            throw new runtime.RequiredError(
                'commentIn',
                'Required parameter "commentIn" was null or undefined when calling coreApiCommunityAddComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/public/routes/{slug}/comments`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentInToJSON(requestParameters['commentIn']),
        };
    }

    /**
     * Add Comment
     */
    async coreApiCommunityAddCommentRaw(requestParameters: PublicRoutesApiCoreApiCommunityAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentOut>> {
        const requestOptions = await this.coreApiCommunityAddCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentOutFromJSON(jsonValue));
    }

    /**
     * Add Comment
     */
    async coreApiCommunityAddComment(requestParameters: PublicRoutesApiCoreApiCommunityAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentOut> {
        const response = await this.coreApiCommunityAddCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityCopyRoute without sending the request
     */
    async coreApiCommunityCopyRouteRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityCopyRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityCopyRoute().'
            );
        }

        if (requestParameters['copyIn'] == null) {
            throw new runtime.RequiredError(
                'copyIn',
                'Required parameter "copyIn" was null or undefined when calling coreApiCommunityCopyRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/public/routes/{slug}/copy`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopyInToJSON(requestParameters['copyIn']),
        };
    }

    /**
     * Save the public line as one of the visitor\'s own routes, with their own schedule.  It is an imported path, so the copy rides exactly the line shown (never the hidden ends) and counts against the visitor\'s route quota like any other route.
     * Copy Route
     */
    async coreApiCommunityCopyRouteRaw(requestParameters: PublicRoutesApiCoreApiCommunityCopyRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringRouteOut>> {
        const requestOptions = await this.coreApiCommunityCopyRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringRouteOutFromJSON(jsonValue));
    }

    /**
     * Save the public line as one of the visitor\'s own routes, with their own schedule.  It is an imported path, so the copy rides exactly the line shown (never the hidden ends) and counts against the visitor\'s route quota like any other route.
     * Copy Route
     */
    async coreApiCommunityCopyRoute(requestParameters: PublicRoutesApiCoreApiCommunityCopyRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringRouteOut> {
        const response = await this.coreApiCommunityCopyRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityDeleteComment without sending the request
     */
    async coreApiCommunityDeleteCommentRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityDeleteCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling coreApiCommunityDeleteComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/comments/{comment_id}`;
        urlPath = urlPath.replace('{comment_id}', encodeURIComponent(String(requestParameters['commentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The author may delete a comment, and so may the route\'s owner: it is their page.
     * Delete Comment
     */
    async coreApiCommunityDeleteCommentRaw(requestParameters: PublicRoutesApiCoreApiCommunityDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.coreApiCommunityDeleteCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The author may delete a comment, and so may the route\'s owner: it is their page.
     * Delete Comment
     */
    async coreApiCommunityDeleteComment(requestParameters: PublicRoutesApiCoreApiCommunityDeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiCommunityDeleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for coreApiCommunityEditComment without sending the request
     */
    async coreApiCommunityEditCommentRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityEditCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling coreApiCommunityEditComment().'
            );
        }

        if (requestParameters['commentIn'] == null) {
            throw new runtime.RequiredError(
                'commentIn',
                'Required parameter "commentIn" was null or undefined when calling coreApiCommunityEditComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/public/comments/{comment_id}`;
        urlPath = urlPath.replace('{comment_id}', encodeURIComponent(String(requestParameters['commentId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CommentInToJSON(requestParameters['commentIn']),
        };
    }

    /**
     * Edit Comment
     */
    async coreApiCommunityEditCommentRaw(requestParameters: PublicRoutesApiCoreApiCommunityEditCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentOut>> {
        const requestOptions = await this.coreApiCommunityEditCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentOutFromJSON(jsonValue));
    }

    /**
     * Edit Comment
     */
    async coreApiCommunityEditComment(requestParameters: PublicRoutesApiCoreApiCommunityEditCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentOut> {
        const response = await this.coreApiCommunityEditCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityGetPublicRoute without sending the request
     */
    async coreApiCommunityGetPublicRouteRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityGetPublicRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityGetPublicRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Public Route
     */
    async coreApiCommunityGetPublicRouteRaw(requestParameters: PublicRoutesApiCoreApiCommunityGetPublicRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicRouteDetail>> {
        const requestOptions = await this.coreApiCommunityGetPublicRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicRouteDetailFromJSON(jsonValue));
    }

    /**
     * Get Public Route
     */
    async coreApiCommunityGetPublicRoute(requestParameters: PublicRoutesApiCoreApiCommunityGetPublicRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicRouteDetail> {
        const response = await this.coreApiCommunityGetPublicRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityLikeRoute without sending the request
     */
    async coreApiCommunityLikeRouteRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityLikeRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityLikeRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}/like`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Like Route
     */
    async coreApiCommunityLikeRouteRaw(requestParameters: PublicRoutesApiCoreApiCommunityLikeRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeOut>> {
        const requestOptions = await this.coreApiCommunityLikeRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeOutFromJSON(jsonValue));
    }

    /**
     * Like Route
     */
    async coreApiCommunityLikeRoute(requestParameters: PublicRoutesApiCoreApiCommunityLikeRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeOut> {
        const response = await this.coreApiCommunityLikeRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityListComments without sending the request
     */
    async coreApiCommunityListCommentsRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityListCommentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityListComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}/comments`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Comments
     */
    async coreApiCommunityListCommentsRaw(requestParameters: PublicRoutesApiCoreApiCommunityListCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentOut>>> {
        const requestOptions = await this.coreApiCommunityListCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentOutFromJSON));
    }

    /**
     * List Comments
     */
    async coreApiCommunityListComments(requestParameters: PublicRoutesApiCoreApiCommunityListCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentOut>> {
        const response = await this.coreApiCommunityListCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityListPublicRoutes without sending the request
     */
    async coreApiCommunityListPublicRoutesRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityListPublicRoutesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Discover public routes, newest or most liked first, optionally inside a map box.  ``bbox`` is ``minLon,minLat,maxLon,maxLat``. It is checked against the public line, so a route never turns up for a box that only its hidden ends touch.
     * List Public Routes
     */
    async coreApiCommunityListPublicRoutesRaw(requestParameters: PublicRoutesApiCoreApiCommunityListPublicRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PublicRouteSummary>>> {
        const requestOptions = await this.coreApiCommunityListPublicRoutesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PublicRouteSummaryFromJSON));
    }

    /**
     * Discover public routes, newest or most liked first, optionally inside a map box.  ``bbox`` is ``minLon,minLat,maxLon,maxLat``. It is checked against the public line, so a route never turns up for a box that only its hidden ends touch.
     * List Public Routes
     */
    async coreApiCommunityListPublicRoutes(requestParameters: PublicRoutesApiCoreApiCommunityListPublicRoutesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PublicRouteSummary>> {
        const response = await this.coreApiCommunityListPublicRoutesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityPhotoFile without sending the request
     */
    async coreApiCommunityPhotoFileRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityPhotoFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling coreApiCommunityPhotoFile().'
            );
        }

        if (requestParameters['size'] == null) {
            throw new runtime.RequiredError(
                'size',
                'Required parameter "size" was null or undefined when calling coreApiCommunityPhotoFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/photos/{photo_id}/{size}`;
        urlPath = urlPath.replace('{photo_id}', encodeURIComponent(String(requestParameters['photoId'])));
        urlPath = urlPath.replace('{size}', encodeURIComponent(String(requestParameters['size'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The image itself: to anyone when its route is public, else only to the route\'s owner.
     * Photo File
     */
    async coreApiCommunityPhotoFileRaw(requestParameters: PublicRoutesApiCoreApiCommunityPhotoFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.coreApiCommunityPhotoFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * The image itself: to anyone when its route is public, else only to the route\'s owner.
     * Photo File
     */
    async coreApiCommunityPhotoFile(requestParameters: PublicRoutesApiCoreApiCommunityPhotoFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiCommunityPhotoFileRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for coreApiCommunityPublicRouteElevation without sending the request
     */
    async coreApiCommunityPublicRouteElevationRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteElevationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityPublicRouteElevation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}/elevation`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public Route Elevation
     */
    async coreApiCommunityPublicRouteElevationRaw(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElevationOut>> {
        const requestOptions = await this.coreApiCommunityPublicRouteElevationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElevationOutFromJSON(jsonValue));
    }

    /**
     * Public Route Elevation
     */
    async coreApiCommunityPublicRouteElevation(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteElevationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElevationOut> {
        const response = await this.coreApiCommunityPublicRouteElevationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityPublicRouteForecast without sending the request
     */
    async coreApiCommunityPublicRouteForecastRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteForecastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityPublicRouteForecast().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling coreApiCommunityPublicRouteForecast().'
            );
        }

        if (requestParameters['time'] == null) {
            throw new runtime.RequiredError(
                'time',
                'Required parameter "time" was null or undefined when calling coreApiCommunityPublicRouteForecast().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = requestParameters['time'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}/forecast`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The weather on this route for the visitor\'s own departure: a forecast job like any other.  Signed-in visitors only, like all planning. The job is the visitor\'s, so the result is shaped for the visitor\'s tier, and it runs on the public line only.
     * Public Route Forecast
     */
    async coreApiCommunityPublicRouteForecastRaw(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteForecastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ForecastJobOut>> {
        const requestOptions = await this.coreApiCommunityPublicRouteForecastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ForecastJobOutFromJSON(jsonValue));
    }

    /**
     * The weather on this route for the visitor\'s own departure: a forecast job like any other.  Signed-in visitors only, like all planning. The job is the visitor\'s, so the result is shaped for the visitor\'s tier, and it runs on the public line only.
     * Public Route Forecast
     */
    async coreApiCommunityPublicRouteForecast(requestParameters: PublicRoutesApiCoreApiCommunityPublicRouteForecastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ForecastJobOut> {
        const response = await this.coreApiCommunityPublicRouteForecastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityUnlikeRoute without sending the request
     */
    async coreApiCommunityUnlikeRouteRequestOpts(requestParameters: PublicRoutesApiCoreApiCommunityUnlikeRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling coreApiCommunityUnlikeRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/public/routes/{slug}/like`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unlike Route
     */
    async coreApiCommunityUnlikeRouteRaw(requestParameters: PublicRoutesApiCoreApiCommunityUnlikeRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeOut>> {
        const requestOptions = await this.coreApiCommunityUnlikeRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeOutFromJSON(jsonValue));
    }

    /**
     * Unlike Route
     */
    async coreApiCommunityUnlikeRoute(requestParameters: PublicRoutesApiCoreApiCommunityUnlikeRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeOut> {
        const response = await this.coreApiCommunityUnlikeRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum CoreApiCommunityListPublicRoutesSortEnum {
    New = 'new',
    Popular = 'popular',
}
/**
  * @export
  * @enum {string}
  */
export enum CoreApiCommunityPhotoFileSizeEnum {
    Full = 'full',
    Thumb = 'thumb',
}
