/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ForecastJobOut,
    ForecastJobOutFromJSON,
    ForecastJobOutToJSON,
} from '../models/ForecastJobOut';
import {
    type RecurringRouteIn,
    RecurringRouteInFromJSON,
    RecurringRouteInToJSON,
} from '../models/RecurringRouteIn';
import {
    type RecurringRouteOut,
    RecurringRouteOutFromJSON,
    RecurringRouteOutToJSON,
} from '../models/RecurringRouteOut';

export interface RecurringRoutesApiCoreApiRecurringRouteCreateRouteRequest {
    /**
     * 
     */
    recurringRouteIn: RecurringRouteIn;
}

export interface RecurringRoutesApiCoreApiRecurringRouteDeleteRouteRequest {
    /**
     * 
     */
    routeId: string;
}

export interface RecurringRoutesApiCoreApiRecurringRouteGetRouteRequest {
    /**
     * 
     */
    routeId: string;
}

export interface RecurringRoutesApiCoreApiRecurringRouteRouteForecastRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    date: string;
    /**
     * 
     */
    time: string;
}

export interface RecurringRoutesApiCoreApiRecurringRouteUpdateRouteRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    recurringRouteIn: RecurringRouteIn;
}

/**
 * 
 */
export class RecurringRoutesApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiRecurringRouteCreateRoute without sending the request
     */
    async coreApiRecurringRouteCreateRouteRequestOpts(requestParameters: RecurringRoutesApiCoreApiRecurringRouteCreateRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recurringRouteIn'] == null) {
            throw new runtime.RequiredError(
                'recurringRouteIn',
                'Required parameter "recurringRouteIn" was null or undefined when calling coreApiRecurringRouteCreateRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/routes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringRouteInToJSON(requestParameters['recurringRouteIn']),
        };
    }

    /**
     * Create a new recurring route. Enqueues a background task to fetch route geometry.
     * Create Route
     */
    async coreApiRecurringRouteCreateRouteRaw(requestParameters: RecurringRoutesApiCoreApiRecurringRouteCreateRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringRouteOut>> {
        const requestOptions = await this.coreApiRecurringRouteCreateRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringRouteOutFromJSON(jsonValue));
    }

    /**
     * Create a new recurring route. Enqueues a background task to fetch route geometry.
     * Create Route
     */
    async coreApiRecurringRouteCreateRoute(requestParameters: RecurringRoutesApiCoreApiRecurringRouteCreateRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringRouteOut> {
        const response = await this.coreApiRecurringRouteCreateRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiRecurringRouteDeleteRoute without sending the request
     */
    async coreApiRecurringRouteDeleteRouteRequestOpts(requestParameters: RecurringRoutesApiCoreApiRecurringRouteDeleteRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiRecurringRouteDeleteRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a recurring route.
     * Delete Route
     */
    async coreApiRecurringRouteDeleteRouteRaw(requestParameters: RecurringRoutesApiCoreApiRecurringRouteDeleteRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.coreApiRecurringRouteDeleteRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a recurring route.
     * Delete Route
     */
    async coreApiRecurringRouteDeleteRoute(requestParameters: RecurringRoutesApiCoreApiRecurringRouteDeleteRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiRecurringRouteDeleteRouteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for coreApiRecurringRouteGetRoute without sending the request
     */
    async coreApiRecurringRouteGetRouteRequestOpts(requestParameters: RecurringRoutesApiCoreApiRecurringRouteGetRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiRecurringRouteGetRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single recurring route by ID.
     * Get Route
     */
    async coreApiRecurringRouteGetRouteRaw(requestParameters: RecurringRoutesApiCoreApiRecurringRouteGetRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringRouteOut>> {
        const requestOptions = await this.coreApiRecurringRouteGetRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringRouteOutFromJSON(jsonValue));
    }

    /**
     * Get a single recurring route by ID.
     * Get Route
     */
    async coreApiRecurringRouteGetRoute(requestParameters: RecurringRoutesApiCoreApiRecurringRouteGetRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringRouteOut> {
        const response = await this.coreApiRecurringRouteGetRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiRecurringRouteListRoutes without sending the request
     */
    async coreApiRecurringRouteListRoutesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the current account\'s active recurring routes by next departure.
     * List Routes
     */
    async coreApiRecurringRouteListRoutesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RecurringRouteOut>>> {
        const requestOptions = await this.coreApiRecurringRouteListRoutesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecurringRouteOutFromJSON));
    }

    /**
     * List the current account\'s active recurring routes by next departure.
     * List Routes
     */
    async coreApiRecurringRouteListRoutes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RecurringRouteOut>> {
        const response = await this.coreApiRecurringRouteListRoutesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiRecurringRouteRouteForecast without sending the request
     */
    async coreApiRecurringRouteRouteForecastRequestOpts(requestParameters: RecurringRoutesApiCoreApiRecurringRouteRouteForecastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiRecurringRouteRouteForecast().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling coreApiRecurringRouteRouteForecast().'
            );
        }

        if (requestParameters['time'] == null) {
            throw new runtime.RequiredError(
                'time',
                'Required parameter "time" was null or undefined when calling coreApiRecurringRouteRouteForecast().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = requestParameters['time'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}/forecast`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start (or join) the forecast for one departure of a saved route.  Returns 200 with the finished payload -- weather, Plotly figures and sections -- when an identical forecast is already computed and still fresh, otherwise 202 and a job to watch over `wsUrl`. Cell fetching and figure rendering both happen on workers; neither is allowed on this path.
     * Route Forecast
     */
    async coreApiRecurringRouteRouteForecastRaw(requestParameters: RecurringRoutesApiCoreApiRecurringRouteRouteForecastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ForecastJobOut>> {
        const requestOptions = await this.coreApiRecurringRouteRouteForecastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ForecastJobOutFromJSON(jsonValue));
    }

    /**
     * Start (or join) the forecast for one departure of a saved route.  Returns 200 with the finished payload -- weather, Plotly figures and sections -- when an identical forecast is already computed and still fresh, otherwise 202 and a job to watch over `wsUrl`. Cell fetching and figure rendering both happen on workers; neither is allowed on this path.
     * Route Forecast
     */
    async coreApiRecurringRouteRouteForecast(requestParameters: RecurringRoutesApiCoreApiRecurringRouteRouteForecastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ForecastJobOut> {
        const response = await this.coreApiRecurringRouteRouteForecastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiRecurringRouteUpdateRoute without sending the request
     */
    async coreApiRecurringRouteUpdateRouteRequestOpts(requestParameters: RecurringRoutesApiCoreApiRecurringRouteUpdateRouteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiRecurringRouteUpdateRoute().'
            );
        }

        if (requestParameters['recurringRouteIn'] == null) {
            throw new runtime.RequiredError(
                'recurringRouteIn',
                'Required parameter "recurringRouteIn" was null or undefined when calling coreApiRecurringRouteUpdateRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/routes/{route_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringRouteInToJSON(requestParameters['recurringRouteIn']),
        };
    }

    /**
     * Update a recurring route. Re-fetches geometry if start, destination, or profile changed.
     * Update Route
     */
    async coreApiRecurringRouteUpdateRouteRaw(requestParameters: RecurringRoutesApiCoreApiRecurringRouteUpdateRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringRouteOut>> {
        const requestOptions = await this.coreApiRecurringRouteUpdateRouteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringRouteOutFromJSON(jsonValue));
    }

    /**
     * Update a recurring route. Re-fetches geometry if start, destination, or profile changed.
     * Update Route
     */
    async coreApiRecurringRouteUpdateRoute(requestParameters: RecurringRoutesApiCoreApiRecurringRouteUpdateRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringRouteOut> {
        const response = await this.coreApiRecurringRouteUpdateRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
