/* tslint:disable */
/* eslint-disable */
/**
 * NoRain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type RouteWeatherOut,
    RouteWeatherOutFromJSON,
    RouteWeatherOutToJSON,
} from '../models/RouteWeatherOut';

export interface RouteWeatherApiCoreApiRouteWeatherRouteWeatherRequest {
    /**
     * 
     */
    startLat: number;
    /**
     * 
     */
    startLon: number;
    /**
     * 
     */
    destLat: number;
    /**
     * 
     */
    destLon: number;
    /**
     * 
     */
    profile: string;
    /**
     * 
     */
    departureTime: string;
    /**
     * 
     */
    intervalSeconds?: number;
}

/**
 * 
 */
export class RouteWeatherApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiRouteWeatherRouteWeather without sending the request
     */
    async coreApiRouteWeatherRouteWeatherRequestOpts(requestParameters: RouteWeatherApiCoreApiRouteWeatherRouteWeatherRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['startLat'] == null) {
            throw new runtime.RequiredError(
                'startLat',
                'Required parameter "startLat" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        if (requestParameters['startLon'] == null) {
            throw new runtime.RequiredError(
                'startLon',
                'Required parameter "startLon" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        if (requestParameters['destLat'] == null) {
            throw new runtime.RequiredError(
                'destLat',
                'Required parameter "destLat" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        if (requestParameters['destLon'] == null) {
            throw new runtime.RequiredError(
                'destLon',
                'Required parameter "destLon" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        if (requestParameters['profile'] == null) {
            throw new runtime.RequiredError(
                'profile',
                'Required parameter "profile" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        if (requestParameters['departureTime'] == null) {
            throw new runtime.RequiredError(
                'departureTime',
                'Required parameter "departureTime" was null or undefined when calling coreApiRouteWeatherRouteWeather().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startLat'] != null) {
            queryParameters['start_lat'] = requestParameters['startLat'];
        }

        if (requestParameters['startLon'] != null) {
            queryParameters['start_lon'] = requestParameters['startLon'];
        }

        if (requestParameters['destLat'] != null) {
            queryParameters['dest_lat'] = requestParameters['destLat'];
        }

        if (requestParameters['destLon'] != null) {
            queryParameters['dest_lon'] = requestParameters['destLon'];
        }

        if (requestParameters['profile'] != null) {
            queryParameters['profile'] = requestParameters['profile'];
        }

        if (requestParameters['departureTime'] != null) {
            queryParameters['departure_time'] = requestParameters['departureTime'];
        }

        if (requestParameters['intervalSeconds'] != null) {
            queryParameters['interval_seconds'] = requestParameters['intervalSeconds'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/route_weather`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Route Weather
     */
    async coreApiRouteWeatherRouteWeatherRaw(requestParameters: RouteWeatherApiCoreApiRouteWeatherRouteWeatherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RouteWeatherOut>> {
        const requestOptions = await this.coreApiRouteWeatherRouteWeatherRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RouteWeatherOutFromJSON(jsonValue));
    }

    /**
     * Route Weather
     */
    async coreApiRouteWeatherRouteWeather(requestParameters: RouteWeatherApiCoreApiRouteWeatherRouteWeatherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RouteWeatherOut> {
        const response = await this.coreApiRouteWeatherRouteWeatherRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
