/* tslint:disable */
/* eslint-disable */
/**
 * Meteolane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PhotoOut,
    PhotoOutFromJSON,
    PhotoOutToJSON,
} from '../models/PhotoOut';
import {
    type PhotoUpdateIn,
    PhotoUpdateInFromJSON,
    PhotoUpdateInToJSON,
} from '../models/PhotoUpdateIn';
import {
    type SharingIn,
    SharingInFromJSON,
    SharingInToJSON,
} from '../models/SharingIn';
import {
    type SharingOut,
    SharingOutFromJSON,
    SharingOutToJSON,
} from '../models/SharingOut';

export interface SharingApiCoreApiCommunityDeletePhotoRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    photoId: string;
}

export interface SharingApiCoreApiCommunityGetSharingRequest {
    /**
     * 
     */
    routeId: string;
}

export interface SharingApiCoreApiCommunityListPhotosRequest {
    /**
     * 
     */
    routeId: string;
}

export interface SharingApiCoreApiCommunityUpdatePhotoRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    photoId: string;
    /**
     * 
     */
    photoUpdateIn: PhotoUpdateIn;
}

export interface SharingApiCoreApiCommunityUpdateSharingRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    sharingIn: SharingIn;
}

export interface SharingApiCoreApiCommunityUploadPhotoRequest {
    /**
     * 
     */
    routeId: string;
    /**
     * 
     */
    file: Blob;
    /**
     * 
     */
    caption?: string;
    /**
     * 
     */
    lat?: number | null;
    /**
     * 
     */
    lon?: number | null;
}

/**
 * 
 */
export class SharingApi extends runtime.BaseAPI {

    /**
     * Creates request options for coreApiCommunityDeletePhoto without sending the request
     */
    async coreApiCommunityDeletePhotoRequestOpts(requestParameters: SharingApiCoreApiCommunityDeletePhotoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityDeletePhoto().'
            );
        }

        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling coreApiCommunityDeletePhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}/photos/{photo_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));
        urlPath = urlPath.replace('{photo_id}', encodeURIComponent(String(requestParameters['photoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Photo
     */
    async coreApiCommunityDeletePhotoRaw(requestParameters: SharingApiCoreApiCommunityDeletePhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.coreApiCommunityDeletePhotoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Photo
     */
    async coreApiCommunityDeletePhoto(requestParameters: SharingApiCoreApiCommunityDeletePhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.coreApiCommunityDeletePhotoRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for coreApiCommunityGetSharing without sending the request
     */
    async coreApiCommunityGetSharingRequestOpts(requestParameters: SharingApiCoreApiCommunityGetSharingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityGetSharing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}/sharing`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Sharing
     */
    async coreApiCommunityGetSharingRaw(requestParameters: SharingApiCoreApiCommunityGetSharingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharingOut>> {
        const requestOptions = await this.coreApiCommunityGetSharingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SharingOutFromJSON(jsonValue));
    }

    /**
     * Get Sharing
     */
    async coreApiCommunityGetSharing(requestParameters: SharingApiCoreApiCommunityGetSharingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharingOut> {
        const response = await this.coreApiCommunityGetSharingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityListPhotos without sending the request
     */
    async coreApiCommunityListPhotosRequestOpts(requestParameters: SharingApiCoreApiCommunityListPhotosRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityListPhotos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/routes/{route_id}/photos`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Photos
     */
    async coreApiCommunityListPhotosRaw(requestParameters: SharingApiCoreApiCommunityListPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PhotoOut>>> {
        const requestOptions = await this.coreApiCommunityListPhotosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PhotoOutFromJSON));
    }

    /**
     * List Photos
     */
    async coreApiCommunityListPhotos(requestParameters: SharingApiCoreApiCommunityListPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PhotoOut>> {
        const response = await this.coreApiCommunityListPhotosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityUpdatePhoto without sending the request
     */
    async coreApiCommunityUpdatePhotoRequestOpts(requestParameters: SharingApiCoreApiCommunityUpdatePhotoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityUpdatePhoto().'
            );
        }

        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling coreApiCommunityUpdatePhoto().'
            );
        }

        if (requestParameters['photoUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'photoUpdateIn',
                'Required parameter "photoUpdateIn" was null or undefined when calling coreApiCommunityUpdatePhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/routes/{route_id}/photos/{photo_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));
        urlPath = urlPath.replace('{photo_id}', encodeURIComponent(String(requestParameters['photoId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PhotoUpdateInToJSON(requestParameters['photoUpdateIn']),
        };
    }

    /**
     * Update Photo
     */
    async coreApiCommunityUpdatePhotoRaw(requestParameters: SharingApiCoreApiCommunityUpdatePhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PhotoOut>> {
        const requestOptions = await this.coreApiCommunityUpdatePhotoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhotoOutFromJSON(jsonValue));
    }

    /**
     * Update Photo
     */
    async coreApiCommunityUpdatePhoto(requestParameters: SharingApiCoreApiCommunityUpdatePhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PhotoOut> {
        const response = await this.coreApiCommunityUpdatePhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityUpdateSharing without sending the request
     */
    async coreApiCommunityUpdateSharingRequestOpts(requestParameters: SharingApiCoreApiCommunityUpdateSharingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityUpdateSharing().'
            );
        }

        if (requestParameters['sharingIn'] == null) {
            throw new runtime.RequiredError(
                'sharingIn',
                'Required parameter "sharingIn" was null or undefined when calling coreApiCommunityUpdateSharing().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/routes/{route_id}/sharing`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SharingInToJSON(requestParameters['sharingIn']),
        };
    }

    /**
     * Publish or hide a route, and choose how much of either end stays hidden.
     * Update Sharing
     */
    async coreApiCommunityUpdateSharingRaw(requestParameters: SharingApiCoreApiCommunityUpdateSharingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharingOut>> {
        const requestOptions = await this.coreApiCommunityUpdateSharingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SharingOutFromJSON(jsonValue));
    }

    /**
     * Publish or hide a route, and choose how much of either end stays hidden.
     * Update Sharing
     */
    async coreApiCommunityUpdateSharing(requestParameters: SharingApiCoreApiCommunityUpdateSharingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharingOut> {
        const response = await this.coreApiCommunityUpdateSharingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for coreApiCommunityUploadPhoto without sending the request
     */
    async coreApiCommunityUploadPhotoRequestOpts(requestParameters: SharingApiCoreApiCommunityUploadPhotoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling coreApiCommunityUploadPhoto().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling coreApiCommunityUploadPhoto().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['caption'] != null) {
            formParams.append('caption', requestParameters['caption'] as any);
        }

        if (requestParameters['lat'] != null) {
            formParams.append('lat', requestParameters['lat'] as any);
        }

        if (requestParameters['lon'] != null) {
            formParams.append('lon', requestParameters['lon'] as any);
        }


        let urlPath = `/api/routes/{route_id}/photos`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Add a photo. It is re-encoded without metadata; its position is only what the owner sets.
     * Upload Photo
     */
    async coreApiCommunityUploadPhotoRaw(requestParameters: SharingApiCoreApiCommunityUploadPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PhotoOut>> {
        const requestOptions = await this.coreApiCommunityUploadPhotoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhotoOutFromJSON(jsonValue));
    }

    /**
     * Add a photo. It is re-encoded without metadata; its position is only what the owner sets.
     * Upload Photo
     */
    async coreApiCommunityUploadPhoto(requestParameters: SharingApiCoreApiCommunityUploadPhotoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PhotoOut> {
        const response = await this.coreApiCommunityUploadPhotoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
