/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A contiguous segment of the route with uniform weather conditions.
 * @export
 * @interface RouteSection
 */
export interface RouteSection {
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    startKm: number;
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    endKm: number;
    /**
     * 
     * @type {string}
     * @memberof RouteSection
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof RouteSection
     */
    endTime: string;
    /**
     * 
     * @type {string}
     * @memberof RouteSection
     */
    condition: string;
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    maxRainMm: number;
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    maxHeadwind: number;
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    tempMin: number;
    /**
     * 
     * @type {number}
     * @memberof RouteSection
     */
    tempMax: number;
}

/**
 * Check if a given object implements the RouteSection interface.
 */
export function instanceOfRouteSection(value: object): value is RouteSection {
    if ((!('startKm' in value) && !('start_km' in value)) || (value['startKm'] === undefined && value['start_km'] === undefined)) return false;
    if ((!('endKm' in value) && !('end_km' in value)) || (value['endKm'] === undefined && value['end_km'] === undefined)) return false;
    if ((!('startTime' in value) && !('start_time' in value)) || (value['startTime'] === undefined && value['start_time'] === undefined)) return false;
    if ((!('endTime' in value) && !('end_time' in value)) || (value['endTime'] === undefined && value['end_time'] === undefined)) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if ((!('maxRainMm' in value) && !('max_rain_mm' in value)) || (value['maxRainMm'] === undefined && value['max_rain_mm'] === undefined)) return false;
    if ((!('maxHeadwind' in value) && !('max_headwind' in value)) || (value['maxHeadwind'] === undefined && value['max_headwind'] === undefined)) return false;
    if ((!('tempMin' in value) && !('temp_min' in value)) || (value['tempMin'] === undefined && value['temp_min'] === undefined)) return false;
    if ((!('tempMax' in value) && !('temp_max' in value)) || (value['tempMax'] === undefined && value['temp_max'] === undefined)) return false;
    return true;
}

export function RouteSectionFromJSON(json: any): RouteSection {
    return RouteSectionFromJSONTyped(json, false);
}

export function RouteSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteSection {
    if (json == null) {
        return json;
    }
    return {
        
        'startKm': json['start_km'],
        'endKm': json['end_km'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'condition': json['condition'],
        'maxRainMm': json['max_rain_mm'],
        'maxHeadwind': json['max_headwind'],
        'tempMin': json['temp_min'],
        'tempMax': json['temp_max'],
    };
}

export function RouteSectionToJSON(json: any): RouteSection {
    return RouteSectionToJSONTyped(json, false);
}

export function RouteSectionToJSONTyped(value?: RouteSection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_km': value['startKm'],
        'end_km': value['endKm'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'condition': value['condition'],
        'max_rain_mm': value['maxRainMm'],
        'max_headwind': value['maxHeadwind'],
        'temp_min': value['tempMin'],
        'temp_max': value['tempMax'],
    };
}

