# Generated by Django 5.2.6 on 2026-06-17 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('start_name', models.CharField(max_length=300)),
                ('dest_lat', models.FloatField()),
                ('dest_lon', models.FloatField()),
                ('dest_name', models.CharField(max_length=300)),
                ('profile', models.CharField(default='bike', help_text='GraphHopper routing profile: bike, ebike, fast_ebike, car, foot', max_length=50)),
                ('schedule_cron', models.CharField(help_text='5-field cron expression', max_length=100)),
                ('schedule_description', models.CharField(help_text="Human-readable, e.g. 'Every Monday at 08:00'", max_length=200)),
                ('polyline', models.JSONField(blank=True, help_text='[[lon, lat], ...] full route polyline', null=True)),
                ('total_seconds', models.IntegerField(blank=True, null=True)),
                ('total_distance_m', models.FloatField(blank=True, null=True)),
                ('sample_points', models.JSONField(blank=True, help_text='[{lat, lon, lat_r, lon_r, elapsed_s}, ...] pre-computed sample points with rounded coords', null=True)),
                ('geometry_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnsembleCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_r', models.FloatField(help_text='Latitude rounded to 2 decimal places')),
                ('lon_r', models.FloatField(help_text='Longitude rounded to 2 decimal places')),
                ('day_key', models.DateField(help_text="The 'today' date when the forecast was fetched")),
                ('forecast_days', models.IntegerField(help_text='Number of forecast days requested (1–16)')),
                ('data', models.JSONField(help_text='Raw ensemble API response (hourly precipitation series)')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat_r', 'lon_r', 'day_key'], name='core_ensemb_lat_r_3e0677_idx'), models.Index(fields=['fetched_at'], name='core_ensemb_fetched_b92b8a_idx')],
                'unique_together': {('lat_r', 'lon_r', 'day_key')},
            },
        ),
        migrations.CreateModel(
            name='ForecastCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_r', models.FloatField(help_text='Latitude rounded to 2 decimal places (~1 km)')),
                ('lon_r', models.FloatField(help_text='Longitude rounded to 2 decimal places (~1 km)')),
                ('day_key', models.DateField(help_text="The 'today' date when the forecast was fetched")),
                ('forecast_days', models.IntegerField(help_text='Number of forecast days requested (1–16)')),
                ('data', models.JSONField(help_text='Raw API response dict (minutely_15 + hourly blocks)')),
                ('source', models.CharField(help_text='"open-meteo" or "openweathermap"', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat_r', 'lon_r', 'day_key'], name='core_foreca_lat_r_ab7353_idx'), models.Index(fields=['fetched_at'], name='core_foreca_fetched_1289d9_idx')],
                'unique_together': {('lat_r', 'lon_r', 'day_key', 'source')},
            },
        ),
    ]
