# Generated by Django 6.1.1 on 2026-09-12 13:39

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = (("auth", "0012_alter_user_first_name_max_length"),)

    operations = (
        migrations.CreateModel(
            name="ProcessedStripeEvent",
            fields=[
                ("event_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("event_type", models.CharField(blank=True, default="", max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("email", models.EmailField(max_length=254, verbose_name="email address")),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EnsembleCell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat_r", models.FloatField(help_text="Latitude rounded to 2 decimal places")),
                ("lon_r", models.FloatField(help_text="Longitude rounded to 2 decimal places")),
                ("day_key", models.DateField(help_text="The 'today' date when the forecast was fetched")),
                ("forecast_days", models.IntegerField(help_text="Number of forecast days requested (1–16)")),
                ("data", models.JSONField(help_text="Raw ensemble API response (hourly precipitation series)")),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["lat_r", "lon_r", "day_key"], name="core_ensemb_lat_r_3e0677_idx"),
                    models.Index(fields=["fetched_at"], name="core_ensemb_fetched_b92b8a_idx"),
                ],
                "unique_together": {("lat_r", "lon_r", "day_key")},
            },
        ),
        migrations.CreateModel(
            name="ForecastCell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat_r", models.FloatField(help_text="Latitude rounded to 2 decimal places (~1 km)")),
                ("lon_r", models.FloatField(help_text="Longitude rounded to 2 decimal places (~1 km)")),
                ("day_key", models.DateField(help_text="The 'today' date when the forecast was fetched")),
                ("forecast_days", models.IntegerField(help_text="Number of forecast days requested (1–16)")),
                ("data", models.JSONField(help_text="Raw API response dict (minutely_15 + hourly blocks)")),
                ("source", models.CharField(help_text='"open-meteo" or "openweathermap"', max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["lat_r", "lon_r", "day_key"], name="core_foreca_lat_r_ab7353_idx"),
                    models.Index(fields=["fetched_at"], name="core_foreca_fetched_1289d9_idx"),
                ],
                "unique_together": {("lat_r", "lon_r", "day_key", "source")},
            },
        ),
        migrations.CreateModel(
            name="RecurringRoute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("start_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("start_name", models.CharField(max_length=300)),
                ("destination_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("dest_name", models.CharField(max_length=300)),
                (
                    "profile",
                    models.CharField(
                        default="bike",
                        help_text="GraphHopper routing profile: bike, ebike, fast_ebike, car, foot",
                        max_length=50,
                    ),
                ),
                ("schedule_cron", models.CharField(help_text="5-field cron expression", max_length=100)),
                (
                    "schedule_description",
                    models.CharField(help_text="Human-readable, e.g. 'Every Monday at 08:00'", max_length=200),
                ),
                (
                    "polyline",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True,
                        geography=True,
                        help_text="Full GraphHopper route line in WGS84",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("total_seconds", models.IntegerField(blank=True, null=True)),
                ("total_distance_m", models.FloatField(blank=True, null=True)),
                (
                    "sample_points",
                    models.JSONField(
                        blank=True,
                        help_text="[{lat, lon, lat_r, lon_r, elapsed_s, idx}, ...] pre-computed sample points with rounded coords",
                        null=True,
                    ),
                ),
                ("geometry_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("thumbnail", models.JSONField(blank=True, null=True)),
                ("thumbnail_computed_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this route. Routes without an owner are hidden from the app.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan", models.CharField(choices=[("free", "Free"), ("pro", "Pro")], default="free", max_length=20)),
                (
                    "status",
                    models.CharField(blank=True, default="", help_text="Stripe subscription status", max_length=32),
                ),
                ("stripe_customer_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, default="", max_length=255)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="core_user_email_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"), name="core_user_username_ci_unique"
            ),
        ),
    )
