# Generated by Django 6.1.1 on 2026-09-12 15:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0002_alter_user_managers'),
    )

    operations = (
        migrations.CreateModel(
            name='ForecastJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('adhoc', 'Ad-hoc route'), ('route', 'Saved route')], max_length=16)),
                ('params', models.JSONField(help_text='The request that asked for this forecast')),
                ('geometry', models.JSONField(blank=True, help_text='polyline, sample_points, total_seconds, total_distance_m', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planning', 'Planning'), ('fetching', 'Fetching cells'), ('assembling', 'Assembling'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('cells_total', models.IntegerField(default=0)),
                ('cells_settled', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_foreca_status_65b2fd_idx'), models.Index(fields=['updated_at'], name='core_foreca_updated_65c39e_idx')],
            },
        ),
    )
