# Generated by Django 6.1.1 on 2026-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("core", "0003_forecastjob"),
    )

    operations = (
        migrations.AddField(
            model_name="recurringroute",
            name="vertex_times",
            field=models.JSONField(
                blank=True, help_text="Floating-point elapsed seconds at every polyline vertex", null=True
            ),
        ),
    )
