# Generated by Django 6.1.1 on 2026-09-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("core", "0004_recurringroute_vertex_times"),)

    operations = (
        migrations.AddField(
            model_name="forecastjob",
            name="cells_failed",
            field=models.IntegerField(default=0),
        ),
    )
