# Generated by Django 6.1.1 on 2026-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0007_alter_recurringroute_profile'),
    )

    operations = (
        migrations.AddField(
            model_name='forecastjob',
            name='computed_weather',
            field=models.JSONField(blank=True, null=True),
        ),
    )
