# Generated by Django 6.1.1 on 2026-09-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_recurringroute_departure_flex_after_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringroute",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
