# Generated by Django 6.1.1 on 2026-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_recurringroute_briefing_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='complimentary_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
