# Generated by Django 6.1.1 on 2026-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_recurringroute_return_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="checkout_interval",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="checkout_session_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
