# Generated by Django 6.1.1 on 2026-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subscription_checkout_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringroute',
            name='via_points',
            field=models.JSONField(blank=True, default=list, help_text='[[lon, lat], ...] points the route must pass, in riding order'),
        ),
    ]
