# Generated by Django 6.1.1 on 2026-09-22 16:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_poi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastjob",
            name="kind",
            field=models.CharField(
                choices=[("adhoc", "Ad-hoc route"), ("route", "Saved route"), ("journey_stage", "Journey stage")],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("start_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("start_name", models.CharField(max_length=300)),
                ("destination_point", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ("dest_name", models.CharField(max_length=300)),
                (
                    "via_points",
                    models.JSONField(blank=True, default=list, help_text="[[lon, lat], ...] in riding order"),
                ),
                ("profile", models.CharField(default="bike", max_length=50)),
                ("start_date", models.DateField()),
                ("earliest_start", models.TimeField(help_text="Local time a day's ride may start")),
                ("latest_arrival", models.TimeField(help_text="Local time a day's ride should end")),
                ("max_day_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_day_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                ("max_leg_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_leg_distance_m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "poi_categories",
                    models.JSONField(blank=True, default=list, help_text="core.pois categories wanted on every leg"),
                ),
                (
                    "lodging_kinds",
                    models.JSONField(blank=True, default=list, help_text="tourism=* values a day may end at"),
                ),
                ("road_prefs", models.JSONField(blank=True, default=dict, help_text="core.road_prefs.RoadPrefs")),
                (
                    "weather_prefs",
                    models.JSONField(
                        blank=True, default=dict, help_text="avoid_rain, avoid_headwind, departure_window_minutes"
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("routing", "Routing"),
                            ("weather", "Fetching corridor weather"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("plan_revision", models.PositiveIntegerField(default=0)),
                ("plan_attempts", models.PositiveSmallIntegerField(default=0)),
                ("plan_error", models.TextField(blank=True, default="")),
                ("planned_at", models.DateTimeField(blank=True, null=True)),
                ("plan_state", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyDay",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("index", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                ("start", models.JSONField(help_text="[lon, lat]")),
                ("end", models.JSONField(help_text="[lon, lat]")),
                ("lodging", models.JSONField(blank=True, null=True)),
                ("lodging_missing", models.BooleanField(default=False)),
                ("weather_routed", models.BooleanField(default=False)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="days", to="core.journey"
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="JourneyStage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rank", models.PositiveSmallIntegerField(help_text="GraphHopper's order, 0 = its best path")),
                (
                    "via_points",
                    models.JSONField(blank=True, default=list, help_text="Gap-fill POIs routed through, [[lon, lat]]"),
                ),
                ("polyline", django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ("total_seconds", models.IntegerField()),
                ("total_distance_m", models.FloatField()),
                ("sample_points", models.JSONField()),
                ("vertex_times", models.JSONField()),
                ("geometry_fetched_at", models.DateTimeField()),
                (
                    "breaks",
                    models.JSONField(blank=True, default=list, help_text="[{along_m, elapsed_s, lon, lat, pois}]"),
                ),
                (
                    "gaps",
                    models.JSONField(blank=True, default=dict, help_text="{category: longest stretch without it, m}"),
                ),
                (
                    "detours",
                    models.JSONField(blank=True, default=list, help_text="Gap-fill POIs: [{poi..., category}]"),
                ),
                ("detour_m", models.FloatField(default=0, help_text="Extra distance the gap-fill vias cost")),
                (
                    "leg_m",
                    models.FloatField(default=0, help_text="The leg limit on this stage in metres; 0 = no breaks"),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="core.journeyday"
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="journeyday",
            constraint=models.UniqueConstraint(fields=("journey", "index"), name="unique_journey_day"),
        ),
    ]
