# Generated by Django 6.1.1 on 2026-09-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_recurringroute_gpx'),
        ('core', '0018_journeys'),
    ]

    operations = [
    ]
