# Generated by Django 6.1.1 on 2026-09-23 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_merge_0017_recurringroute_gpx_0018_journeys"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellFetchLease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("forecast", "Forecast"), ("ensemble", "Ensemble")], max_length=16)),
                ("lat_r", models.FloatField()),
                ("lon_r", models.FloatField()),
                ("day_key", models.DateField()),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "lat_r", "lon_r", "day_key"), name="unique_cell_fetch_lease"
                    )
                ],
            },
        ),
    ]
