# Generated by Django 6.1.1 on 2026-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_route_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='lodging_detour',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='leg_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='limit_overruns',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='leg_m',
            field=models.FloatField(default=0, help_text='The leg distance limit; legacy rows may hold a time-derived distance'),
        ),
    ]
