# Generated by Django 6.1.1 on 2026-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_journey_routed_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="kind",
            field=models.CharField(
                choices=[("tour", "Tour"), ("random", "Random ride")],
                default="tour",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="random_prefs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random rides only: round_trip, heading, seed (core.random_rides)",
            ),
        ),
    ]
