# Generated by Django 6.1.1 on 2026-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_journey_routed_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='poi',
            name='osm_ref',
            field=models.CharField(help_text='n123 / w456 / r789', max_length=32),
        ),
    ]
