# Generated by Django 6.1.1 on 2026-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_journey_routed_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_profile",
            field=models.CharField(
                choices=[
                    ("bike", "bike"),
                    ("ebike", "ebike"),
                    ("fast_ebike", "fast_ebike"),
                ],
                default="bike",
                max_length=16,
            ),
        ),
    ]
