# Generated by Django 6.1.1 on 2026-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Also joins main's two 0025 branches, which both start from 0024.
        ("core", "0025_poi_drop_redundant_indexes"),
        ("core", "0025_public_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="kind",
            field=models.CharField(
                choices=[("tour", "Tour"), ("random", "Random ride")],
                default="tour",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="random_prefs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Random rides only: round_trip, heading, seed (core.random_rides)",
            ),
        ),
    ]
