# Generated by Django 6.1.1 on 2026-09-27 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_poi_drop_redundant_indexes"),
        ("core", "0025_public_routes"),
    ]

    operations = []
