# Generated by Django 6.1.1 on 2026-09-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_default_profile'),
        ('core', '0026_merge_20260927_1004'),
    ]

    operations = [
    ]
