# Generated by Django 6.1.1 on 2026-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20260927_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=8),
        ),
    ]
