# Generated by Django 6.1.1 on 2026-09-28 11:48

import django.db.models.functions.text
from django.db import migrations, models


def seed_switzerland(apps, schema_editor):
    """What the app covers today: routing and search in Switzerland."""
    apps.get_model("core", "CoverageArea").objects.get_or_create(code="CH", defaults={"status": "covered"})


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="German. Empty for a country.",
                        max_length=100,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="English. Empty: the German name.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("covered", "Covered"),
                            ("planned", "Planned"),
                            ("candidate", "Open for votes"),
                        ],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="German, optional.",
                        max_length=200,
                    ),
                ),
                (
                    "note_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="English, optional.",
                        max_length=200,
                    ),
                ),
                ("covered_since", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CoverageSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=254)),
                (
                    "language",
                    models.CharField(
                        choices=[("de", "Deutsch"), ("en", "English")],
                        default="de",
                        max_length=8,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("area_code"),
                        django.db.models.functions.text.Lower("email"),
                        name="core_coveragesubscription_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CoverageVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.CharField(max_length=6)),
                ("voter", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["voter"], name="core_covera_voter_856cd9_idx")],
                "constraints": [models.UniqueConstraint(fields=("area_code", "voter"), name="core_coveragevote_once")],
            },
        ),
        migrations.RunPython(seed_switzerland, migrations.RunPython.noop),
    ]
