# Generated by Django 6.1.1 on 2026-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_garmin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringroute',
            name='profile',
            field=models.CharField(default='bike', help_text='GraphHopper routing profile: bike, ebike, fast_ebike, hike', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_profile',
            field=models.CharField(choices=[('bike', 'bike'), ('ebike', 'ebike'), ('fast_ebike', 'fast_ebike'), ('hike', 'hike')], default='bike', max_length=16),
        ),
    ]
