# Generated by Django 6.1.1 on 2026-09-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_coverage'),
        ('core', '0030_user_default_profile_hike'),
    ]

    operations = [
    ]
