# Generated by Django 6.1.1 on 2026-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_coveragevote_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringroute",
            name="stops",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
